### ISSUE TITLE
forking breaks the build process

### ISSUE THREAD

**Issue by minimaldesign** [react-component/slider#100]
Hi!

Thanks again for the great plugin!

I tried to fork your project (in order to make the tooltip show by default), but when I then include my fork in my package.json file, the `lib` folder is not there, so I tried to add this postinstall script:
```
"postinstall": "npm run build"
```
But I'm getting a `Exit status 1` error… Is there something you need to patch in order to get your plugin to work from a forked repo or is there something on my end I can do to get it working?

Thanks for any pointer in the right direction!

**Comment by benjycui** [comment]
`lib` is builded. And source code is here: https://github.com/react-component/slider/tree/master/src

**Comment by benjycui** [comment]
And I don't understand why you need `lib`.
If you had modified rc-slider and want to use it in your project, just publish you own slider @xxx/rc-slider.

**Comment by memoblue** [comment]
when I include your version in my package.json, I can see a `lib` folder in the `/node_modules/rc-slider/` directory and everything works great, but when I use `https://github.com/minimaldesign/slider` there is no `lib` folder and I get a bunch of "missing files" errors when I try to run my app.

That's why I assume when I install your version, the build process works, but I install my version, the build process doesn't work. And that's what I'm trying to fix… Makes sense?

Thanks for your answer!

**Comment by minimaldesign** [comment]
when I include your version in my package.json, I can see a `lib` folder in the `/node_modules/rc-slider/` directory and everything works great, but when I use `https://github.com/minimaldesign/slider` there is no `lib` folder and I get a bunch of "missing files" errors when I try to run my app.

That's why I assume when I install your version, the build process works, but I install my version, the build process doesn't work. And that's what I'm trying to fix… Makes sense?

Thanks for your answer!

**Comment by benjycui** [comment]
`lib` is built while publish(`npm run pub`). So, just publish your own rc-slider.

Tips: modify `package.json.name` before publish.

**Comment by just-boris** [comment]
@minimaldesign my approach to maintaining forks that require extra build actions is create special branch in your fork where you can commit and store built files.

See a related issue in another my project: https://github.com/webdriverio/wdio-allure-reporter/pull/10
