### ISSUE TITLE
Composable components?

### ISSUE THREAD

**Issue by tpae** [react-component/slider#103]
I noticed if I wanted to add custom logic to the Handle, I can't import the handle directly to build my own slider.

from
```
import Rcslider from 'rc-slider'
```
to
```
import {Handle, Track} from 'rc-slider'
```

That way, I can add custom class names to my handle, and it would make it easy to extend it and customize the slider. What do you think?

**Comment by benjycui** [comment]
I will review this PR later https://github.com/react-component/slider/pull/102
