### ISSUE TITLE
about tipFormatter question?

### ISSUE THREAD

**Issue by feifeiiiiiiiiiii** [react-component/slider#109]
I read about show `tips` code, and found code as follow:

`
 const isNoTip = (step === null) || (tipFormatter === null);
`
why `show tips` need two condition control, and I think control `tips show` only need `tipFormatter` and not need `step`

**Comment by benjycui** [comment]
If you set `marks` and `step={null}`, tooltip is unnecessary http://react-component.github.io/slider/examples/marks.html
