### ISSUE TITLE
React dependency issue

### ISSUE THREAD

**Issue by ChuckPierce** [react-component/slider#112]
It seems that `rc-util` uses react 15 when it bumped up to version 3.2.  I think things should be consistent in terms of having react 0.14 and react 15 compatible versions of `rc-slider`.  Not sure how you would want to proceed.

**Comment by benjycui** [comment]
So... did you meet errors/warnings?

It would be better if you could provide more infomation.

**Comment by ChuckPierce** [comment]
Yes very sorry!

I'm referring to this issue with `rc-util` https://github.com/react-component/util/issues/5

It's giving off a warning for an unmet dependency because `rc-uti` switched to using react 15.  Since this component currently uses react 0.14 a user that installs the latest package with `npm2` will ultimately have two versions of react installed in their dependencies.  If using `npm3` they will get a warning that react 15 was not installed.  

Hopefully this makes things clear.  Options are to roll back the `rc-util` dependency to 3.1 which uses react 0.14 to get rid of the warning or just upgrade everything to react 15.

**Comment by benjycui** [comment]
Fixed in https://github.com/react-component/util/commit/d5841333f298635d414d49e9add43cdb491a49c8
