### ISSUE TITLE
Feature: ability to select start value for a continuous interval

### ISSUE THREAD

**Issue by AlexeyToksarov** [react-component/slider#113]
Please see an example "Slider with visible selection bar from a value" on http://angular-slider.github.io/angularjs-slider/
What do you think?

**Comment by just-boris** [comment]
Hello! 
As far as I see, you can implement it now with range slider, but hide the first handler with extra CSS.

Does it work for you?

**Comment by AlexeyToksarov** [comment]
Yep, I've tried this.
The tricky part is when we try to move the right handle of the slider to the left side, at the moment when it passes the left handle, they sort of switch places and if we proceed with moving to the left side, we will start to drag the left handle instead of the right.
So I cannot just hide the first handler for example.

**Comment by benjycui** [comment]
Try to [customized handle](http://react-component.github.io/slider/examples/custom-handles.html).

Tips: 

```jsx
const Handle = require('rc-slider/lib/Handle');

function CustomizedHandle(props) {
  // do something
  return value === xx ? null: <Handle {...props} />;
}
```
