### ISSUE TITLE
ToolTip: visible only first time.

### ISSUE THREAD

**Issue by nidhir-systango** [react-component/slider#114]
Tooltip on the slider(which displays min and max value of Range visible only first time of Form submitting). When I open the form next time tooltip is not visible.

**Comment by benjycui** [comment]
Sorry, I don't understand. Could you provide more information? It would be better if you provide and online demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by jazoom** [comment]
I cannot get the tooltip to show up at all, even when copying the examples exactly.

**Comment by benjycui** [comment]
@jazoom it works fine in my project. So, could you provide a re-producible demo?

**Comment by jazoom** [comment]
I decided to use a different slider solution (unrelated to the tooltip issue) so I don't have the code anymore. Maybe it's because I'm using React 15.2? I can't think what else could be significantly different to your project.

**Comment by benjycui** [comment]
NVM, I am using React@15.2.x, too.
