### ISSUE TITLE
Feature request: rc-slider should have ability to adjust the position of marks

### ISSUE THREAD

**Issue by bhutaninitin** [react-component/slider#115]
I have a feature request. Imagine a range between 0 and 10456543 with marks at 256, 4080, and 1000000. The rc-slider currently fails to render them properly . 
There should be a option like marks_points=[0,25,50,100] which can be specified with marks=[0,256,4080,1000000] so that those marks render at the specified mark_points.

**Comment by AlexeyToksarov** [comment]
Why are these examples do not work for you?
http://react-component.github.io/slider/examples/marks.html

**Comment by bhutaninitin** [comment]
No.  These examples work on a small range (-10 to 100). I am talking about a big range.. say 0 to 10000000 with marks at 10, 20, 260, 50000, and 10000000.

Sent from Yahoo Mail on Android 
 
  On Tue, 5 Jul, 2016 at 1:20, Alexey Toksarov<notifications@github.com> wrote:   
Why are these examples do not work for you?
http://react-component.github.io/slider/examples/marks.html

**Comment by benjycui** [comment]
It works fine with big rang:

![image](https://cloud.githubusercontent.com/assets/3580607/16717676/8e17a67a-474b-11e6-874c-b04c605304f9.png)

**Comment by bhutaninitin** [comment]
Try setting 300, 400, 1000, as marks in your big range example. These marks all clutter on the left side. With a feature like mark_points, you can actually set the position of the marks based so that they do not clutter in one place.

**Comment by benjycui** [comment]
Of course you can. See: http://react-component.github.io/slider/examples/marks.html

**Comment by zverexe** [comment]
Is this fixed? I still cannot adjust position, if I have values like 100, 200 and 260 there is big gap between 100 and 200
