### ISSUE TITLE
Initializing with null value

### ISSUE THREAD

**Issue by shulcsm** [react-component/slider#119]
What's the expected behavior for initializing with null?
Now if you initialize with null and then click for first position value doesn't get set.

This is caused by coercing prop value to first value here https://github.com/react-component/slider/blob/master/src/Slider.jsx#L44
So this here https://github.com/react-component/slider/blob/master/src/Slider.jsx#L211  becomes `1=1` and onChange doesn't get triggered.

**Comment by shulcsm** [comment]
nvm, judging by proptypes null is not supported.

**Comment by champeng** [comment]
@shulcsm I need something similar. I need to avoid default rendering of active slider step, how can we do that?

**Comment by shulcsm** [comment]
@champeng 
```
class NullableSlider extends RcSlider {
  constructor(props) {
    super(props)
    this.state.touched = props.value !== null
  }
  onStart(position) {
    super.onStart(position)
    // @FIXME, doesn't handle ranges
    const { touched, upperBound } = this.state
    if (!touched) {
      this.onChange({ upperBound })
      this.setState({ touched: true })
    }
  }
}
```

**Comment by champeng** [comment]
Thanks @shulcsm for the response. However, I didn't get how it would prevent rendering of active slider step. I tried this one but it is still rendering the first step as active.

**Comment by champeng** [comment]
Idea is good. Actually I have ended up in something similar. I have added one custom class in the wrapper div of Slider component when there is a null value required and I have undone the active style changes in that css class. Thanks for your help.
