### ISSUE TITLE
Prefix for current value and always show tooltip?

### ISSUE THREAD

**Issue by reintroducing** [react-component/slider#121]
I'm building a slider where I want the value to have a prefix (in my case $) and I want it to always show.  Is there any way to currently do this?  Here is the slider:

https://www.dropbox.com/s/1cq95p4czx73p5r/Screenshot%202016-07-20%2016.08.32.png?dl=0

It would be great if this was supported some way.

**Comment by benjycui** [comment]
Try http://react-component.github.io/slider/examples/custom-handles.html

**Comment by reintroducing** [comment]
Thanks, I saw that, but there is no way to pass down a prefix for the handle to apply before the value so you have to create a custom handle every time. It should be a prop that gets passed in because one time the prefix may be `$` but another time it may not be dollar values at all so I'd like to pass in either nothing or a different string, etc. If you'd like I can submit a PR with the change.

**Comment by reintroducing** [comment]
Disregard, realized I could do this and it'll get passed through: `handle={<RangeSliderHandle prefix={currentLabelPrefix} />}`.

Thanks!
