### ISSUE TITLE
Styles not imported

### ISSUE THREAD

**Issue by vgrafe** [react-component/slider#124]
My setup : webpack and ES6. 

Even with the clues offered on #88 and #53, I can't find a way to import the css, the component stays invisible.

using `import 'rc-slider/assets/index.css'` does not change anything. I also tried to copy the css and link it to the base html file, without success.

What would be a starting point to resolve this, either with a PR or by linking the css another way?

**Comment by benjycui** [comment]
Try to copy a simple [demo](https://github.com/react-component/slider/blob/master/examples/slider.js) to test.

I am not sure whether your webpack config is right.

**Comment by melinaschweizer** [comment]
I am having the same issue.. how was this resolved?
