### ISSUE TITLE
setting more than two handles

### ISSUE THREAD

**Issue by coding-saints** [react-component/slider#128]
Is it possiblle to set 3 or more handles? Im guessing due to "lower" and "upper" I'm probably not goin to be able to obtain this,If it is at all possible I would like to see an example please.
Thanks

**Comment by Vivekbhusal** [comment]
hey @coding-saints , you have got it right. It's not possible at the moment. But if you could provide a user story that defines use case of 3 handles, we can start a  issue for that.

**Comment by benjycui** [comment]
> provide a user story

+1

**Comment by coding-saints** [comment]
I would like a range slider to set 3 range points for screen size: one range for 0px to 460px. A second range for 460-780, and a 3rd range 780 to 1200px. Then I want to add a range that would allow a specific element to be shown if the screen size is 1200-1300px.

Let me know if this makes sense, multiple handles to set multiple screen sizes to display content.

**Comment by benjycui** [comment]
....

It's weirdo.

Actually, I think you can use three `Slider` with label. It will be more user friendly.

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/17281221/4f284cca-57cd-11e6-9961-92cf2619b0bc.png)

**Comment by coding-saints** [comment]
Yea I figured it sounded wompy. I just need to be able to add more than 2 handles, thats all

**Comment by Vivekbhusal** [comment]
@coding-saints : If I understood it correctly, you are not looking for range style slider rather three isolated handlers.

**Comment by coding-saints** [comment]
@Vivekbhusal : Exactly. My 2 pennies are that one could add multiple (3 or more) handles and style accordingly (i.e. use some type of `connect` function to create a range if needed).

**Comment by benjycui** [comment]
I know what you want, but I don't think it is a good user experience for users don't know the meaning of each value.

Just use three isolated Slider, and a label to describe the meaning of it's value.

**Comment by coding-saints** [comment]
Im still not sure you understand, actually. Because the range would be set between 0px and 9999px . The range would be set on that note. The issue I am having is setting multiple breaks. And I need the breaks to be 'dynamic', hence the need for 3 or more handles. Fir my use case, i think it would be more friendly to have 1 slider to control breakpoints, rather than have to control multiple sliders for setting the media queries.
