### ISSUE TITLE
Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

### ISSUE THREAD

**Issue by reintroducing** [react-component/slider#129]
I've got rc-slider on a page in a much larger application that also contains jQuery (legacy code, don't ask).  When I drag on the slider I'm seeing this in the console: https://www.dropbox.com/s/jnqkstq0tl9y6t3/Screenshot%202016-07-28%2011.30.51.png?dl=0

This is when I have Chrome in the device toolbar mode looking at an iPhone, for instance (emulating).  It does not happen in your demo pages so I assume its coming from jQuery though I'm not sure why it would be picking this up and showing the warnings. It has no effect on the slider whatsoever but its quite annoying to get the console filled with those. I was able to comment out the pauseEvent method in onTouchStart and that stopped the warning but couldn't figure out where to comment out the code to prevent the warning from firing on drag.

Any idea why this would be happening? And subsequently how to fix it?

**Comment by benjycui** [comment]
I have no idea, either...

But it seems that this warning is threw by jQuery or React.
