### ISSUE TITLE
If min === max, handle should display on the left hand side. (low priority)

### ISSUE THREAD

**Issue by Streemo** [react-component/slider#132]
Currently, when min === max, the handle sits on the right hand side (at the end). Perhaps a prop should be provided to indicate the preferred parity of the slider? For example, in my use case, the slider's min and max values are dynamic. Sometimes, those values are both zero, in which case we'd want the user to see the handle on the left hand side, since the left hand position indicates "nothing", whereas the right hand position indicates "maximum", which makes no sense when the min and max are both 0.

Thanks.

**Comment by benjycui** [comment]
It works as expected:

```jsx
<Slider mix={0} max={0} />
```

![image](https://cloud.githubusercontent.com/assets/3580607/17468129/60af80f0-5d57-11e6-8593-e77ad4f5a7ef.png)
