### ISSUE TITLE
Distracting PropTypes warnings on development fork

### ISSUE THREAD

**Issue by kfatehi** [react-component/slider#134]
Hi I have forked the project in order to add a feature I need, however I keep getting the React PropTypes deprecation warning. My procedure was to fork and clone and then `npm link` that into my project.

This worked fine enough in that I was able to use the component in the context of my app however the console floods with the PropTypes deprecation warning (which is actually an "error," so I can't even filter it out).

Any tips on what I'm doing wrong here would be appreciated. I am guessing it has something to do with the fact that the `rc-slider` on npm is in transpiled form and in a `lib` directory whereas I'm trying to edit, webpack, and execute the `src` which does more things with PropTypes or something like that... Maybe I need some kind of webpack plugin that is dropping the PropTypes the way `slider` does when it packages itself for npm?

Anyway thanks in advance, and nice slider component 👍

**Comment by benjycui** [comment]
Could you provide the warning message.

**Comment by kfatehi** [comment]
Unfortunately I didn't take a screenshot and have long since changed my environment -- I ended up writing my own slider today using d3 inside a `ref` callback.

All I remember is that the error linked me to this https://facebook.github.io/react/warnings/dont-call-proptypes.html

I just spent the past 30 mins trying to setup a new project in order to replicate the issue but I ran into a new error instead 

```
reactProdInvariant.js:12Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

The crux of my complaint stemmed from the fact that the tooling is too complex or abstracted out (what is rc-tool? i couldn't figure it out. where are the babel and webpack configs? are they hidden somewhere in rc-* deps? i couldn't find them. does your project get compiled by the babel/webpack confs of my project or do those tools go read the configs of your project while transpiling your lib and then magically insert the result in the right place) to the point where contribution is made damn near impossible. Please understand I'm complaining about the state of our javascript ecosystem right now, it's kind of an unavoidable problem at the moment while we are transitioning to ES6 and so on. I hope that it gets better soon. As a result of this bullshit I ended up creating yet another Slider instead of just making yours better.
