### ISSUE TITLE
Feature Request: Restrict slider's values only to the defined marks.

### ISSUE THREAD

**Issue by Streemo** [react-component/slider#138]
There should be a way to restrict the possible values of a slider only to the defined marks. The handle would "jump" between marks. A use case might be in selecting available times between a range: 12:00am to 11:45pm (step 15 minutes).  There may only be events for 10-20 times in this range. It would be better if the slider "jumped" between marks.

Example:
```
"M": Mark
"<== ... ==>": Slider
"H_i": Allowed locations of Handle

   H_1 H_2      H_3             H_4 H_5   
<==M===M========M===============M===M==>
```
The handle must jump between H_i and H_i+/-1, and can only occupy positions H_i.

This setting would make the slider isomorphic to a select menu.

**Comment by benjycui** [comment]
If I didn't misunderstand your issue, this feature had been support:

```jsx
<Slider min={-10} marks={marks} step={null} onChange={log} defaultValue={20} />
```

http://react-component.github.io/slider/examples/marks.html

**Comment by Streemo** [comment]
Hi, thanks -- I must've missed it in the README.md
