### ISSUE TITLE
Setting z-index on tooltips

### ISSUE THREAD

**Issue by brandonmp** [react-component/slider#143]
Is there a way to adjust the zIndex on the tooltips? I'm using this component in a draw component (a slide-in menu), but the tool tips are rendering beneath the drawer

**Comment by derrickpelletier** [comment]
Taking a look at this, i recently removed z-index for slider as it was breaking with other layered components.

**Comment by derrickpelletier** [comment]
that i can recreate it this by wrapping a slider in a `<div>` element with a z-index and `position: absolute or relative`

Rolling back commits to prior to the z-index removal (commit #cf45d68) makes it work but only if the wrapping element has a z-index less than 5.

**Comment by brandonmp** [comment]
thanks @derrickpelletier I think that'd work for my purposes--the default `z-index` on the drawer component I'm using (Material-UI) is 2.

is it equally straightforward to make the `z-index` an option? either binary toggle or passable integer?

**Comment by derrickpelletier** [comment]
It's probably not unreasonable to expose the `rc-tooltip` `overlayStyle` prop...

The problem stems from the fact that rc-tooltip is mounted outside of the dom context of the slider itself. It is positioned absolutely and doesn't have a z-index.

This makes me think i might have been incorrect before when I said it worked on the previous commit, as the z-index would still be below the "drawer".

**Comment by derrickpelletier** [comment]
You could probably just add your own `css` in either case. Such as:

```css
.rc-tooltip {
  z-index: 3;
}
```

**Comment by brandonmp** [comment]
hmm that doesn't immediately work, but I can futz w/ it a little later.  I almost exclusively use in-line styles so I'll have to figure out if I'm setting that correctly in the context of my project.

**Comment by derrickpelletier** [comment]
Yeah sorry, without knowing the exact makeup of your dom/styles it's hard to say what the override is. Good luck.

**Comment by benjycui** [comment]
Sorry for late response, busy with other open source.

@brandonmp I am curious why this doesn't work? Could you provide a re-producible online-demo?

```css
.rc-tooltip {
  z-index: n;
}
```

**Comment by brandonmp** [comment]
hey @benjycui np. i ended up dropping the tooltips for now & just designing around it. if it comes up again I'll push an example to a public repo--thanks for following-up!

**Comment by cpmech** [comment]
So, this is still an issue, right?

**Comment by benjycui** [comment]
@cpmech if you met this issue, please provide a re-producible online demo, thanks.
