### ISSUE TITLE
onChange called even when value did not change

### ISSUE THREAD

**Issue by Fuzzyma** [react-component/slider#144]
Hey! Thx for this great component.
I found a big(?) visible when used with small min/max (like 1-5). onChange is triggered on every mousemove while dragging the handle.
The value is not changed duo to the big distance from one point to the next - still onChange triggers.

Imo that should be fixed since it can lead to performance issues (especially when the values of the slider are used in other components)

// EDIT: I digged a bit and it turned out, that `oldValue` is always `undefined` (https://github.com/react-component/slider/blob/d7e6b9d9be1c4776cae2447a4256767b3df3c310/src/Slider.jsx#L118)

Simply changing the line to: `const oldValue = state[state.handle];` fixed this problem

**Comment by ryan4888** [comment]
Also having this issue.
