### ISSUE TITLE
rc-slider styles affect the tooltips outside the slider

### ISSUE THREAD

**Issue by matias91** [react-component/slider#147]
Hi! Sorry to bother.
I just started to use this component, but also i was using the **rc-tooltip** component, and i noticed that the styles inside the slider component are affecting all the tooltips i use.

There will be some way to prevent this behavior?

Thanks in advance!

**Comment by benjycui** [comment]
You can try to solve this problem with `prefixCls="rc-slider-xx"` now.

And I will fix this bug in next version.
