### ISSUE TITLE
Color width between marks on slider

### ISSUE THREAD

**Issue by janhartmann** [react-component/slider#152]
Hi, thanks for this awesome library.

I am currently "abusing" this slider to do some crazy work with dates and it's all going great. I am wondering if its possible to add a dynamic width to each dot on the slider?

My use case for this, is that I wish to mark a range on the slider with a special color. And I think of expanding the width of the "dot" (a line on the slider in my case). 

I would like to add a dynamic width on the `.rc-slider-dot` element. E.g. by possible extending the marks styling to include the styling for the dot.

Thanks

**Comment by janhartmann** [comment]
This is my case. On this slider there is 4 dots - I wish to fill out the space between:

<img width="705" alt="udklip" src="https://cloud.githubusercontent.com/assets/1107383/18702031/26027574-7fe0-11e6-834c-8fd2544f826c.PNG">

**Comment by benjycui** [comment]
I am not sure whether this feature can solve your problem: https://github.com/react-component/slider/pull/117

cc @alampros

**Comment by janhartmann** [comment]
I actually solved this issue by adding child components, to the slider and calculating the width of items using the approach used in the `Track` component.

**Comment by alampros** [comment]
@benjycui Worked perfectly –Thank you! 🍻
