### ISSUE TITLE
Keep "pushable" between states/values

### ISSUE THREAD

**Issue by monsieurnebo** [react-component/slider#159]
Hi,

I'm storing the slider value in a redux state in the goal of keeping an history (you can switch between previous values by going back in your browser).

It seems that we can't keep the **pushable** props between two states using a different **value**.

If I don't specify any value in the Slider, the pushable props still work. If you set the value props (to update the display at each state), the pushable props stop working.

Any idea to fix this ?

**Comment by benjycui** [comment]
@sosz could you review this issue?

**Comment by patrickdevivo** [comment]
+1 I'm seeing similar issue, `pushable` prop only seems to work when `value` is not set

**Comment by it4anna** [comment]
The same affect on allowCross={false} :(

**Comment by dannypk** [comment]
Would be nice to have an overlapping = false or something, so when you have 2 values, they cannot be the same. I am trying to make a workaround, but seems that the values array mixes the values[0] with values[1] when they "overlap"

**Comment by paranoidjk** [comment]
close since dulplicate, please trace https://github.com/react-component/slider/issues/347
