### ISSUE TITLE
Actually a suggestion for improvement - not sure how to file this...

### ISSUE THREAD

**Issue by giladbr** [react-component/slider#160]
So the problem I'm solving is that you have to click the gray slider line very exactly to trigger the onclick.
This was considered a major problem with our PM and customers because it seemed the slider wouldn't respond to some of the clicks.

My solution is simple - add padding to the main line:

```
.rc-slider {
//[...]
   padding: 10px 2px; //or whatever other size you want the clickable area to be
}
```

And to avoid the line getting thicker, replace `background-color: #C0C0C0;` with `background: url('/PATH/TO/sliderBackground.jpg') repeat-x center;` - a simple background image of 2px X 1px gray (for some reason attaching the image to this issue isn't working).

**Comment by benjycui** [comment]
Make sense, actually, you can set `margin: 5px 0`

**Comment by benjycui** [comment]
5.1.3

**Comment by giladbr** [comment]
Nope, tried that, margin is not part of the element and therefore not
clickable... Think of a button with 100px margin, the button just gets
pushed downwards, the margin area isn't clickable. Needs to be padding.

**Comment by benjycui** [comment]
5.2.0
