### ISSUE TITLE
Why you need this check?

### ISSUE THREAD

**Issue by savelichalex** [react-component/slider#161]
Why you need this check https://github.com/react-component/slider/blob/master/src/Slider.jsx#L93-L95
This check is trigger onChange, but I don't understand why. If I remove this, all work fine.

**Comment by benjycui** [comment]
You cannot set a value which is smaller than `min` or bigger thatn `max`.

**Comment by savelichalex** [comment]
And why then onChange is calling?

**Comment by benjycui** [comment]
For customized `value` has been reset.
