### ISSUE TITLE
Slider.js:423 Uncaught TypeError: Cannot read property 'toFixed' of undefined(…)

### ISSUE THREAD

**Issue by ql** [react-component/slider#162]
Hello!
I'm trying to set up logarithmic scale slider (as described in https://github.com/react-component/slider/issues/150) with value and marks:

`<Slider defaultValue={ 100 }  marks={{10:'10', 100:'100', 1000:'1000', 10000:'10k', 100000:'100k'}} value={[10, 100, 1000, 10000, 100000]} onChange={this.onSpendingChange} />
`

How I could use value parameter without getting error with toFixed?

**Comment by benjycui** [comment]
Make sure which one are you going to use, `Slider` or `Slider[range]`?

**Comment by ql** [comment]
@benjycui simple one, without ranges

**Comment by benjycui** [comment]
https://github.com/react-component/slider#props

`value` is a number while `Slider[range=false]`, please read the documentation.

**Comment by ql** [comment]
@benjycui actually documentation mentions only defaultValue, not value.

value	number or [number, number, ...]		Set current positions of handles. If range is `false`, the type of `defaultValue` should be `number`. Otherwise, `[number, number, ...]`

**Comment by amdolan** [comment]
@ql It seems that the example described in #150 is no longer supported (I'm not sure if it ever was), or at least is unclear from the docs in how to implement it.  You could translate the value of the slider to your own scale with a function, depending on your use case.

Logarithmic scales do not seem to be supported, an issue that I'm not sure the maintainer understands.  However, they are in [bootstrap-slider](https://github.com/seiyria/bootstrap-slider#options).
