### ISSUE TITLE
"allowCross" Has unexpected behavior

### ISSUE THREAD

**Issue by jbccollins** [react-component/slider#163]
When using the "allowCross" option with a dual thumb slider I encountered an issue when dragging the thumb with the higher value past the thumb with the lower value. Console logging in "onSliderChange" reveals that momentarily the value is correct but then somehow "onSliderChange" is called again setting both array elements to the same number. For example, given thumbs with values [4, 5], dragging the "5" thumb will result in a console log of: 
"[4, 4]" (expected)
"[3, 4]" (expected)
"[3, 3]" (unexpected) 
Relevant Code:

``` javascript
onSliderChange(value) {
   console.log(value);
   this.setState({
     value
   });
}
...
<Slider
    range
    step={1}
    min={0}
    max={24}
    allowCross
    value={this.state.value}
    onChange={this.onSliderChange}
    onAfterChange={this.onAfterChange}
    handle={<CustomHandle />}
/>
```

GIF:
- Note that I am using a custom handle for the thumbs but I tested it with the default handle and this issue still occurs.
  ![allowcross_bug](https://cloud.githubusercontent.com/assets/8915552/19695108/e34d5f38-9aaf-11e6-83bf-48a232679e24.gif)

**Comment by jbccollins** [comment]
Ok. I figured it out. This issue is with binding value to state and then changing state on the onChange handler. I was able to get it to work as expected  with 
```JavaScript
          <Slider
            range
            min={0}
            max={24}
            step={1}
            defaultValue={this.props.value}
            allowCross
            onChange={this.onSliderChange}
            onAfterChange={this.onAfterChange}
            handle={<CustomHandle />}
          />
```

**Comment by benjycui** [comment]
About `allowCross`, it seems that it works fine http://react-component.github.io/slider/examples/range.html

**Comment by benjycui** [comment]
5.2.1

**Comment by jbccollins** [comment]
Works perfectly now. Thanks for the quick fix!
