### ISSUE TITLE
Can the handler be a text input box? and I can edit text inside that box?

### ISSUE THREAD

**Issue by redguardtoo** [react-component/slider#164]
when I input percentage number inside that text box, the slider will be also be updated

**Comment by benjycui** [comment]
Try http://react-component.github.io/slider/examples/custom-handles.html

**Comment by redguardtoo** [comment]
I don't think a edit text box at the slider handle position is doable. I tried different ways and read the code of Slider.js, basically slider.js will **intercept the mouse down event** if the cursor inside the rectangle of the text input. So the text input will NEVER get the focus. I suggest leave this feature to the original plugin developer since I already submit the feature request.

**Comment by benjycui** [comment]
How about `stopPropagation?`
