### ISSUE TITLE
Add track customization

### ISSUE THREAD

**Issue by p-himik** [react-component/slider#168]
I think it would be really neat to be able to add other elements on top of the track. My main use-case is to add an additional input field on top of a range so a user can provide more information on a particular range.

**Comment by benjycui** [comment]
Just put an Input field beside Slider, see: https://ant.design/components/slider/#components-slider-demo-input-number

**Comment by p-himik** [comment]
That's not really what I meant. Imagine you have a slider with multiple ranges (their number can be changed by a user) - one input will not be enough.

**Comment by benjycui** [comment]
Could you provide more details? Picture and so on.

**Comment by p-himik** [comment]
Something like this:
![slider_labels](https://cloud.githubusercontent.com/assets/4410314/20290753/953534f4-ab14-11e6-8bda-c3dec490ff52.png)
So a particular label (I guess it would make sense to make the actual type configurable) is attached to a particular range, hence if I move some handles around add/remove ranges - the labels follow.

**Comment by benjycui** [comment]
Actually, you can wrap rc-slider, and create your own Slider without customized track.

**Comment by benjycui** [comment]
```jsx
<div>
  <Slider />
  <label />
  <label />
</div>
```
