### ISSUE TITLE
How to detect which slider has changed

### ISSUE THREAD

**Issue by nmartinezb3** [react-component/slider#170]
Hi,

I have many sliders, so I would like to receive in the callback some extra param in order to detect which slider was changed, using the same callback for every slider.

For example, if I have: 

```javascript
class Sliders extend Component {

  onValueChange(value, slider) {
   //here I only receive the value
  }
    render() {
      return (
        <div>
          Slider dots id="sliderA" step={1} defaultValue={1} max={4} onAfterChange={this.onValueChange}   />
          Slider dots id="sliderA" step={1} defaultValue={1} max={4} onAfterChange={this.onValueChange}   />
        </div>
      )
  }
}
```
In the onValueChange method, `this` corresponds to the component, so I cant get the id of the slider.
Is there any way to do this without creating a different callback for every slider?

**Comment by bmcgary** [comment]
Would something like this work??

Change `onAfterChange={this.onValueChange}` to look like this `onAfterChange={(values) => {this.onValueChange(values, "firstSlider")}}` (then on the second slider same thing but change "firstSlider" to be "secondSlider". (This is using ES6 syntax I believe.)

Normal JS would look more like this:
`onAfterChange={function(values) {this.onValueChange(values, "firstSlider")}}`

**Comment by just-boris** [comment]
Basically, you shouldn't need to know this. If you need to update appropriate state value in change callback you can do something like this

```
<Slider onAfterChange={this.onValueChange.bind(this, 'sliderA')}   />
<Slider onAfterChange={this.onValueChange.bind(this, 'sliderB')} />

// then handle
onValueChange(value, sliderId) {
}
```

Here you are call handler with one extra argument that specifies the id of slider. Also you can do the same with arrow function `onAfterChange={(value) => this.onValueChange.bind(value, 'sliderB')}`, if you would like
