### ISSUE TITLE
Tooltips not appearing

### ISSUE THREAD

**Issue by mdorn** [react-component/slider#174]
I'm using version 5.3.4 in the context of a Meteor application (that also uses React Bootstrap), and everything works great except that the tooltips don't appear.  I noticed that in the `marks.js` demo here: http://react-component.github.io/slider/examples/marks.html  tooltips don't show up in the first one either.  Any ideas what might be causing this?

**Comment by benjycui** [comment]
It's useless to show tooltip when marks can tell you everything.

**Comment by mdorn** [comment]
@benjycui fair enough, but why then do the other examples on the page show both tooltips and marks?  The slider I'm having trouble with does not use marks, FWIW.

**Comment by benjycui** [comment]
Because others Slider has `step`, so tooltip is needed to tell user the value they select.

**Comment by mdorn** [comment]
@benjycui OK I see, so if step is `null` then no tooltips will appear. That explains thy they don't appear in the demo. Unfortunately, I'm working with a simple slider that does not use steps or marks, and tooltips still are not appearing. It must have something to do with my particular environment.

**Comment by benjycui** [comment]
Try to provide a re-producible with CodePen.

**Comment by alpha-beta-soup** [comment]
+1 for using `tipFormatter` with `step: null`. I used the tip formatter to give a relative time indicator (e.g. "2 hours and 5 minutes from now") with the absolute time indicated elsewhere. `null` steps with marks means users can't select positions on the slider between marks, which is great for my use case. However it means the relative time can no longer appear ephemerally in the tooltip. I don't see why this needs to be an either-or situation, conceptually null steps seems to have no relation to whether or not the marks can have a formatted tooltip.

**Comment by TheTourer** [comment]
I too am having tooltip issues.

My slider is for selecting a start and end time within 24 hours. My config for the slider is as follows:

```
let timeSliderConfig = {
      min: 0.0,
      max: 24.0,
      step: 0.5,
      range: true,
      allowCross: false,
      defaultValue: [0.0, 24.0],
      value: [this.state.startTime, this.state.endTime],
      onChange: this.onSliderChange.bind(this),
      tipFormatter: this.formatTime
  }
```

The time is supposed to be displayed on the tooltip as "12:30 PM", "1:00 AM", etc, but no tooltip shows up despite the configured `tipFormatter`. What am I doing wrong?

**Comment by benjycui** [comment]
@alpha-beta-soup make sense, could you just create a PR? Busy recently..
