### ISSUE TITLE
Appending / removing marks

### ISSUE THREAD

**Issue by viktorbergehall** [react-component/slider#179]
I'm trying to dynamically remove a marker but the bounds array in the internal state won't update. 
Example:
```
state = {
  data = [0, 10, 20]
}

...

someEvent() {
  this.setState({data: [0, 10]});
}

...

<Slider range value={this.state.data} />
```

The desired outcome of the above example is that the initial render of rc-slider has three values, and when someEvent() is called rc-slider should get two values (0, 10). The problem is that the third value in the bounds array (in rc-slider internal state) is still present, even though the `value` property only has two values. Therefor you can't remove values. 

Has anyone have any idea of how to fix this?

Thanks in advance

**Comment by benjycui** [comment]
I read the code and think that you can update `marks` dynamically.

**Comment by benjycui** [comment]
And it will be better that if you can provide an re-producible demo with codepen
