### ISSUE TITLE
feature: vertical slider

### ISSUE THREAD

**Issue by derekyau** [react-component/slider#18]

**Comment by simaQ** [comment]
So far we have not offer this option, but we will add soon.

**Comment by derekyau** [comment]
i see... really need that option - otherwise, this is awesome!

**Comment by yiminghe** [comment]
这个得实现下

**Comment by foodaka** [comment]
has this been resolved?

**Comment by foodaka** [comment]
also need verical

**Comment by benjycui** [comment]
@foodaka busy for other project. It's welcomed to Pull Request.

**Comment by kyoyadmoon** [comment]
@foodaka   @derekyau  
 I fork this repo and modified this to a vertical one.
you can install this repo for horizontal one
also install the vertical one by add this in package.json
```
"vertical-rc-slider": "git@github.com:kyoyadmoon/slider.git#3.3.4-vertical"
```
here is the release: https://github.com/kyoyadmoon/slider/releases/tag/3.3.4-vertical
hope to help you
@foodaka  if you need, I can send a pull request. But it's not implement by add a props to make it become vertical.

**Comment by benjycui** [comment]
Property `vertical` is OK, please create a PR, if you have time. Thanks :-)

**Comment by daversm** [comment]
Not sure if im doing something wrong, but with the vertical slider, if I scroll the page down then try to move the slider, the slider handle jump all the way down. If I scroll the page all the way up, then things seem to work just fine

**Comment by benjycui** [comment]
3.6.0
