### ISSUE TITLE
setState issue prevents further scrolling

### ISSUE THREAD

**Issue by pentool** [react-component/slider#186]
Hello,

We are getting the following warning:
"Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Slider component."

For some reason this is being emitted from rc-slider. Our setup a little complicated. We use swiper in order to swipe through multiple pages (http://idangero.us/swiper/#.WFA2yXdh2Rs). On one of those pages we have rc-slider. However, we don't even get to the first page of the swiper when the console is emitting these warnings. The problem is, all scrolling comes to a halt.

We have a tableview component (custom made, similar to iOS), and you can scroll the contents of the tableview vertically. However, when you select to go to the page where the Swiper component is placed onto (and one of those swiper pages contain rc-slider) these warnings start to get emitted.

Once I start getting these warnings and then go back to the tableview, we are unable to scroll ANY of our pages no more.

We are building with Cordova 6.4.0.

I realize these may not be much to go on, but due to deadline constraints we need to yank out rc-slider from our codebase for it is causing issues.

I made a screenshot on the console. Once I try to scroll/swipe a page vertically, these warnings are getting emitted.

https://s27.postimg.org/75lnmir43/Screen_Shot_2016_12_12_at_1_34_46_PM.png

**Comment by benjycui** [comment]
Your use case is complicated, and it seems that I cannot help you.

I guess that Swiper destroy Slider without unmounting it, so Slider's `componentWillUnmount` cannot clear some event listeners.

**Comment by pentool** [comment]
According to our dev:

> he needs to add the following to index.jsx. It fixes the problem—he attached a document level listener that didn't get explicitly removed.

`componentWillUnmount() {
      this.removeEvents('touch');
      this.removeEvents('mouse');
  } `
