### ISSUE TITLE
ie8 support 

### ISSUE THREAD

**Issue by DimaJedi** [react-component/slider#188]
Documents say: support ie8,ie8+,chrome,firefox,safari.
But neither tests passed, nor my try worked. (version 5.4.0)
Do you have version working properly on ie8 or do you plan to fix it?

**Comment by benjycui** [comment]
Maybe the older version... 

Actually, we are not going to support IE8.

**Comment by DimaJedi** [comment]
could you please advice version that have chances on ie8?
