### ISSUE TITLE
Bump rc-utils version

### ISSUE THREAD

**Issue by FallingSnow** [react-component/slider#189]
Can you please bump the rc-utils version to 4.0.2, I think it will fix an error I'm getting.

**Comment by benjycui** [comment]
A RP is welcomed, thanks.

**Comment by FallingSnow** [comment]
Can I just edit the file and make a request or do I need to build the files too.

**Comment by benjycui** [comment]
You should test locally before you create a PR

**Comment by FallingSnow** [comment]
#191
