### ISSUE TITLE
support this.props.children in Handle component

### ISSUE THREAD

**Issue by sergeyglazyrindev** [react-component/slider#195]
hey guys!
That would be great to support {this.props.children} in Handle component. That would simplify a lot writing custom handlers a lot. What do you think ? I can do a pull request today... if everyone agrees.

**Comment by sergeyglazyrindev** [comment]
the use case is following:

```
class CustomSliderHandle extends Handle {
    render() {
        const value =  numeral(this.props.value || 0).format('(0.0 a)');
        return <Handle {...this.props}>
            <div className="how-much">{value}</div>
        </Handle>;
    }
}
```

**Comment by benjycui** [comment]
> That would simplify a lot writing custom handlers a lot.

Could you provide more use case?

**Comment by sergeyglazyrindev** [comment]
Ok, for example:
I am showing Slider with this code:
```
<Slider tipFormatter={null} onChange={this.onChangedSpend.bind(this)}
        handle={<CustomSliderHandle />} range allowCross={false} max={50000000} min={0} value={[this.state.spend_amount_min, this.state.spend_amount_max]}/>

```
and CustomSliderHandle is following:
```
class CustomSliderHandle extends Handle {
    render() {
        const value =  numeral(this.props.value || 0).format('(0.0 a)');
        return <Handle {...this.props}>
            <div className="how-much">{value}</div>
        </Handle>;
    }
}
```
this custom slider handle is used to show a tooltip with current min/max number.
It's more easiest to position element if it's showing inside react-slider Handle.

**Comment by benjycui** [comment]
It's simple enough after `6.0.0` https://github.com/react-component/slider/blob/master/src/Handle.jsx

It's easy to write your own Handle.

**Comment by tasiek** [comment]
As I found out, since version `6.0.0`, `handle` parameter does no longer accept object, only a function.

If someone wondered how to pass your own params to custom handle, you may (obviously?) do that like so:

```javascript
const handle = customProps => props => {
   ...
}
```
and 
```javascript
<Slider ... handle={ handle({ /* customProps */ }) } />
```
