### ISSUE TITLE
Tooltip not showing when moving to the first value

### ISSUE THREAD

**Issue by Andries-Smit** [react-component/slider#204]
When the moving the slider to the first value, the tooltip is hidden.

This is especially noticeable when there is much space between the values. 

![rs-slider_bug_no_tootlip_on_0](https://cloud.githubusercontent.com/assets/6724749/22143196/7b70c556-def9-11e6-8936-27c4580d4ec5.gif)

How to reproduce
* On page http://react-component.github.io/slider/examples/slider.html
* Sample `Basic Slider，step=20`
* Set the value to 40
* Hold your mouse button down
* Move it slowly to the left.
* The tooltip is always shown
* Halfway between 20 and 0 the tooltip disappears. (BUG)
* Tooltip show again when the move hover over the 0

**Comment by Thebigbignooby** [comment]
I don't have have any tooltip showing..... with this code 

```
<Slider tipFormatter={this.percentFormatter}
          tipTransitionName='rc-slider-tooltip-zoom-down'
          />
```

**Comment by benjycui** [comment]
`Tooltip` had been remove in `6.0.0`, and you can use `handle` to add `Tooltip` to `Handle`, see: http://react-component.github.io/slider/examples/handle.html

**Comment by isaachinman** [comment]
@benjycui Do you have an explanation for removing `Tooltip` in `6.0.0`? For what it's worth, I think it's a rather weird decision and have had to intentionally revert an automatic update back to `5.4.3` to maintain expected functionality.

**Comment by benjycui** [comment]
I want to keep `rc-slider` as small as possible, for it will be used in mobile web.

I think I can add `rc-slider/lib/handleWithTooltip` to simplify your use case.

**Comment by benjycui** [comment]
Try `6.1.0` http://react-component.github.io/slider/examples/handle.html

Or `antd` https://ant.design/components/slider/

**Comment by isaachinman** [comment]
Fair enough, could probably be achieved with a `hasTooltips` prop which requires (not imports, to save bundle size) whatever tooltip component you use. Anyways, thanks for the response - makes sense.

**Comment by benjycui** [comment]
More info:
* `antd`: powerful and convenient
* `react-component`: simple and flexible
