### ISSUE TITLE
Feature request: Allow marks to receive custom styling

### ISSUE THREAD

**Issue by cjtafoya** [react-component/slider#206]
Would be useful to be able to style or otherwise pass a CSS function to individual marks. Looks like it could be easily implemented in the styles array on the mark component.

**Comment by benjycui** [comment]
see: http://react-component.github.io/slider/examples/marks.html

```jsx
const marks = {
  '-10': '-10°C',
  0: <strong>0°C</strong>,
  26: '26°C',
  37: '37°C',
  50: '50°C',
  100: {
    style: {
      color: 'red',
    },
    label: <strong>100°C</strong>,
  },
};
```

**Comment by cjtafoya** [comment]
Yes the label can be styled, but not the circular dot... This does not address the issue

**Comment by benjycui** [comment]
So, what is your use case? Can you provide more info?

**Comment by cjtafoya** [comment]
I'm using the slider as a stepper for a series of required inputs. Users can skip ahead if they desire, but I want to be able to indicate the level of 'completeness' within the circular mark, as the custom tooltip contains separate information.

Looking at the code, it seems that custom/individual mark styling could be passed into the array which assigns the overall styling, so while I would just fork and make this integration on my own, I'm sure there are other users who would want this functionality which is why I suggested the feature for the main branch.

Separately, great component and definitely enjoy using!

**Comment by benjycui** [comment]
Just use `rc-steps`, see: http://react-component.github.io/steps/examples/progressDot.html

**Comment by ibash** [comment]
I also need this - will send a PR
