### ISSUE TITLE
Handle issue in v6.0.0.

### ISSUE THREAD

**Issue by ka7eh** [react-component/slider#208]
If you hold and drag the handle to the left and keep going outside of the "Slider" component, the handle changes direction and starts going right!
Try on any of the demo pages:
http://react-component.github.io/slider/examples/marks.html

**Comment by lavrton** [comment]
I suggested a fix here: https://github.com/react-component/slider/pull/207

**Comment by benjycui** [comment]
Sorry to make a mistake, and thank you @lavrton

**Comment by benjycui** [comment]
+ rc-slider@6.0.1
