### ISSUE TITLE
Dragging slider/range left beyond 0 (into negative) moves slider to the right

### ISSUE THREAD

**Issue by hectoroso** [react-component/slider#209]
I'm able to reproduce this in your demo: http://react-component.github.io/slider/examples/range.html

Slider with min = 0. Just keep dragging to the left beyond the left-most limit and the slider starts going to the right. The onChange function returns positive values, looks like the absolute values.

**Comment by benjycui** [comment]
Duplicated: https://github.com/react-component/slider/issues/208
