### ISSUE TITLE
Slider  does not show up in IE11. Object doesn't support property or method 'includes'.

### ISSUE THREAD

**Issue by JCaraballo113** [react-component/slider#211]
The slider shows up on Chrome but not in IE11 due to this issue.

Screenshots for reference:

http://imgur.com/a/xCxen

**Comment by benjycui** [comment]
Which version are you using? And could you provide a re-producible online demo and steps?

**Comment by JCaraballo113** [comment]
What do you mean by version? Browser Version? Because that would be Internet Explorer 11 as stated in the title. To reproduce put the component on any file, a default one works and then just boot it up in IE11.

**Comment by benjycui** [comment]
Version of `rc-slider`

**Comment by JCaraballo113** [comment]
Version 6.0.0

**Comment by benjycui** [comment]
I tested this [demo](http://react-component.github.io/slider/examples/slider.html) in IE11, and it works fine.

Actually, I cannot find any `includes` in rc-slider's code, please check your own code, thx.

**Comment by benjycui** [comment]
Close for no response.

**Comment by ifdion** [comment]
@benjycui the example doesn't work on IE 9 and IE 10. I tested both on VirtualBox VM. Are they not supported anymore? If so I think we need to update the README.md. Or is it a bug?

![screen shot 2017-12-14 at 17 56 50](https://user-images.githubusercontent.com/373018/33988946-8238f438-e0f8-11e7-8c88-5e5fbeeec35e.png)

![screen shot 2017-12-14 at 17 57 32](https://user-images.githubusercontent.com/373018/33988967-869b0e30-e0f8-11e7-8b90-bd0b7bc8c8ad.png)
