### ISSUE TITLE
Disable changing slider value with Click to use only dragging.

### ISSUE THREAD

**Issue by ihhha** [react-component/slider#212]
How is it possible in your excellent component? May be I can do it by my self if you help me with some advice.

**Comment by benjycui** [comment]
I don't understand your use case, it's weirdo, can you provide more info?

**Comment by benjycui** [comment]
Close for no response.

**Comment by kvrmd** [comment]
@ihhha You can use css `pointer-events` (http://caniuse.com/#search=pointer-events) to have this functionality.

```
.rc-slider {
    pointer-events: none;
    .rc-slider-handle {
        pointer-events: auto;
    }
}
```

**Comment by ihhha** [comment]
@kvrmd Thanks. Finally I've used CSS. But just decrease rc-slider height so it's hard to click on it to move handler )
