### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by wzup** [react-component/slider#215]
I have this error. `handles` is `undefined` for some reason:
```
function isEventFromHandle(e, handles) {
  return Object.keys(handles).some(function (key) {
    return e.target === (0, _reactDom.findDOMNode)(handles[key]);
  });
}
```

![handles - google chrome 2017-02-05 15 42 22](https://cloud.githubusercontent.com/assets/3880497/22624541/f652bc44-ebb9-11e6-8b6e-1d93dd99bad3.png)

What handles are these? Why does error happen? How to solve it?

**Comment by benjycui** [comment]
Could you provide a re-producible online demo and steps? Thanks.

**Comment by benjycui** [comment]
Close for no response.
