### ISSUE TITLE
Suggestion: Reversed Slider

### ISSUE THREAD

**Issue by sonovice** [react-component/slider#216]
It would be nice to be able to have the slider rendered "reversed". This would be useful for selecting lower boundaries:
![reverse](https://cloud.githubusercontent.com/assets/8217108/22622302/333d98fa-eb37-11e6-89ca-e8cc50938917.png)

**Comment by benjycui** [comment]
Yep, `Slider[reversed]` and `Range[reversed]` are OK.

It will be better if you can create a PR for this.

**Comment by Mike-Dax** [comment]
https://www.npmjs.com/package/rc-slider-extended exists by the way, this might be an easy transfer-and-refactor job.

**Comment by iamsoorena** [comment]
I've found the best temporary [alternative](https://github.com/sghall/react-compound-slider).

**Comment by andviane** [comment]
We also need the reversed slider. Looking forward to see the new release!

**Comment by vanyakosmos** [comment]
> I've found the best temporary [alternative](https://github.com/sghall/react-compound-slider).

more like permanent alternative

**Comment by Towhidsadeghian** [comment]
> https://www.npmjs.com/package/rc-slider-extended exists by the way, this might be an easy transfer-and-refactor job.

Cannot read property 'string' of undefined

**Comment by afc163** [comment]
https://github.com/react-component/slider/pull/472
