### ISSUE TITLE
iOS safari scroll to back

### ISSUE THREAD

**Issue by wieseljonas** [react-component/slider#217]
Does anyone have a solution to stop mobile safari from going to the previous page when rc-slider is swiped to the right?

**Comment by benjycui** [comment]
Just prevent default behavior?

I am not familiar with mobile environment, maybe someone can PR to fix this.

**Comment by paranoidjk** [comment]
@wieseljonas 
sorry, could you give us more detail info ? I visit this [demo](http://react-component.github.io/slider/examples/slider.html) with iphone 6s plus,  all works fine

**Comment by wieseljonas** [comment]
I fixed it by making the handle bigger and increasing the track's margin with the edge of the screen. It's all fine now.

Thanks.

**Comment by paranoidjk** [comment]
Ok, going to close this, if you have any further questions, please just ask, or feel free to open a issue :)
