### ISSUE TITLE
display: flex on a container throws Cannot read property 'toFixed' of undefined

### ISSUE THREAD

**Issue by aplanchamp** [react-component/slider#218]
```
     <div className="SliderButtons__content">
        <p className="SliderButtons__placeholder">{`${value} ${type}`}</p>
        <Slider
          value={value}
          min={min} max={max}
          range={false}
          allowCross={false}
          onChange={newValue => handleChange(newValue, id)}
          className="SliderButtons__input"
        />
      </div>
```

Setting display: flex on "SliderButtons__content" hides the bar of the Slider component and thus breaks the logic because the lib can not find the new value to set.

**Comment by benjycui** [comment]
Please provide a re-producible online with CodePend, and steps.

**Comment by aparij** [comment]
@aplanchamp  You need to set the width of the container (in your case SliderButtons__content) to fix the issue.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/aJooRE?editors=0011

**Comment by benjycui** [comment]
Close now, you can re-open it any time if you can provide re-producible demo

**Comment by yanivnizry** [comment]
have the same issue with latest build
re-producible demo : https://codesandbox.io/embed/nk8oym53p0
