### ISSUE TITLE
Unable to preventDefault inside passive event listener

### ISSUE THREAD

**Issue by neokreo** [react-component/slider#220]
Moving the handle I got this warning on Chrome 56

Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

**Comment by RByers** [comment]
Sorry for the trouble, this is a breaking change in Chrome 56 to [improve scroll performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention).  You probably need to add an appropriate `touch-action` [CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) to explicitly disable touch scrolling.

**Comment by benjycui** [comment]
@neokreo could you provide re-producible online demo and steps?

**Comment by paranoidjk** [comment]
This is because of Chrome 56 break change， React had been discussed
 about this https://github.com/facebook/react/issues/8968

**Comment by benjycui** [comment]
Just trace React's discussion.
