### ISSUE TITLE
Exception on Android 4.0.x

### ISSUE THREAD

**Issue by neokreo** [react-component/slider#221]
I have blank page on the browser of an Android 4.0.x phone, using the Slider component in the render. I'm sorry but I'm not able to see what kind of exception is.
I need to use the web app also on that kind of Android version.

**Comment by benjycui** [comment]
Sorry, this is an invalid issue, if you cannot provide enough information.

**Comment by neokreo** [comment]
This is the error.
Uncaught TypeError: Cannot assign to read only property '__esModule' of #<Object>

![img_2017-02-17 09 46 59](https://cloud.githubusercontent.com/assets/3073815/23058629/3da02718-f4f6-11e6-9e92-ad18245f4293.jpg)

**Comment by paranoidjk** [comment]
@neokreo http://stackoverflow.com/questions/35461830/cannot-assign-to-read-only-property-esmodule#answer-41044331 this may help you

**Comment by paranoidjk** [comment]
close for no response.
