### ISSUE TITLE
Range slider generated with `createSliderWithTooltip` shows Tooltip when disabled

### ISSUE THREAD

**Issue by SavePointSam** [react-component/slider#222]
Currently, if a range slider is made using the provided helper function and the range slider's disabled prop is true, tooltips still appear on hover. This shouldn't happen, or should be configureable.

Thanks for the great component set!

**Comment by paranoidjk** [comment]
see https://github.com/react-component/slider/pull/223/files

```js
createSliderWithTooltip(Slider | Range, autoDisable: boolean) => React.Component
```
