### ISSUE TITLE
6.1.2 Custom Handle css issues

### ISSUE THREAD

**Issue by Elliot128** [react-component/slider#230]
I'm using the custom handle for a range as in the examples. The handle is receiving the prefixCls="rc-slider-tooltip" prop as well as a unique key. When dragging a slider, all tooltips seem to 'vibrate' as I drag a handle because of these minor css changes.

Tooltip on drag jumps back and forth between these two styles.
`left: 391.5px; top: 974px;`
`left: 392px; top: 974px;`

![tooltipissue](https://cloud.githubusercontent.com/assets/14080426/23445199/5ec23500-fdff-11e6-8327-770e7195df13.gif)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/aJooRE?editors=0011

**Comment by Elliot128** [comment]
http://codepen.io/anon/pen/zZvbKG?editors=0011

Have some code written but getting an error when I try to use a custom handle

**Comment by benjycui** [comment]
@Elliot128 your demo doesn't work.

**Comment by Elliot128** [comment]
I cannot reproduce currently and the problem has gone away. Will re-open if I am able to reproduce.

**Comment by hellofantastic** [comment]
@Elliot128  how did you get handle dots and tooltips to be default visible ?
