### ISSUE TITLE
6.1.2 Custom tooltips out of place if rendered to part of page off screen

### ISSUE THREAD

**Issue by Elliot128** [react-component/slider#231]
If rendering the page with the tooltips out of view and  always displayed, they will render to the bottom of the window, not on top of the handles.

**Comment by benjycui** [comment]
It's a problem in `dom-align`.

**Comment by benjycui** [comment]
Trace: https://github.com/yiminghe/dom-align/pull/11

**Comment by Elliot128** [comment]
Any word on when this fix may be released?

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i`

**Comment by Elliot128** [comment]
I ran that command but I still have the same issue when the sliders are rendered off the screen.

![5ec23500-fdff-11e6-8327-770e7195df13](https://cloud.githubusercontent.com/assets/14080426/24466819/d8e33468-1477-11e7-8fa5-820e1ba9aaa8.gif)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/aJooRE?editors=0011

**Comment by Elliot128** [comment]
I am unable to reproduce in that site because I cannot find a dist for rc-tooltip. For rc-slider you use 'https://unpkg.com/rc-slider/dist/rc-slider.js', but for the tooltip there is no /dist/ folder.

**Comment by Elliot128** [comment]
http://codepen.io/anon/pen/peYbJE?editors=0011

Make sure that the slider is rendered outside of the initially viewable area. The tooltip will be rendered to the bottom of the view, while the slider is out of view.

**Comment by benjycui** [comment]
@yiminghe forgot to publish a new version after merging my patcth...

**Comment by benjycui** [comment]
rm -rf node_modules && npm i

**Comment by Elliot128** [comment]
Ran that command and the problem is still there.

**Comment by benjycui** [comment]
dom-align@1.5.4 is published and unpublished..

You can watch dom-aligin's release, and try if it's published.
