### ISSUE TITLE
Get Value of Range Handles in onChange Function

### ISSUE THREAD

**Issue by epalaima** [react-component/slider#234]
Hi, I'm trying to get the values of the handles of a Range and use them to update other parts of my page when the knobs are changed. However I can't seem to find anything about how to access the handle values in the repo or the examples. I was trying (basic example):

```
class MyClass extends React.Component {
...
changeHandler(event){
      const input = event.target.value;
      ...etc....
}
...
render(){
      const initialValues = [10, 50];
      return <Range defaultValue={initialValues} onChange={this.changeHandler.bind(this)}/>;
}
}
```

**Comment by paranoidjk** [comment]
https://github.com/react-component/slider/blob/master/examples/range.js#L30

**Comment by paranoidjk** [comment]
please read the api document and demo code first
