### ISSUE TITLE
How to use handle with es6?

### ISSUE THREAD

**Issue by eldyvoon** [react-component/slider#238]
```
{this.state.showHandler && <Range step={20}
	defaultValue={[this.state.selectedRange[0], this.state.selectedRange[1]]} 
	onAfterChange={this.log.bind(this)}
	handle={this.handleRange.bind(this)}
	/>}
```

Above code did not trigger the slider, but I'm able to get value by doing 

```
handle(props){
console.log(props);
}
```

It's ok when I remove this line 

`handle={this.handleRange.bind(this)}`

**Comment by paranoidjk** [comment]
https://github.com/react-component/slider/blob/master/examples/handle.js#L14
