### ISSUE TITLE
Can't be used with css-modules

### ISSUE THREAD

**Issue by OlivierCo** [react-component/slider#239]
Your component looks really nice, but unfortunately it's unusable with a webpack and css-modules config.

You should split and import yout css files directly per component. It would be transparent for everybody.

**Comment by paranoidjk** [comment]
no time for this，if you want to use css-module in your project，just exclud rc-slider

**Comment by just-boris** [comment]
For the reference, the same request with longer discussion https://github.com/react-component/slider/issues/154

**Comment by paranoidjk** [comment]
I mean in your css-loader config:

```js
      {
        test: /\.css$/,
        loader: "style-loader!css-loader?modules"
        exclude: [require.resolve('rc-slider')]
      },
 
```

**Comment by timhecker** [comment]
With the new webpack config, it is:
```javascript
      {
        test: /\.css$/,
        include: /node_modules\/rc-slider/,
        use: ['style-loader', 'css-loader']
      },
```

**Comment by clintonmedbery** [comment]
Ugh none of this did it for me. Here is my solution:
**styles.scss**
`:global {
    @import '~rc-slider/assets/index';
}`
**import**
`import './styles.scss';`

**Comment by Yrsafam** [comment]
My resolve:

```
// Component.tsx

import React from "react";
import Slider from "rc-slider";
import "rc-slider/assets/index.css";

import styles from "path/to/styles.module.scss";

<Slider
        className={styles.filter__slider}
        min={0}
        max={20}
        defaultValue={0}
/>
```

```
// styles.module.scss

.filter {
  &__slider {
    :global(.rc-slider-rail) {
      background-color: red;
    }
  }
}
```
