### ISSUE TITLE
Marks are considered step values

### ISSUE THREAD

**Issue by marin101** [react-component/slider#240]
I'd like to report a bug regarding the use of marks.

I'm using marks as in the pictures bellow. I created the slider component like this:
`marks={
    0: 0%,
    10: 10%,
    20: 20%,
    30: 30%,
   ...
}`
`<Slider min={0} max={100} step={3} marks={marks}/>`

With the step value being `step=3` I shouldn't be allowed to place the slider on a position that is not a multiple of 3. However, as you can see in the images bellow, I am able to select the position 10 probably because 10 is one of the defined marks.

These are the pictures of the 3 consecutive steps:
![screenshot from 2017-03-18 13 14 17](https://cloud.githubusercontent.com/assets/22985405/24071915/39b1cf82-0bdd-11e7-874d-8e197b519bff.png)
![screenshot from 2017-03-18 13 14 31](https://cloud.githubusercontent.com/assets/22985405/24071918/3c3e3ba0-0bdd-11e7-9bae-e11f0294a99e.png)
![screenshot from 2017-03-18 13 14 34](https://cloud.githubusercontent.com/assets/22985405/24071919/3e3cfd4c-0bdd-11e7-9c5a-cd5d6d2eab6a.png)

**Comment by benjycui** [comment]
Actually, it an expected behavior.

If you don't want your users to select value on marks, why do you show these marks?

**Comment by marin101** [comment]
@benjycui Well, I consider marks to be just orientation points. With marks on the slider I can immediately see approximate value of the slider but I do not want it to be one of the slider positions.

As far as I could see the `Range` is behaving in the way I described which means that marks are not necessarily slider positions.

Please, reconsider opening this issue.

**Comment by benjycui** [comment]
Actually, you can wrap rc-slider now, when some click marks, you just re-set the value to the closest step.

**Comment by benjycui** [comment]
Because I don't think your use case is common.

**Comment by marin101** [comment]
Oh yeah, I can make a workaround like that, thanks.
