### ISSUE TITLE
Slider going over max value

### ISSUE THREAD

**Issue by marin101** [react-component/slider#241]
`<Slider min={0} max={100} step={21.1} marks={marks}>`

When I use `Slider` like this I'm allowed to take `Slider` handle over `max` value.

Example images:
![screenshot from 2017-03-18 17 26 15](https://cloud.githubusercontent.com/assets/22985405/24073935/19f5d2c4-0c00-11e7-8975-efea43702f8d.png)
![screenshot from 2017-03-18 17 25 43](https://cloud.githubusercontent.com/assets/22985405/24073934/184d681a-0c00-11e7-97b3-24165ef33ac8.png)

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/24092789/77ce51be-0d8b-11e7-9ffb-bd47ac28bf25.png)

**Comment by marin101** [comment]
@benjycui Yeah, but why is this feature not possible? There can be a valid use case where I would like the step to be the value which does not evenly divide `max-min`.

Maybe you can make this a feature request?

**Comment by benjycui** [comment]
It's hard to tell the right behavior when step is not divisible.

Could you show your option? As detailed as possible.

**Comment by marin101** [comment]
What I would like is that the slider doesn't go beyond the max value, otherwise it is fine.

I made a workaround by not allowing the value of the slider to becoming larger than the max value in the onChange callback.

**Comment by benjycui** [comment]
> I made a workaround by not allowing the value of the slider to becoming larger than the max value in the onChange callback.

So, just wrap your solution as a customized component.

> What I would like is that the slider doesn't go beyond the max value, otherwise it is fine.

What I need is a common solution for most project. So, you also think it's hard to tell which behavior is common. So, this should not be integrated into rc-slider.
