### ISSUE TITLE
breakpoints for step size

### ISSUE THREAD

**Issue by rohit-ravikoti** [react-component/slider#242]
Hi!
Awesome component! I was wondering if there was any way to set breakpoints for step size. For example:
min: 1k, max: 10M
I would like to set breakpoints where:
step size for 1k - 100k is 1k
step size for 100k - 1M is 10k
step size for >1M is 100k

Thanks!

**Comment by benjycui** [comment]
Just use a transformer function:

```jsx
function transform(valueFromSlider) {
  // ..
  return valueToYourApp 
}
```

**Comment by iamsoorena** [comment]
@benjycui sorry but I didn't understand how should I use this transform function, could you explain a little?
