### ISSUE TITLE
Clicking on a mark selects different values on a slider

### ISSUE THREAD

**Issue by marin101** [react-component/slider#245]
When I click on the range slider mark which spans multiple dots different dots are selected on the range slider. As is shown in the images bellow, when I click on the 2015 I get a different result opposed to when I click 31.

![screenshot from 2017-03-30 14 34 35](https://cloud.githubusercontent.com/assets/22985405/24504398/71291d08-1556-11e7-8d92-018ae65c4fe2.png)

![screenshot from 2017-03-30 14 34 41](https://cloud.githubusercontent.com/assets/22985405/24504401/73a679b8-1556-11e7-8e04-8d8abc1dc20b.png)

**Comment by marin101** [comment]
I think the marks object is not clickable at all, but the empty space bellow slider is clickable which result in this behaviour

**Comment by benjycui** [comment]
Yep, it is an known issue.

**Comment by paranoidjk** [comment]
@marin101 can you provide a codepen demo?

**Comment by RavenXce** [comment]
It seems like the whole marks area can be used for sliding, rather than the marks being used as anchors for clicking. This doesn't seem intuitive..

**Comment by yesmeck** [comment]
Should be fixed in #376
