### ISSUE TITLE
Mark not corresponding to its dot position

### ISSUE THREAD

**Issue by marin101** [react-component/slider#246]
When there is only 1 mark on the range slider, the mark is not aligned with dot.

![screenshot from 2017-03-30 14 57 30](https://cloud.githubusercontent.com/assets/22985405/24505212/614ae2a6-1559-11e7-9b24-4be3faaf3749.png)

**Comment by paranoidjk** [comment]
Should been fixed at https://github.com/react-component/slider/commit/cba733e19da50379e01f522484bb78f6e63b3f55.

Please upgrade to latest version.
