### ISSUE TITLE
Add support for BEM

### ISSUE THREAD

**Issue by eddyerburgh** [react-component/slider#248]
I want to use this at work but the design team are hesitant as it does not use BEM.

I'd like to add an optional prop, called `bem`, that makes class names follow the BEM convention

I'm happy to make a PR for this

**Comment by benjycui** [comment]
Actually.. I don't think `className`s in rc-slider will affect your own code, for all the `className`s will have a prefix 'rc-slider'.

**Comment by eddyerburgh** [comment]
I agree, but my design team don't want to use anything that doesn't follow BEM, even though specificity won't be a problem.

**Comment by benjycui** [comment]
Sorry, it seems that we cannot help you. We had better keep current class name, even though it is not perfect. Because we must keep compatibility.

**Comment by antipin** [comment]
>  for all the classNames will have a prefix 'rc-slider'

That's cool, but unfortunately still not completely safe and isolated.

Also it doesn't play well with css-modules: classnames can be postfixed with hashes etc..

But it could be solved by extending rc-slider's interface in a way that allows to add custom classnames to every element of the slider (the same like it is done now for `styles`).
And it doesn't break backwards compatibility.

I could do implement it and open a PR, if you think it's a good idea?
