### ISSUE TITLE
Detect which handle is being dragged in onBeforeChange

### ISSUE THREAD

**Issue by gragland** [react-component/slider#250]
It would be great if `onBeforeChange` let you know which handle was being dragged. You can figure this out in `onChange` and `onAfterChange` by looking at which handle position value changed, but as far as I can tell there's no way to know in `onBeforeChange`.

I'd be happy to figure out a solution and do a pull request for this if this is something that you'd want to merge.

**Comment by paranoidjk** [comment]
can you explain why you need to kown which handle was being dragged ? 

We won't consider a feature which is unnecessary, so please give us your use case 😄

**Comment by gragland** [comment]
@paranoidjk I enable the user to hold the mouse down on a handle for 1 second to zoom-in on the range for more precise positioning (range max value is large). I need to know which handle is being clicked so that I can fetch its offset and do some calculations that ensure that the handle stays in the same position relative to the screen when zooming. And there are a couple other situations where I want to do things differently depending on which handle is clicked. For example when the middle handle is changed it alters the current time in an embedded video.

![](https://media.giphy.com/media/3ohzdKS0rtF77QwGvS/giphy.gif)

**Comment by paranoidjk** [comment]
i see，PR is welcome

**Comment by benjycui** [comment]
I am not sure if you should pass a number or a DOM node to `onBeforeChange`. Which will be better and more useful?

**Comment by gragland** [comment]
@benjycui I'm passing index (number) currently and then have a HOC around Handle that allows me to access the node if I need to: `<Handle ref={(handle) => { this.handleRefs[index] = handle; }} />`. This works well for me as I just need the index number sometimes and other times I need to access the node to read its props.offset. If we just passed the node there would be no way to know the index unless we passed multiple args to `onBeforeChange`right? I'm open to either solution though.

**Comment by benjycui** [comment]
Sorry, it seems that index is unstable in your use case. Because you can drag a handle across other handle, if you set `allowCross=true`.

e.g. You drag handle 1 across handle 2, then you are dragging handle 2 actually.

Actually, both of index and DOM node are unstable, unless we refactor the implementation of rc-slider.

**Comment by benjycui** [comment]
And I think this is not a common use case, just write your own [`createSliderWithTooltip`](https://github.com/react-component/slider/blob/master/src/createSliderWithTooltip.jsx) or something like that. And you can get `index` from that HOC.

**Comment by gragland** [comment]
@benjycui Ah yes I suppose I can keep track of the currently active handle using <Handle> onMouseEnter and onMouseLeave events (since no way to override `onBeforeChange` with an HOC as far as I can tell). I agree that index with `allowCross=true` is a bit misleading (even though it isn't an issue for me) and can see why you wouldn't want to merge this. Thanks for considering!
