### ISSUE TITLE
Google Chrome: preventDefault inside passive event listener

### ISSUE THREAD

**Issue by delorge** [react-component/slider#258]
Using this component in latest Chrome (mobile device emulation) causes following warning:
```
Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
```

One of possible solutions is using appropriate [CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action), which I believe should be either `none` or `pan-x` / `pan-y` depending on orientation;

Please consider these options and I'll send a PR

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/aJooRE?editors=0011

**Comment by benjycui** [comment]
I am not familiar with mobile browsers, cc @paranoidjk

**Comment by paranoidjk** [comment]
@delorge maybe because of chrome 56 break change ? https://github.com/facebook/react/issues/8968

**Comment by delorge** [comment]
@benjycui it can be reproduced in latest Chrome (switch to device toolbar in devtools). Just try to drag handlers, no special setup required.

@paranoidjk exactly :) I wasn't aware of this issue at React repo.

Although the slider keeps working as expected, these warnings are quite noisy and annoying. (I fixed this in my project by adding `touch action` prop, as I mentioned above).

**Comment by paranoidjk** [comment]
@delorge we don't have time to deal with this problem, since the react team do not have a conclusion yet.

but still you can PR to help us fix it~

**Comment by delorge** [comment]
@paranoidjk okay, I'll dig into this

**Comment by paranoidjk** [comment]
ping @delorge do you have time to help us fix this problem?

**Comment by paranoidjk** [comment]
I will handle this.
