### ISSUE TITLE
non linear range

### ISSUE THREAD

**Issue by jboissard** [react-component/slider#259]
For some applications, it might be useful to have a non linear scale. e.g. most values are between 0 and 100 but some are close to thousands.

so instead of defining step with an integer, be able to have a function

**Comment by paranoidjk** [comment]
you may use range http://react-component.github.io/slider/examples/range.html

**Comment by ksavenkov** [comment]
would be cool to have at least "linear" and "logarithmic" options

**Comment by paranoidjk** [comment]
I think it's unnecessary, you can do a transform between the slider position value and the presentation value

**Comment by dmkelly** [comment]
@paranoidjk I just came across this issue and have a similar question. Is there a way to pass a transform function into the slider? I believe this solution would break down with the tooltip value display if the transform isn't applied by the slider (my design calls for tooltips).

**Comment by qoalu** [comment]
Solved it by wrapping the component inside another one and mapping slider values to my own values. The tricky part which I have not solved is setting a defaultValue and transforming from my own values to a slider value

**Comment by cinderblock** [comment]
Example of how to do this: https://github.com/react-component/slider/issues/393#issuecomment-452310092
