### ISSUE TITLE
Module not found: Error: Can't resolve 'rc-util/es/Dom/addEventListener' in '/home/wolfgang.schuster/projects/cirrus/root/internal2/node_modules/rc-slider/es/common'

### ISSUE THREAD

**Issue by wolfadex** [react-component/slider#266]
The NPM version is listed as 7.0.6 and has the error `Module not found: Error: Can't resolve 'rc-util/es/Dom/addEventListener' in '/home/wolfgang.schuster/projects/cirrus/root/internal2/node_modules/rc-slider/es/common'` caused by line 11 in `/es/common/createSlider.js`. The line in version 7.0.6 is `import addEventListener from 'rc-util/es/Dom/addEventListener';` when it should be `import addEventListener from 'rc-util/lib/Dom/addEventListener';`, which it is in version 7.0.5.

**Comment by yesmeck** [comment]
@wolfadex Try reinstall node_modules.

**Comment by wolfadex** [comment]
I'm using yarn for my project and rc-util 4.0.2 is getting installed which doesn't have the `/es` directory. I'm also using rc-menu and rc-tooltip in my project which seem to be the likely reason that rc-util 4.0.2 is being installed. They both use the `/lib` directory in rc-util instead of `/es`.

**Comment by yesmeck** [comment]
@wolfadex Try upgrade  rc-util to 4.0.4
