### ISSUE TITLE
es target exports only default

### ISSUE THREAD

**Issue by maxired** [react-component/slider#267]
Hey,

I am using the new es target.
I wish I could import doing `import { Range } from 'rc-slider'`, but this is not working, because the es/index files exports only in default.

This was for me working before using the es target.

**Comment by paranoidjk** [comment]
shall we support this ? cc @yiminghe @benjycui 

we need to change [index.js](https://github.com/react-component/slider/blob/master/src/index.js) to

```js
import Slider from './Slider';
import Range from './Range';
import Handle from './Handle';
import createSliderWithTooltip from './createSliderWithTooltip';

Slider.Range = Range;
Slider.Handle = Handle;
Slider.createSliderWithTooltip = createSliderWithTooltip;

export { ...Slider };
export default Slider;
```

**Comment by tinder-rhsiao** [comment]
the readme still pointing to use 
```js
import Slider, { Range } from 'rc-slider';
```
https://github.com/react-component/slider

which breaks after the release

**Comment by paranoidjk** [comment]
cc @react-component/admin so, all rc-components need to do this change later.
