### ISSUE TITLE
react v15 Prop type deprecation warning

### ISSUE THREAD

**Issue by kolodkin** [react-component/slider#269]
Warning: Align: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by paranoidjk** [comment]
`rm -rf node_modules && npm i`

**Comment by kolodkin** [comment]
Your solution didn't work for me.
I am using 
    "rc-slider": "^7.0.8",
    "react": "^15.5.4",

**Comment by paranoidjk** [comment]
can you give me the complete error stack, i can not guess where the warning come from, rc-slider should be no warning since https://github.com/react-component/slider/pull/253

**Comment by kolodkin** [comment]
sure

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
printWarning @ warning.js:36
warning @ warning.js:60
get @ React.js:95
(anonymous) @ Align.js:53 (rc-align/lib/Align.js:52)
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ index.js:7 (rc-align/lib/index.js:7)
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ Popup.js:19 (rc-trigger/lib/Popup.js:19)
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ Trigger.js:27 (rc-trigger/lib/Trigger.js:27)
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ index.js:3 (rc-trigger/lib/index.js:3)
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ Tooltip.js:15 (rc-Tooltip/lib/Tooltip.js:15)
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ index.js:3 (rc-tooltip/lib/index.js:3)
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ createSliderWithTooltip.js:45
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ index.js:20 (rc-slider/lib/index.js:20)
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ ImageTemplateEditor.js:23
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ ImageEditActionIcon.js:17
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ ActionIcons.js:17
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ FeedsMenu.js:24
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ FeedsMenuContainer.js:7
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ Home.js:11
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ HomeContainer.js:7
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ main.js:46
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ index.js:15
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ bootstrap 572d2b6…:578
__webpack_require__ @ bootstrap 572d2b6…:555
(anonymous) @ bootstrap 572d2b6…:578
(anonymous) @ bootstrap 572d2b6…:578
warning.js:36 Warning: Align: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
printWarning @ warning.js:36
warning @ warning.js:60
createClass @ ReactClass.js:628
(anonymous) @ Align.js:49
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ index.js:7
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ Popup.js:19
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ Trigger.js:27
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ index.js:3
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ Tooltip.js:15
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ index.js:3
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ createSliderWithTooltip.js:45
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ index.js:20
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ ImageTemplateEditor.js:23
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ ImageEditActionIcon.js:17
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ ActionIcons.js:17
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ FeedsMenu.js:24
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ FeedsMenuContainer.js:7
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ Home.js:11
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ HomeContainer.js:7
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ main.js:46
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ index.js:15
__webpack_require__ @ bootstrap 572d2b6…:555
fn @ bootstrap 572d2b6…:86
(anonymous) @ bootstrap 572d2b6…:578
__webpack_require__ @ bootstrap 572d2b6…:555
(anonymous) @ bootstrap 572d2b6…:578
(anonymous) @ bootstrap 572d2b6…:578

**Comment by paranoidjk** [comment]
I checked at the dependence tree, all them should fixed the react 15.5 warning.

`rc-slider -> rc-tooltip -> rc-trigger -> rc-align`

can you give me your git repo url ?

**Comment by kolodkin** [comment]
issue solved by doing the following:
yarn remove rc-slider
yarn add rc-slider

i think the reasone is the one of the dependencies was updates. see attached image of yarn.lock file diff.  (rc-trigger version changed from 3.4.2 to 3.4.3 and prop-type added as dependency. 
![screen shot 2017-05-16 at 15 08 51](https://cloud.githubusercontent.com/assets/2054182/26105210/c5200454-3a49-11e7-8349-4721f6b532da.png)

**Comment by paranoidjk** [comment]
Of couse, when i say `rm -rf node_modules && npm i`,  i mean you need to upgrade your dependencies. 

By the way, If you say more clearly that you use yarn at the begining,  then we do not need to waste time at here.

**Comment by benjycui** [comment]
I don't link `yarn.lock`...
