### ISSUE TITLE
Uncaught TypeError: Can't add property context, object is not extensible

### ISSUE THREAD

**Issue by karenpeng** [react-component/slider#27]
Hi, I have just a basic setup

```
var React = require('react')
var Rcslider = require('rc-slider')

React.render(<Rcslider/>, document.getElementById('chart'))
```

And gets back error ```Uncaught TypeError: Can't add property context, object``` in ReactCompositeComponent.js:153
which is ```inst.context = publicContext```

Any idea?

**Comment by benjycui** [comment]
Version?

**Comment by benjycui** [comment]
Version? React and rc-slider

**Comment by benjycui** [comment]
Version? React and rc-slider

**Comment by yiminghe** [comment]
use react 0.14
