### ISSUE TITLE
Can't import css

### ISSUE THREAD

**Issue by mgrzeszczak** [react-component/slider#270]
As in the title I can't import css file.

My rules:

```
module : {
    rules : [
      {
        use: 'babel-loader',
        test: /\.js$/,
        exclude: /node_modules/
      },
      {
        use: ['style-loader','css-loader'],
        test: /\.css$/
      }
    ]
  }
```

Error:

Module not found: Error: Can't resolve 'rc-slider/assets/index.css' in ...

**Comment by paranoidjk** [comment]
Sorry, we use issue to track bug，please read webpack2 doc for your problem's answer.
