### ISSUE TITLE
CSS not included in dist package

### ISSUE THREAD

**Issue by roderickhsiao** [react-component/slider#271]
The latest version no longer include assets folder in the package

tested at version 7.0.8

it moves to `/dist` folder now, not sure this is expected as the documentation still points us to the assets folder.

**Comment by roderickhsiao** [comment]
its under /dist now

**Comment by roderickhsiao** [comment]
not sure its exp

**Comment by roderickhsiao** [comment]
not sure this is expected as the documentation still points us to the assets folder.

**Comment by benjycui** [comment]
https://unpkg.com/rc-slider@7.0.8/dist/

**Comment by paranoidjk** [comment]
https://unpkg.com/rc-slider@7.0.8/assets/

**Comment by nadeemja** [comment]
Having the same problem. Not sure how the links above help. Am I supposed to download the file and put it somewhere in my codebase? (v8.3.0)

**Comment by paranoidjk** [comment]
@nadeemja Sorry for the trouble. I have fixed it just now，please try `rc-slider@8.3.1`.

**Comment by nadeemja** [comment]
Hi @paranoidjk !

Thanks for the quick response. Very impressive. 

Unfortunately it didn't work. 

I ran `yarn remove rc-slider` and then `yarn add add rc-slider`.

**Comment by paranoidjk** [comment]
@nadeemja see https://unpkg.com/rc-slider@8.3.1/dist/

**Comment by nadeemja** [comment]
@paranoidjk 

I don't understand what you want me to do. 

Do I need to handle the css file separately?

**Comment by paranoidjk** [comment]
@nadeemja What's your problem? 

My answer is for this issue, see the issue title: **CSS not included in dist package #271**, and i fixed it.

**Comment by nadeemja** [comment]
Yes. My problem is that the css is not included when installing the package. There is not assets folder, not even in 8.3.1

**Comment by paranoidjk** [comment]
@nadeemja If you require from  npm, you sould load style manually, see https://github.com/react-component/slider/blob/master/examples/slider.js#L2

**Comment by nadeemja** [comment]
Yes, I understand - but the file does not exist. 

Do you mean to say that we must manually __download__ the file?

**Comment by paranoidjk** [comment]
@nadeemja I checked it, right now i only published css to npm, so you can do:

`import 'rc-slider/assets/index.css';`

do you need less? Please let me know if it is necessary.

**Comment by paranoidjk** [comment]
@nadeemja I think users no need to import less, just use css, since you have to compile less to css eventually.

**Comment by paranoidjk** [comment]
@nadeemja see usage doc in readme: https://github.com/react-component/slider#usage 😄

**Comment by nadeemja** [comment]
@paranoidjk 

Okay. Let me explain. 

1. I ran `yarn add rc-slider`.

2. I open node_modules/rc-slider.

3. There is no assets folder in node_modules/rc-slider.

4. Therefore, `import 'rc-slider/assets/index.css';` gives error `unable to resolve module`.

I do not need Less. I'm just saying that __the .css file is missing__. :)

**Comment by paranoidjk** [comment]
@nadeemja What's your version of rc-slider? 

You could see from https://unpkg.com/rc-slider@8.3.1/ , There do have assets folder.

PS. what is unpkg? see https://unpkg.com/#/

**Comment by nadeemja** [comment]
I'm using 8.3.1. 

Perhaps it's a problem with Yarn.

Have you tested with Yarn? 
https://github.com/yarnpkg/yarn

**Comment by paranoidjk** [comment]
@nadeemja Yarn won't change the package files.

**Comment by nadeemja** [comment]
I know. But then why is the assets folder not installed into node_modules/rc-slider?
