### ISSUE TITLE
Webpack ES6 Css import not working. 

### ISSUE THREAD

**Issue by nikohosn** [react-component/slider#273]
webpack config

`'use strict';

const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

function isExternal(module) {
    var userRequest = module.userRequest;

    if (typeof userRequest !== 'string') {
        return false;
    }

    return userRequest.indexOf('bower_components') >= 0 ||
        userRequest.indexOf('node_modules') >= 0 ||
        userRequest.indexOf('lib') >= 0;
}

module.exports = {
    entry: path.resolve(__dirname, 'public/app/app.js'),
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'public/web/js')
    },
    resolve: {
        modules: ['node_modules', './public/lib'],
        extensions: ['.js', '.jsx', '.css', '.json']
    },
    module: {
        loaders: [{
            test: /\.js(x)?$/,
            exclude: /node_modules/,
            loaders: 'babel-loader',
            query: {
              presets: [ 'stage-2' ]
            }
        }, {
            test: /\.scss$/,
            loader: ExtractTextPlugin.extract('css-loader')
        }, {
            test: /\.css$/,
            loader: 'css-loader'
        }, {
            test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: "url-loader?limit=10000&mimetype=application/font-woff"
        }, {
            test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: "file-loader"
        }, {
            test: /\.svg(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: 'url-loader?limit=10000&mimetype=image/svg+xml&name=/images/[name].[ext]'
        }, {
            test: /\.(jpe?g|png|gif|ico|svg)$/i,
            loader: 'file-loader?name=/images/[name].[ext]'
        }, {
            test: /\.json$/,
            loader: 'json-loader'
        }]
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendors',
            minChunks: function (module) {
                return isExternal(module);
            },
            filename: 'vendors.js',
            path: path.resolve(__dirname, 'public/web/js')
        })
    ],
    watchOptions: {
        poll: true
    }
};
`

example usage of component 
`import React from 'react';
import {ModalContainer, ModalDialog} from 'react-modal-dialog';
import { connect } from 'react-redux'
import wordcount from 'wordcount';
import NoteList from './NoteList';
import Session from '../../middleware/Session';
import * as actions from './actions';
import { Scrollbars } from 'react-custom-scrollbars';
import ReactQuill from 'react-quill';
import 'rc-slider/assets/index.css';
import 'rc-tooltip/assets/bootstrap.css';
import Tooltip from 'rc-tooltip';
import Slider from 'rc-slider';

const createSliderWithTooltip = Slider.createSliderWithTooltip;
const Range = createSliderWithTooltip(Slider.Range);
const Handle = Slider.Handle;

const handle = (props) => {
  const { value, dragging, index, ...restProps } = props;
  return (
    <Tooltip
      prefixCls="rc-slider-tooltip"
      overlay={value}
      visible={dragging}
      placement="top"
      key={index}
    >
      <Handle {...restProps} />
    </Tooltip>
  );
};

const wrapperStyle = { width: 100, margin: 50 };

class NoteEditor extends React.Component {

  constructor(props) {
    super(props);

    this.state = {
      user: Session.getSession('prg_lg'),
      wordcount:0
    }

    this.modules = {
      toolbar: [
        [{ 'header': [1, 2, false] }],
        ['bold', 'italic', 'underline','strike', 'blockquote'],
        [{'list': 'ordered'}, {'list': 'bullet'}, {'indent': '-1'}, {'indent': '+1'}],
        ['link', 'image'],
        ['clean']
      ],
    };

        // [{ 'color': [] }, { 'background': [] }],

    this.formats = [
      'header',
      'bold', 'italic', 'underline', 'strike', 'blockquote',
      'list', 'bullet', 'indent',
      'link', 'image'
    ];

  }

  handleChange(e) {
    this.setState({[e.target.name]: e.target.value});
  }

  handleTextChange(val) {
    // this.props.noteText(val);
    this.setState({text: val});
    this.wordCountUpdate(val);
    console.log("Text change: " + val);
  }

  getNoteEditor() {
    return (
      <ReactQuill theme='snow' value={this.state.text} modules={this.modules} formats={this.formats} onChange={this.handleTextChange.bind(this)} />
    );
   //
  }

  wordCountUpdate(val) {
    let nodeText = $(val).contents().filter(function(){
      return this.nodeType === 3 && $.trim(this.nodeValue) !== '';
    }).text()
    this.setState({ wordcount: wordcount(nodeText) })
  }

  render() {
    let note = this.props.note;
    let noteCreator = note.creator.first_name + ' ' + note.creator.last_name
    let noteImg = '/images/default-profile-pic.png';

    return(
      <div>
        <ModalContainer zIndex={9999} >
          <ModalDialog width="642px" className="note-popup-dialog" style={{transform : "none"}} >
            <div className="popup-holder">
              <section className="edit-note-popup clearfix">
                <section className="inner-header clearfix">
                  <div className="info-wrapper">
                    <img className="user-image img-circle" src={noteImg} alt="User"/>
                      <p className="note-owner">by {noteCreator}</p>
                      <p className="time-wrapper">{note.created_at}</p>
                  </div>
                  <div className="options-wrapper">
                    <span className="delete-note"></span>
                    <span className="note-info"></span>
                    <div className="search-wrapper">
                      <input type="text" className="form-control search-note" placeholder="search"/>
                      <span className="search-ico"></span>
                    </div>
                    <span className="maximize"></span>
                  </div>
                </section>
                <section className="note-body clearfix">
                  <div className="title-wrapper">
                    <input defaultValue={note.title} type="text" className="note-title" value={this.state.noteTitle} onChange={ this.handleChange.bind(this) } />
                  </div>
                  <div className="rich-editor-holder">
                    { this.getNoteEditor() }
                  </div>
                </section>
              </section>
              <span className="close-note" onClick={this.props.dismissModal}></span>
              <div className="note-words-count">
                <span className="count">{this.state.wordcount}</span> <span className="def">words</span></div>
              <div>
                <Slider min={0} max={20} defaultValue={3} handle={this.handle} />
              </div>
            </div>
          </ModalDialog>
        </ModalContainer>
      </div>
    );
  }
}

export default connect(null, actions)(NoteEditor);`

**Comment by benjycui** [comment]
Please learn [how to write readable Markdown](https://guides.github.com/features/mastering-markdown/), and it's a good habit to preview your comment before submitting.

**Comment by benjycui** [comment]
And I think it's a usage question of webpack.

**Comment by banterstudios** [comment]
You need to also add in the style-loader

Do this:

`{
    test: /\.css$/,
     loader: 'style!css'
      },`
