### ISSUE TITLE
rc-tooltip in a react bootstrap Modal

### ISSUE THREAD

**Issue by ContiGabriel** [react-component/slider#276]
Hi, 
I got a issue when using the rc-tooltip in a react bootstrap Modal whereby the tooltip is behind the modal and therefore not visible.
Any idea on how to fix that?

**Comment by paranoidjk** [comment]
Can you give a reproducible demo?

It looks like z-index problem.

**Comment by ContiGabriel** [comment]
Hi paranoidjk,
You are right it is a z-index issue but I cannot found a wait to change it.
I will give you a demo tomorrow.

**Comment by zeakd** [comment]
I have same problem. How about make `createSliderWithTooltip` with options? like 

```
const TooltipSlider = createSliderWithTooltip({
  // same as rc-tooltip props
  overlayClassName: "something"
})(Slider)
```

**Comment by paranoidjk** [comment]
@zeakd can you give a demo about your problem first? I am not sure what's you guys problem is ?

**Comment by zeakd** [comment]
Sorry. I though we share the problem. I have a Search Panel component with z-index 7000. 

SearchPanel.js
```
import React, { Component } from 'react'
import Slider, { Range as _Range, createSliderWithTooltip } from 'rc-slider';
import 'rc-slider/assets/index.css';
import './SearchPanel.scss'

const Range = createSliderWithTooltip(_Range);

class SearchPanel extends Component {
  render () {
    return (
      <div className='SearchPanel'>
        <Range min={-20} max={20}/>
      </div>
    )
  }
}

export default SearchPanel;
```

``` scss
.SearchPanel {
  position: absolute;
  height: 400px;
  width: 100%;
  background-color: lightcoral;
  z-index: 7000;
}

```

but tool tip is gone when I append z-index on it. So, I want to set z-index on tooltip also.

**Comment by paranoidjk** [comment]
You should use z-index less than 1070 https://github.com/react-component/tooltip/blob/943af8d6895cb659aa0d152566152b0eef8c0aa3/assets/bootstrap.less#L26

or you can use `props.overlayStyle` set rc-tooltip z-index

**Comment by zeakd** [comment]
Right. Then how can I set overlayStyle with createSliderWithTooltip?

**Comment by paranoidjk** [comment]
First, you can do it by override css.

If you still want to do it through js, What about i change the api to this?
`createSliderWithTooltip(Range, restPropsForTooltip);`

**Comment by paranoidjk** [comment]
or you can drop `createSliderWithTooltip` away, just use your own HOC, see  
https://github.com/react-component/slider/blob/master/examples/handle.js#L34

**Comment by zeakd** [comment]
It looks good. I prefer to change the api, for we can use full props of rc-tooltip.

**Comment by paranoidjk** [comment]
@zeakd whould you like to give us a PR, since i am busy right now 😄

**Comment by zeakd** [comment]
Actually, I already made new createSliderWithTooltip. 

I think it maybe clear 

`createSliderWithTooltip(Range, { tooltipProps });`

or 

`createSliderWithTooltip({ tooltipProps })(Range)`

in second way, I'm not sure it is useful, but maybe we can use decorator like this

```
@createSliderWithTooltip({ tooltipProps })
Range
```
because createSliderWithTooltip in current version can be used with decorator

**Comment by benjycui** [comment]
```jsx
createSliderWithTooltip(Range, restPropsForTooltip);
```

-1 for this or something like this.

If I want to pass dynamic props to tooltip, this means that I need to create many Slider in render.

```jsx
render() {
  Slider = createSliderWithTooltip(Slider, { style: { color: ... } });
  return <Slider />;
}
```

This will be low performance.

**Comment by zeakd** [comment]
Then How about second one?

**Comment by paranoidjk** [comment]
@benjycui dynamic props is weird use case, IMO, we just give the ability to custom tooltip props, do not need to care about unnormal use case.

**Comment by benjycui** [comment]
How about:

```jsx
const Slider = createSliderWithTooltip(xxx);

<Slider tooltipPrps={...} />
```

**Comment by zeakd** [comment]
I like that way. Is there any performance issue?

**Comment by zeakd** [comment]
I like that way. Is ther any performance issue of it? @paranoidjk 
I'll send pr

**Comment by paranoidjk** [comment]
@zeakd It shouldn't be. You can add the tooltipPrps code at here https://github.com/react-component/slider/blob/master/src/createSliderWithTooltip.jsx#L31

**Comment by benjycui** [comment]
`tooltipPrps` => `tooltipProps `

typo..

**Comment by wootwoot1234** [comment]
Can someone explain to me how to use this?  I'm having the same issue as the original poster.  Here's what I'm doing but it's not working:


    handle = props => {
        const {value, dragging, index, ...restProps} = props;
        return (
            <Tooltip
                prefixCls="rc-slider-tooltip"
                overlay={value}
                visible={dragging}
                placement="top"
                key={index}
                tooltipProps={{overlayStyle: {zIndex: 1051}}}
            >
                <Handle value={value} {...restProps} />
            </Tooltip>
        );
    };

    render() {
        return <Range min={0} max={365} defaultValue={[0, 14]} handle={this.handle} />;
    }
