### ISSUE TITLE
Common API styles are not consistent

### ISSUE THREAD

**Issue by billycai** [react-component/slider#277]
I'm trying to use the component with some custom styles, I manage to get the Slider looking the way I wanted but I literally copy the component and changed from `Slider` to `Range` it renders differently. Not sure why this is happening because the props are the same and all part of the common API shared between both components. Here's a screenshot below:
<img width="950" alt="screen shot 2017-05-31 at 11 59 47 am" src="https://cloud.githubusercontent.com/assets/1152185/26641605/288fef80-45f9-11e7-9d1b-977679cd2417.png">

**Comment by paranoidjk** [comment]
I didn't understand your problem.
Our demo looks fine http://react-component.github.io/slider/

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/26662771/e1f6427a-46b8-11e7-97b6-aff14040a8e9.png)

Make sure that your selectors works for Range's handle and track.

**Comment by billycai** [comment]
The problem is the Range component doesn't apply the track styles or the handle styles passed to the props, only the Slider component applies these styles even though it's under the common API. I believe there is an open PR regarding this issue.

**Comment by paranoidjk** [comment]
Yep, trace at https://github.com/react-component/slider/pull/255

**Comment by paranoidjk** [comment]
Fixed in https://github.com/react-component/slider/pull/281
