### ISSUE TITLE
Wrong handle position when scaled

### ISSUE THREAD

**Issue by Jcqt-390** [react-component/slider#279]
The slider handle is not placed at the right position when it is scaled.

Step to reproduce : Place the slider inside a scaled div

const wrapperStyle = { width: 400, margin: 50,transform:scale(0.5) };
ReactDOM.render(
  <div>
    <div style={wrapperStyle}>
      <p>Slider with custom handle</p>
      <Slider min={0} max={20} defaultValue={3} handle={handle} />
    </div>
    <div style={wrapperStyle}>
      <p>Range with custom handle</p>
      <Range min={0} max={20} defaultValue={[3, 10]} tipFormatter={value => `${value}%`} />
    </div>
  </div>,
  document.getElementById('__react-content')
);

I changed line 211 in lib/common/CreateSlider.js and it works for me :

Prev :  return this.props.vertical ? slider.clientHeight : slider.clientWidth;
Now :  return this.props.vertical ? slider.getBoundingClientRect().height : slider.getBoundingClientRect().width;

**Comment by dbryand** [comment]
Hi @paranoidjk, I just submitted a PR for this. Would appreciate if you could take a look as this is blocking me from using in production (and I don't want to have to go find another slider--this one is great!) Thanks for all of your hard work!

**Comment by paranoidjk** [comment]
Fixed in `rc-slider@8.1.5`
