### ISSUE TITLE
concurrent ranges in same component

### ISSUE THREAD

**Issue by saturation** [react-component/slider#285]
is it possible to have simultaneous ranges in same component with different style.
eg. something like current "disabled" -style with colour could show possible values
and there would be normal range top of that.

of course you can limit choosing different size range but when visualising data and you have list of components it will be a mess.

Something like this:
[link to imgur example picture](http://imgur.com/a/gsVpV)

lightblue shows the possible values etc. maybe just some "zone" and darker is top of that.

**Comment by benjycui** [comment]
I don't understand. If you want to customized style, just override CSS.
