### ISSUE TITLE
Styling the circular dots?

### ISSUE THREAD

**Issue by raubreywhite** [react-component/slider#288]
Hi,

My code for the slider looks like this:

`<Slider.Range
            min={xMin}
            max={xMax}
            defaultValue={defaultValue}
            range={true}
            tipFormatter={this.tipFormatter}
            marks={marks}
            onAfterChange={this.setBrushValues}
            trackStyle={[{ backgroundColor: styles.color.main}]}
            />`

But I can't change the colors of the dots, so I can't match the styling 100% to the rest of my page. Do you have any suggestions on what I should do? Thanks!

<img width="892" alt="screen shot 2017-06-19 at 4 30 54 pm" src="https://user-images.githubusercontent.com/1532091/27290182-c1d9a4de-550c-11e7-8293-b2a2323d21b6.png">

**Comment by paranoidjk** [comment]
use markStyle，please read the api doc and example.

**Comment by TrevorHinesley** [comment]
I don't see any way to style the dot, only the mark text.

**Comment by paranoidjk** [comment]
my mistake，use handleStyle https://github.com/react-component/slider/blob/master/examples/range.js#L144


do you feel the api doc in readme not describe very clear？

**Comment by raubreywhite** [comment]
Hi,

I tried this:

`<Slider.Range
            min={xMin}
            max={xMax}
            defaultValue={defaultValue}
            range={true}
            tipFormatter={this.tipFormatter}
            marks={marks}
            onAfterChange={this.setBrushValues}
            trackStyle={[{ backgroundColor: styles.color.main}]}
            handleStyle={[{ backgroundColor: 'yellow' }, { backgroundColor: 'gray' }, { backgroundColor: 'red' }]}
            />`

And it only lets me style the *big* circles, not the *small* circles.

<img width="886" alt="screen shot 2017-06-20 at 6 02 10 am" src="https://user-images.githubusercontent.com/1532091/27316146-0a1d02c4-557e-11e7-9dcf-31d4340e9754.png">

**Comment by raubreywhite** [comment]
Also

`<Slider.Range
            min={xMin}
            max={xMax}
            defaultValue={defaultValue}
            range={true}
            tipFormatter={this.tipFormatter}
            marks={marks}
            onAfterChange={this.setBrushValues}
            trackStyle={[{ backgroundColor: styles.color.main}]}
            handleStyle={[{ color: 'red' }, { backgroundColor: 'gray' } ]}
            />`

Doesn't let me change the outside color of the big circles...

**Comment by paranoidjk** [comment]
@raubreywhite 
I can not understand what's your problem. The handleStyle will be applied to the handle [props.style(https://github.com/react-component/slider/blob/1f92fb73822b095c6f08cc9b779ff2477c7cee78/src/Range.jsx#L308),, so you can change what ever you like.

**Comment by raubreywhite** [comment]
I need to change the color of the small blue circles (highlighted here). Also I need to change the handle's outline color (currently light blue).

<img width="860" alt="screen shot 2017-06-20 at 4 28 08 pm" src="https://user-images.githubusercontent.com/1532091/27338526-bdf154c4-55d5-11e7-9013-23c8f80678a5.png">

**Comment by paranoidjk** [comment]
@raubreywhite see the `Multi Range with custom track and handle style` demo,  http://react-component.github.io/slider/examples/range.html, code is at [here](https://github.com/react-component/slider/blob/master/examples/range.js#L142).

The handleStyle api is a array of style object, so you can change any style you like.

If you still got problems... Please give a codepen demo to show me where you stuck in ,thanks.

**Comment by raubreywhite** [comment]
I figured it out, I needed to overwrite your css with:

.rc-slider-dot-active {
  border-color: #2196f3 !important;
}

Thank you! :-)

**Comment by paranoidjk** [comment]
nope...

Override css is just one way.

What i say is https://github.com/react-component/slider/blob/master/examples/range.js#L142

```jsx
 <Range count={3} 
  defaultValue={[20, 40, 60, 80]} 
  pushable
  handleStyle={[{ backgroundColor: 'yellow', borderColor: ;#2196f3'  }, { backgroundColor: 'gray' }]}
/>
```

**Comment by raubreywhite** [comment]
Yes, but that only colors the *inside* of the circles, not the outside. And it doesn't color the circles corresponding to the marks.

**Comment by paranoidjk** [comment]
> but that only colors the inside of the circles

Still get confused by you.  `handleStyle={[{  borderColor: '#2196f3'  }]` will change the border color.

> And it doesn't color the circles corresponding to the marks.

The `handleStyle[]` will be applied to  handle style follow the array index order.

**Comment by MaxiSantos** [comment]
handleStyle is the way to go but it dosen't change the :active pseudo class style

**Comment by shravya95** [comment]
as @MaxiSantos mentioned can we get support to change styles of pseudo classes
