### ISSUE TITLE
onAfterChange with value

### ISSUE THREAD

**Issue by jacobp100** [react-component/slider#296]
I have a slider with a `value` set, and an `onAfterChange` handler. However, the slider does not change when dragging. This makes sense, because that is what would happen in the DOM version of React.

However, in React Native, you are able to interact with the slider without having to update the value. The docs are a bit sketchy (wrong) here, but it'll only update the value if the provided `value` prop changes. This contrasts with the DOM, since you don't usually adjust the `value` prop until you've finished sliding.

What's the best way forward for this library: the existing behaviour, or the RN behaviour?

It's worth noting that React Native has `onValueChange` and `onSlidingComplete`, which matches your API better than React DOM, which only has `onChange`.

**Comment by paranoidjk** [comment]
1. `value` + `onChange` 
2. `defaultValue` + `onAfterChange`

https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by eurobob** [comment]
Took me ages to find this. I think there should be a section dedicated to it in the docs
