### ISSUE TITLE
Pre-transpile source code before publishing on npm

### ISSUE THREAD

**Issue by dotted** [react-component/slider#3]
Would it be possible to get you to pre-transpile the source code prior to publishing on npm, as it causes issues when trying to use it while excluding the node_modules folder from transpilation.

Here is another thread about the issue for a different project: https://github.com/pburtchaell/react-notification/issues/8

**Comment by yiminghe** [comment]
thanks, will add support in   [rc-tools](https://github.com/react-component/rc-tools) soon

**Comment by gregsqueeb** [comment]
What is the status of this? Would you appreciate a PR with the pre-transpiled source? I'd be happy to provide it if it'd help move things along.

**Comment by simaQ** [comment]
done
