### ISSUE TITLE
React Slider CSS/Style not working

### ISSUE THREAD

**Issue by DylanRichardPearson** [react-component/slider#301]
[This is my code](http://imgur.com/a/Iq9zX)

The issue is the slider has no formatting/style applied to it and essentially turns out to be one jumble of mark letters [See here](http://imgur.com/a/Iq9zX). 

I have no warnings in the console about missing modules which leads me to believe everything is imported correctly, yet the styling is missing.

Any ideas?

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/aJooRE?editors=0011

**Comment by paranoidjk** [comment]
close for no response.

@DylanRichardPearson Your code seems ok, please provide a reproducible demo.
