### ISSUE TITLE
version 1.6.0 is not working properly in ie8

### ISSUE THREAD

**Issue by carlosaiello** [react-component/slider#31]
with the new version is not passing the tests for ie8.
With ranges the drag and drop of the sliders is a little weird.
I'll try to give a look at it because the ranges is a nice feature to have.

**Comment by benjycui** [comment]
On my way: https://github.com/benjycui/slider/commit/a3bd4db2f865e76799463e6eb8afeacd971e3179

**Comment by benjycui** [comment]
See: #30
