### ISSUE TITLE
[Question] Style active state

### ISSUE THREAD

**Issue by JonWallsten** [react-component/slider#310]
Sorry if this has been answered already. Tried searching/looking through the old issues.
I'm styling the handle by adding the handleStyle attribute. It doesn't however override the default active pseudo state. So a blur glow remains. 
If I completely remove the styles the slider isn't working at all.
Is there any middle ground to this? Just add the critical style for the functionality to work?
Thanks!

**Comment by paranoidjk** [comment]
>  It doesn't however override the default active pseudo state

It's react `props.style` restrictions， we do not have ability to set pseudo class style in jsx.

I suggest you use css.
