### ISSUE TITLE
Feature request: allowEquals for Range

### ISSUE THREAD

**Issue by brmscheiner** [react-component/slider#313]
It would be great if Range accepted an allowEquals boolean for cases where the handles should never be on top of each other. Here are some use cases off the top of my head:

- selecting the start and end time of a meeting 
- setting where a box should begin and end on a grid 
- choosing the min and max GPA required for a student to receive an honors letter 

A more general alternative would be to accept an allowChange function that takes proposed values and returns true or false.

**Comment by paranoidjk** [comment]
Use `Range.allowCross` https://github.com/react-component/slider#range

**Comment by brmscheiner** [comment]
allowCross is a different feature. In the cases above, the handles should not be allowed to cross.

**Comment by paranoidjk** [comment]
@brmscheiner You can use `value + onChange` make `Slider.Range` under control, then you can ensure multi handles never could be equal by change props.value in onChange.
