### ISSUE TITLE
Port into a react native

### ISSUE THREAD

**Issue by Chleba** [react-component/slider#314]
Hi,
Sorry, but may i ask you if there is some sort of progress to port this awesome component into a react-native for use ? There is no other slider component with marks as Yours.
Thanks :)

**Comment by paranoidjk** [comment]
Right now we have no plan. You can try https://github.com/ant-design/ant-design-mobile

**Comment by ajay-dev-j** [comment]
@paranoidjk  Do we have multi slider on it
