### ISSUE TITLE
Feature Request: style 'ends' of Rail separately

### ISSUE THREAD

**Issue by mattholtom** [react-component/slider#316]
The rc-slider-rail object is currently a single, continuous element, and railStyle accepts an object (instead of an array of objects). This means that both ends of the rail have the same style.

I'm struggling to style the ends in different colours, do you know of an easy way to do this?

Would you be open to a pull request that implements the rail as two separate elements 'under the hood'? rc-rail-start and rc-rail-end? 

This would allow railStyle to accept an array of length 2. 
[{backgroundColor: 'blue'}, {background-color: 'red'}]

We are using this component for a % allocation slider (where the 'blank' sections on the rail are also values.) See screenshot.
<img width="606" alt="screen shot 2017-09-04 at 11 55 24 am" src="https://user-images.githubusercontent.com/1645815/30033308-8fdd6e0a-9168-11e7-8bb7-eba1552afba1.png">

Thanks!

**Comment by paranoidjk** [comment]
If you inspect dom in devtools, you will find that the rail means the entire unchecked slider. So it only accept one single style object.

As for your use case, I think you may look for this ? http://react-component.github.io/slider/examples/range.html

<img src="https://gw.alipayobjects.com/zos/rmsportal/pOqrgBkjlGGfwTfzOdvu.png">
