### ISSUE TITLE
Uncontrolled Range component dont work beucase it doesn't receive a required prop.

### ISSUE THREAD

**Issue by rsolci** [react-component/slider#317]
https://github.com/react-component/slider/blob/master/src/Range.jsx#L52

In this line you check if the component receive the value, min or max prop. On uncontrolled components value is not used, but thats ok because it still receives the min and max. But on the followind lines min and max are checked and if they do not change the method returns and the new values are not assigned.
Since the bounds used on render method are from state the component dont re-render properly.

**Comment by paranoidjk** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/aJooRE?editors=0011

**Comment by benjycui** [comment]
Close for no response.
