### ISSUE TITLE
Slider marks extending beyond viewport on mobile

### ISSUE THREAD

**Issue by themirror178** [react-component/slider#318]
Due to the "width: 90%; margin-left: -45%;" on the slider marks, this is causing the element to stretch beyond the viewport, causing the slider and page to extend beyond the device width. My temporary solution is to add style: {width: "initial", "marginLeft": "initial"} to all marks.

I'm not sure why width 90 and margin-left 45 is needed?

![sep 9 2017 5-52 pm](https://user-images.githubusercontent.com/6790025/30238315-ffae9312-9587-11e7-971e-e06119220a6e.gif)

**Comment by ZephD** [comment]
Not just mobile.

**Comment by paranoidjk** [comment]
A reproducible demo please http://codepen.io/benjycui/pen/aJooRE?editors=0011

**Comment by benjycui** [comment]
> I'm not sure why width 90 and margin-left 45 is needed?

To make the center of marks align with corresponding dot. If you can find a better solution, PR is welcomed.

Close now, you can override marks' style to work around.

**Comment by duhaime** [comment]
@benjycui don't you think the default behavior of 8.16.13 (where handles are centered over their labels by default) is better than the behavior of 8.7.0 (where handles are not centered over their labels by default)?

Try changing the version number of this fiddle to see the difference in a minimal code snippet: https://codesandbox.io/s/elated-vaughan-2ylcv

I personally think this change should be reverted. Issues like #434 suggest others expect different default behavior too...
