### ISSUE TITLE
Option to Focus on Handle when Clicking on Slider Component

### ISSUE THREAD

**Issue by jtheberge** [react-component/slider#322]
It would be nice to have an option to autofocus the handler whenever any part of the slider is selected, so rc-tooltip would work on focus correctly. It seems intuitive that clicking on any part of the slider, including the handler, would show the tooltip when it's set to display on focus, but currently that is not the case because no element is ever focused.

**Comment by benjycui** [comment]
> It seems intuitive that clicking on any part of the slider, including the handler, would show the tooltip

Actually, you can achieve this with [customized handle](http://react-component.github.io/slider/examples/handle.html).
