### ISSUE TITLE
Slider Size

### ISSUE THREAD

**Issue by seanfrisbey** [react-component/slider#324]
Is there an easy way to change the size of the slider? I want the slider to be a certain size relative to the other elements on my page. I've been able to override things, but there seems to be some hard-coded padding numbers in the rc-slider code. I can override those too, but that could get finicky in the future with other things. For example, let's say I wanted a 32px handle, and a thick rail to go with it. I'm accomplishing it, but with a LOT of massaging. What is the best way to go about this?

**Comment by benjycui** [comment]
Just override CSS and wrap rc-slider with HOC, we are not going to support size.

**Comment by PainKKKiller** [comment]
Are there any examples of how to wrap rc-slider with HOC ?

**Comment by TracyYXChen** [comment]
You can also just change the offset based on the new width and height, e.g.,
`handleStyle={[{width: '30px', height: '30px', top: '-5px'}`
