### ISSUE TITLE
Range slider is changing both min & max when outside bounds

### ISSUE THREAD

**Issue by lukashambsch** [react-component/slider#328]
With dynamic min & max values, both values are being updated even if only one is outside the new bounds. I think only the value that is outside the bounds should be updated.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/aJooRE?editors=0011

**Comment by afc163** [comment]
@benjycui codepen is not working.

**Comment by benjycui** [comment]
Fixed.

**Comment by afc163** [comment]
`window['rc-slider'].default`

这个 default 能不写吗？在浏览器环境没有什么意义。

**Comment by paranoidjk** [comment]
是因为 entry 从 commonjs 改成了 es module 的原因，解决方案在这里 https://github.com/webpack/webpack/issues/3929#issuecomment-302848532  @yesmeck 看看 rc-tools 要不要处理下？

**Comment by lukashambsch** [comment]
I'm sorry, I'm not exactly sure how to set it up in code pen. I did reproduce it in a test case in the attached PR.

```
it('should only update bounds that are out of range', () => {
  const props = { min: 0, max: 10000, value: [0.01, 10000], onChange: jest.fn() };
  const range = mount(<Range {...props} step={0.1} />);
  range.setProps({ min: 0, max: 500 });

  expect(props.onChange).toHaveBeenCalledWith([0.01, 500]);
});
```

Does anyone know how I would set up something similar in Codepen?

**Comment by paranoidjk** [comment]
@lukashambsch Please fork this codepen https://codepen.io/paranoidjk/pen/QOyrpR?editors=0011

**Comment by lukashambsch** [comment]
@paranoidjk I'm getting the following error with that codepen.

```
"Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in."
```

**Comment by lukashambsch** [comment]
I was able to reproduce it on codepen. If you click the Set button, you'll see that it's resetting the min and max value. That rebinds both the floor and the ceiling values of the slider. But it shouldn't rebind the floor in this case since it's already within the bounds of the min and max.

https://codepen.io/anon/pen/wyqVry/

**Comment by paranoidjk** [comment]
Maybe is umd dist build issue, @yesmeck do you have time to take a look?

**Comment by yesmeck** [comment]
Don't need `default`.

```diff
- const Slider = window['rc-slider'].default;
+ const Slider = window['rc-slider'];
```

**Comment by lukashambsch** [comment]
@paranoidjk @yesmeck Thanks, I was able to figure it out. See my codepen above reproducing the issue.
