### ISSUE TITLE
Upgrade to react 16 already on master, can a tag please be cut and published?

### ISSUE THREAD

**Issue by caguthrie** [react-component/slider#333]
Would love to use this with React 16 in my project.  Thanks

**Comment by benjycui** [comment]
Just upgrade react in your project, we don't need to publish new version of rc-slider.

**Comment by caguthrie** [comment]
With react@16, dependency rc-tooltip@3.4.2 is incompatible as it uses `React.PropTypes`.  While `"rc-tooltip": "^3.4.2"` is listed in package.json which should resolve to a good version normally with the `^`, if a user is using a yarn.lock, package.lock, or similar lockfile with rc-tooltip@3.4.2, nothing will appear wrong when dependencies are resolved.  If you want to reopen this ticket I'm happy to raise a PR.

**Comment by benjycui** [comment]
> If you want to reopen this ticket I'm happy to raise a PR to change this to "rc-tooltip": "^3.4.3", the first version to no longer use React.PropTypes.

OK, just PR.
