### ISSUE TITLE
Cannot control slider via Keyboard

### ISSUE THREAD

**Issue by MrToph** [react-component/slider#335]
Hi, I cannot control the slider via keyboard.

I checked the example here with Chrome v61 by pressing on the handle and then trying to move it with the arrow keys:
http://react-component.github.io/slider/examples/handle.html

I think no keyboard events are fired at all, because the outer `div` can never have focus (no `tab-index`) and prevents the handle component from getting focus because it calls [`utils.pauseEvent(event);` on `Mousedown`](https://github.com/react-component/slider/blob/master/src/common/createSlider.jsx#L107).

**Comment by Robin-front** [comment]
No, I work well. I am also chrome v61  64bit, mac.
keyboard event was implemented with #282 .
The handle `div` has `tabindex="0"`, actually.

If you found any bugs, provide online reproduction, please.

**Comment by MrToph** [comment]
The reproduction is from the example page.

I just checked again: It indeed works when you press `tab` to focus the handle, but if you drag using the mouse / click on the handle, the handle will not get focus and no keyboard events are fired.

I expected a click on the handle / anywhere on the rail to also enable keyboard control

**Comment by paranoidjk** [comment]
@MrToph You are right. https://github.com/react-component/slider/issues/349

**Comment by amaatouq** [comment]
This feature would be super useful!
