### ISSUE TITLE
Controlled Slider does not allow mouse/touch interaction

### ISSUE THREAD

**Issue by martisj** [react-component/slider#337]
Reproducible demo is shown right here in the example.
http://react-component.github.io/slider/examples/slider.html

Try sliding the `Controlled Slider` component and see that it cannot be changed with mouse interaction only programmatically by updating state.
#237

**Comment by Robin-front** [comment]
No, not.
I think you misunderstood the controlled components. 
Check here:
 [https://reactjs.org/docs/forms.html#controlled-components](https://reactjs.org/docs/forms.html#controlled-components)
