### ISSUE TITLE
React 16 ES6 Classes Needs Upgrade

### ISSUE THREAD

**Issue by moog16** [react-component/slider#339]
I am trying to upgrade to React 16, and it seems like rc-slider has a dependency on rc-tooltip, which in turn has the same error as shown in this [issue](https://github.com/react-component/tooltip/issues/106). When rc-tooltip's rc-trigger dependency is upgraded, rc-slider should also be upgrade.

**Comment by paranoidjk** [comment]
Fixed in https://github.com/react-component/tooltip/pull/105. Please reinstall your node_modules.
