### ISSUE TITLE
how to remove the style with marks and step=null

### ISSUE THREAD

**Issue by BenNG** [react-component/slider#341]
Hello I have this configuration and the result above. How can I remove the style `rc-slider-dot` with a config (I would like to avoid if possible a css solution) Thank you !!
```
<Range
  marks={marks}
  allowCross={false}
  min={min}
  max={max}
  step={null}
  defaultValue={getValue()}
  onChange={this.onSliderChange(setValue)}
  value={getValue()}
  trackStyle={{}}
  railStyle={{}}
/>
```

![screenshot from 2017-10-23 16 46 12](https://user-images.githubusercontent.com/456239/31895533-b4af282a-b811-11e7-85e0-6122176873db.png)

**Comment by paranoidjk** [comment]
You can use `dotStyle` and `activeDotStyle` api

https://github.com/react-component/slider#common-api
