### ISSUE TITLE
onChange event is firing only once when dragging the slider along the rail

### ISSUE THREAD

**Issue by ThomasGueldner** [react-component/slider#342]
Hi developers and react-lovers.

Since yesterday I have been trying to use react-slider. So far, everything seems to work as described in the descriptions. But there is one thing that I don't get to work for whatever reason...

I have a slider container which stores the current value of the slider in a state and passes it through to its child which is component, responsible for rendering the UI. When I then press the mouse button and drag the slider in any direction, the ```onChange``` event is called appropriately and updates the value's state in the slider container (I have verified that through logs). Now I was expecting that as long as I keep the mouse button pressed, that I would be able to continue dragging the slider which should continuously firing the ```onChange``` event. But this exactly does not happen. I also used the ```onAfterChange```event method to confirm whether this one is unintentionally called once I continue dragging the slider, but this isn't the case. The weird thing is that once the slider has been re-rendered and the value of the slider has been updated. no other event is fired anymore as long as I keep pressing the mouse. Then when I do a mouseUp, even the ```onAfterChange``` event isn't called here. I have no clue why this is the case here.
In my slider component I use the ```value``` property to assign the handle's position to its designated position which is given by the state ```props``` in the component (the props gets its values from the ```state``` in the container).

I have been checking the custom slider demo which exactly does that thing I am trying to successfully implement. 

I know that I don't have provided any code here yet, but according to my explanation of my problem here so far, do you see any misconception of mine in this case?

Any ideas, solutions or whatsoever is highly appreciated! :)

**Comment by ThomasGueldner** [comment]
A little Update on this here:

I haven't mentioned yet that I am using a slider in combination with a tooltip:

```const SliderWithTooltip = createSliderWithTooltip(Slider);```

I just noticed that if I use an ordinary Slider **without** the tooltip, then sliding the ```Slider``` works properly! But as soon as I apply the ```createSliderWithTooltip``` to the common ```Slider```, then the problem I described in my previous post appears again. I just haven't found out yet, why the ```SliderWithTooltip``` doesn't work in my work.

Did maybe someone have similar problems with that before?

**Comment by ThomasGueldner** [comment]
Update #2:

I just got mamaged to get my custom Slider to work the desired way. But it turned out that I could only do it, because I added a custom ```Handle``` with a ```Tooltip``` object by using the following code:

```
const Handle = Slider.Handle;
const percentFormatter = (value) => (Math.floor(value / sliderData.max * 100) + "%");
const handle = (props) => {
    const { value, dragging, index, ...restProps } = props;
    return (
        <Tooltip
            prefixCls    = "rc-slider-tooltip"
            overlay      = {percentFormatter(value)}
            visible      = {dragging}
            placement    = "top"
            key          = {index}
        >
            <Handle value={value} {...restProps} />
        </Tooltip>
    );
};
```

And here the render method:

```
<Slider 
    min             = {sliderData.min} 
    max             = {sliderData.max}
    defaultValue    = {sliderData.defaultValue}
    value           = {sliderData.value}
    disabled        = {isDisabled}
    onChange        = {(value) => sliderInputHandler(value, sliderData.name)}
    handleStyle     = {[baseStyles.input.sliderHandle]}
    trackStyle      = {baseStyles.input.sliderTrack}
    railStyle       = {baseStyles.input.sliderRail}
    handle          = {handle}
/>
```

I just wonder whether this is the intended way to implement a custom slider with a tooltip whose values come as state props? Unfortunately, I couldn't get this to work:

```const SliderWithTooltip = createSliderWithTooltip(Slider);```

Using this would make my code cleaner (which I therefore would prefer to use however).
I wonder whether I made a mistake there or whether this is a bug in react-slider?
The code I tried to use for that was the following one:

```
const SliderInput = ({classes, sliderData, isDisabled, customSliderClass, sliderInputHandler}) => {
    const SliderWithTooltip = createSliderWithTooltip(Slider);
    const percentFormatter = (value) => (Math.floor(value / sliderData.max * 100) + "%");

    console.log(sliderData)

    return (
        <div className={classes.sliderWrapper}>
            <SliderWithTooltip 
                tipFormatter    = {percentFormatter}
                className       = {customSliderClass !== undefined ? customSliderClass : classes.slider} 
                min             = {sliderData.min} 
                max             = {sliderData.max}
                defaultValue    = {sliderData.defaultValue}
                value           = {sliderData.value}
                disabled        = {isDisabled}
                onChange        = {(value) => sliderInputHandler(value, sliderData.name)}
                onAfterChange   = {(value) => sliderInputHandler(value, "after change")}
                handleStyle     = {[baseStyles.input.sliderHandle]}
                trackStyle      = {baseStyles.input.sliderTrack}
                railStyle       = {baseStyles.input.sliderRail}
            />
        </div>
    );
};
```

If you notice a any mistake or misconception here, please let me know it.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/aJooRE?editors=0011

**Comment by yesmeck** [comment]
Closing since no response.

**Comment by actual-size** [comment]
This is still an issue, Thomas's fix works. I'll try to provide a reproducible example when I get time, but it's really as simple as ```
const SliderWithTooltip = createSliderWithTooltip(Slider)

<SliderWithTooltip />
```
