### ISSUE TITLE
Increase size of touch area

### ISSUE THREAD

**Issue by jwamsterdam** [react-component/slider#344]
Hi, 

Using this slider on mobile (IOS) I experience difficulties to select and move the slider with touch. I have increased the slider button size, but to limited avail. 

Can I increase the touch area of the slider, perhaps by CSS, to make it bigger than the slider button?

**Comment by paranoidjk** [comment]
Please aware that there are two kinds of gesture that rc-slider supported. You can click any point in the slider bar to move the slider to just that point. And you can  drag the slider by you hand.

 so if you make the handler touch area bigger than it's real size, the user's touch may not accuracy.

I suggest you just increase the handler size?

**Comment by jwamsterdam** [comment]
Ok, I will go for that solution

Verstuurd vanaf mijn iPhone
