### ISSUE TITLE
onAfterChange event is firing only once when dragging the slider away from the rail(slider)

### ISSUE THREAD

**Issue by kishoreyarram** [react-component/slider#346]
onAfterChange is working fine in my localhost, But when I deployed my code in stages its behaviour got changed.

Expectation: when we drag range onAfterChange should trigger immediately after leaving the mouse Current Situation: Its getting triggered after going away from the slider and leaving.

**Comment by Woblin** [comment]
In my case onAfterChange only trigger sometimes. Not when i release the mousebutton. So I get less than the expected onAfterChange events. And this is in localhost.
OnChange works as intended everytime the handle move.

![image](https://user-images.githubusercontent.com/196509/32057954-05e2f006-ba69-11e7-8650-dbef772fdf03.png)

**Comment by ha1ogen** [comment]
I think they fixed the issue in the latest version (8.3.5)

**Comment by Woblin** [comment]
@ha1ogen Yes you are correct, I updated to 8.3.5 and now it works!
