### ISSUE TITLE
Controlled Range with allowCross=false has issues

### ISSUE THREAD

**Issue by lap123** [react-component/slider#347]
Here is a demo: https://codepen.io/anon/pen/LzwzEW

Specifically, with 3 ranges or more, when cursor i is moved, cursors from i+2 and beyond are set to the value of i+1. Cursors from i-2 and before are set to i-1 value.

**Comment by paranoidjk** [comment]
@benjycui 

Seems  [ensureValueNotConflict](https://github.com/react-component/slider/blob/master/src/Range.jsx#L275) logic is wrong when there is over 3 handle.

Right now it haven't consider about the beeing processed value index in the whole bounds array, which cause all  satisfy `index > curHandle && value > curValue` condition's handle got set to current handle value.

And it may need to handle `pushable` situation at the same time.

**Comment by Robin-front** [comment]
@paranoidjk  agree.
I think I had fixed at #304 , I add `index` to `ensureValueNotConflict`, please check.
