### ISSUE TITLE
tooltip do not hide while mouse leave

### ISSUE THREAD

**Issue by a1528zhang** [react-component/slider#348]
after I drag the slider, the tooltip don't hide, this issue is also happened on your demo: 
[http://react-component.github.io/slider/examples/handle.html](http://react-component.github.io/slider/examples/handle.html)

chorme version:  61.0.3163.100

**Comment by paranoidjk** [comment]
Works fine in my osx chrome 61.

Please notice that the tooltip will hide after you cursor leave slider.

**Comment by paranoidjk** [comment]
@a1528zhang  Sorry, i confirmed it's a bug which introduced inhttps://github.com/react-component/slider/pull/306,  and it's been fixed by https://github.com/react-component/slider/commit/18d4fa33319618795f7c9cbe5045dc0d0ed33299. Please reinstall your node_modules.

cc @Robin-front
