### ISSUE TITLE
Can I simulate the "onFocus" event?

### ISSUE THREAD

**Issue by matias89** [react-component/slider#349]
Hello. In my project we save the data in the server when the user leaves the form element (input type). But, if I am focused on an input text, and I click on the Slider, in the input text doesn't execute the "blur" event (then I can't save the data). Please see the attached file.

![oct-26-2017-12-48-pm](https://user-images.githubusercontent.com/5619274/32064413-28f5de28-ba50-11e7-83ba-acd249a28ddf.gif)

**Comment by paranoidjk** [comment]
It's because we pause events right now https://github.com/react-component/slider/blob/master/src/utils.js#L70

I am consider we can drop this logic cc @benjycui

**Comment by matias89** [comment]
@benjycui can you consider make the change?

**Comment by LandonSchropp** [comment]
@paranoidjk I've also run into this problem with my project. Specifically, I hook into the blur event on a different input, but it doesn't fire because the slider doesn't focus.
