### ISSUE TITLE
Can't set tabIndex on handle

### ISSUE THREAD

**Issue by gvincentlh** [react-component/slider#353]
We need to be able to disable tabbing into the `rc-slider-handle` by setting `tabIndex="-1"`. Unfortunately it looks like tabIndex on the handle is currently hard-coded to "0", with no ability to override this value. https://github.com/react-component/slider/blob/76d4cf3567c48a43922f6a8c00f5b892e62d41e3/src/Handle.jsx#L28

Could you please add the ability to override `tabIndex` on the handle?

**Comment by paranoidjk** [comment]
It's for keyboard accessibility, could you explain why you need to disable it ? https://github.com/react-component/slider/pull/282

**Comment by gvincentlh** [comment]
@paranoidjk does the **why** really matter? We'd just like to have control over the `tabIndex` value on the handle. We want to create an explicit tab order on multiple page elements. Thanks.

**Comment by paranoidjk** [comment]
Then we maybe could add a api `tabIndex: boolean | number (default to be 1, false to disable)`

Would you like PR?

**Comment by gvincentlh** [comment]
@paranoidjk sounds good, yes will submit a PR tomorrow.

**Comment by gvincentlh** [comment]
@paranoidjk see the MDN docs on tabIndex here https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

We should probably default it to "0" as it is now, but allow it to be overridden via props. I'll expose a `tabIndex` prop on the Handle component.
