### ISSUE TITLE
Vertical slider throws TypeError

### ISSUE THREAD

**Issue by marcusmathioudakis** [react-component/slider#355]
I cannot seem to create a vertical slider. Using the code below:
import React from "react";
import Slider from 'rc-slider/lib/Slider';
import 'rc-slider/assets/index.css';

export default function EffectControl(props) {
	return (
		`<div>
			<Slider min={0} max={20} defaultValue={20}  vertical={true}/>
		</div>`
	);

I get the error "Uncaught TypeError: Cannot read property 'toFixed' of undefined".

Am I missing something?

**Comment by corevo** [comment]
I have encountered a similar issue, it happens because the default `height` is set to `100%`  
Set a height and it should work  
```jsx
<Slider vertical included={false} style{{
  height: "150px"
}} />
```
You can check my code [here](https://github.com/SeleniumHQ/selenium-ide/blob/master/src/neo/components/GaugeMenu/index.jsx)

**Comment by marcusmathioudakis** [comment]
Awesome - thank you Tom. This should be ideally mentioned in the
documentation.

**Comment by marcusmathioudakis** [comment]
sorry I meant thank you Tomer - autocorrect....

**Comment by corevo** [comment]
It's alright, my friends call me Tom
