### ISSUE TITLE
Missing key prop

### ISSUE THREAD

**Issue by schneckentempo** [react-component/slider#358]
I get the following error and would like to get this resolved:
![image](https://user-images.githubusercontent.com/1663926/32660004-5af0e81e-c621-11e7-838a-ca8eb8674781.png)

Looking into the code I think handles is missing the key prop

https://github.com/react-component/slider/blob/0a07adac3694f5881ecf9dffcd4831ba6fafeff9/src/Range.jsx#L307

**Comment by yesmeck** [comment]
Could you try the latest version? Ping me if the issue still exists.

**Comment by TkDodo** [comment]
The warning / error is still reproducable with version `8.6.9`.

Current code pointer seems to be this:

https://github.com/react-component/slider/blob/master/src/Range.jsx#L358

Could you re-open this issue?
