### ISSUE TITLE
 onAfterEnd - cant get event

### ISSUE THREAD

**Issue by AndreyMiloserdov** [react-component/slider#360]
`  onEnd = () => {
    this.setState({ dragging: false });
    this.removeDocumentEvents();
    this.props.onAfterChange(this.getValue());
  }`
But correct
`onEnd = (evt) => {
    this.setState({ dragging: false });
    this.removeDocumentEvents();
    this.props.onAfterChange(this.getValue(), evt);
  }`

**Comment by yesmeck** [comment]
Duplicate of #261
