### ISSUE TITLE
Touchend firing twice (I think)

### ISSUE THREAD

**Issue by sciku1** [react-component/slider#361]
I've got this piece of code:
```
class PriceFilter extends Component {
    onChange(price) {
        this.props.store.filters.price_max = price;
    }
    render() {
        return (
            <div className="price-filter">
                <Slider
                    min={0}
                    max={2500}
                    step={10}
                    defaultValue={2000}
                    onChange={this.onChange.bind(this)}
                    onAfterChange={this.props.reload.bind(this)}
                />
                <div className="min">$1</div>
                <div className="max">$2500+</div>
            </div>
        );
    }
}
```

On mobile, if I tap instead of drag the slider afterChange gets called twice. I believe this is a bug.

**Comment by Robin-front** [comment]
duplicate `onMouseUp` cause twice `this.onEnd` invoked and twice `afterChange`

**Comment by yesmeck** [comment]
@sciku1 Try 8.6.1

**Comment by brinley** [comment]
I just noticed the issue as well on 8.6.4. From what i can see onAfterChange is fired again from onEnd when the slider loses focus https://github.com/react-component/slider/blob/master/src/Slider.jsx#L97
I don't believe adding stopPropagation will resolve the issue. Do we even need to call onAfterChange in onEnd when onAfterChange is already fired on touchend/mouseup?

**Comment by dangnelson** [comment]
I'm experiencing this issue in 8.6.9 which is causing the slider to pop back to the initial value.
