### ISSUE TITLE
npm module IE<=10 support

### ISSUE THREAD

**Issue by Roman-Maksimov** [react-component/slider#368]
The component, which has been installed via `npm` doesn't actually work  on IE<=10 as the babel < 6.14.0 doesn't support parent constructor call for the IE <= 10 (as it doesn't have `__proto__`).
https://github.com/babel/babel/issues/3041
https://github.com/babel/babel/pull/3527

Anyway the Component uses parent constructor call

```javascript
// Slider.jsx
class Slider extends React.Component {
  constructor(props) {
    ...
    // here the this.state is initializing
    // but the constructor is not being called on IE<=10
    this.state = {
      value: this.trimAlignValue(value),
      dragging: false,
    };
    ...
  }
  ...
  render() {
    // as a result, the error 'Can not read property 'value' of null' appears here
    // and crashes the whole remaining JS
    const { value, dragging } = this.state;
  }
...
export default createSlider(Slider);
```
```javascript
// common/createSlider.jsx

export default function createSlider(Component) {
  return class ComponentEnhancer extends Component {
    ...
  }
};
```

To solve the problem it's necessary to recompile the module with babel plugin `transform-es2015-classes` + `loos` option

```
npm install --save babel-plugin-transform-es2015-classes
```
```javascript
{
  ...
  "plugins": [
    ...
    ["transform-es2015-classes", {"loose": true}]
  ]
}
```

**Comment by yesmeck** [comment]
https://github.com/react-component/rc-tools/commit/2c37699ee9051a0302feb8cb6138c5c2ccb0fe4e

**Comment by yesmeck** [comment]
Release rc-slider@8.4.1, could you confirm does this issue has been resolved?

**Comment by Roman-Maksimov** [comment]
Yes, it works now. Thanks!
