### ISSUE TITLE
when slider prop is min={0}, zero is hidden on slider

### ISSUE THREAD

**Issue by evbots** [react-component/slider#375]
I think there is a falsy check in the rc-slider library that causes the "zero" point to be hidden when rendered. This is only if the min prop passed as 0.

 It's a new bug in v8.5.0 and v8.0.0 doesn't exhibit the buggy behavior

**Comment by cardamo** [comment]
This workaround worked for me:
```
const pctMarks = {0: '0', 20: 20, 40: 40, 60: 60, 80: 80, 100: 100};
<Slider marks={pctMarks} />
```

**Comment by mr-devboy** [comment]
Have the same issue
