### ISSUE TITLE
Handler size

### ISSUE THREAD

**Issue by dennisat** [react-component/slider#382]
Hi

**Very nice job, it's really good and simple.**

A small problem styling the handler. When for instance I set it to be 24x24px and slide the handler at the end, the handler is going off the rail. Let's say that this is expected since the code expects the handler to be 14x14px.

How can we fix this? Maybe getting the size of the handler from the dom is a good solution. 

Any help is appreciated.

**BR Dennis**

**Comment by dennisat** [comment]
For ppl facing the same issue.
I solved this issue wrapping it in another component and applying some style that gives the output I want.

**Comment by yesmeck** [comment]
Glad to see you resolved it.

**Comment by PainKKKiller** [comment]
Have  the same issue. Anyway is there any more elegant solution?
