### ISSUE TITLE
[Feature request] Set minimum and maximum possible values

### ISSUE THREAD

**Issue by rpiaggio** [react-component/slider#384]
In some cases, we want the slider range to visually span a range of values but only allow the user to select values from a subrange.

Eg: A user can pay any price from $20 to $100 for a product or service. We want the slider bar to be visually proportional to what he's paying, so we would set we would set `min = 0, max = 100`. But we don't want to let the user actually move the slider under 20. We propose a new property `minValue = 20` to achieve this. Similarly, a `maxValue` probably makes sense too.

Thank you!

**Comment by Robin-front** [comment]
maybe, try to limit `values` on the `onChange` function manually

**Comment by yutingzhao1991** [comment]
> maybe, try to limit values on the onChange function manually

Ant use marks for friendly UI.

---

We can discuss this future for more convenient to use.

**Comment by rpiaggio** [comment]
I'm using both suggestions and works just as needed. Thank you very much @Robin-front and @yutingzhao1991 !
