### ISSUE TITLE
Possible to create a slider with zero in the middle?

### ISSUE THREAD

**Issue by sardaukar** [react-component/slider#386]
Hello!

Is is possible to create a slider running from -100 to 100, zero in the middle (as the default) and no "color" filled in? Can't seem to find an example of this.

Thanks!

**Comment by yutingzhao1991** [comment]
You can set `min` `max` and `marks` props for your want.

There is a demo for you: https://codesandbox.io/s/kkojq34z63.

**Comment by blobinabottle** [comment]
Regarding this, is it possible to make the track start from the middle?
Trying to achieve this:
https://cl.ly/3A0u0w0d0I1r

I tried to hack it already but don't see what else I could do : https://codesandbox.io/s/l7ymkk4nwl

**Comment by Jantwel** [comment]
For this case you need to control click on track by yourself.
https://codesandbox.io/s/k7r90jw37

**Comment by blobinabottle** [comment]
That's perfect. Didn't expect that flexibility with this component! Really clean! Many thanks!!
