### ISSUE TITLE
CSS Styles not imported

### ISSUE THREAD

**Issue by alejandrocfc** [react-component/slider#389]
Follow the demo use: _import 'rc-slider/assets/index.less';_

But on  render, the styles never import...

My setup: ES6, webpack and SCSS for styles

Btw... would be great have styles formatted

**Comment by yutingzhao1991** [comment]
use `import 'rc-slider/assets/index.css';` to replace `import 'rc-slider/assets/index.less';` and try again.

**Comment by alejandrocfc** [comment]
Ty for reply, I forge to write that I use `import 'rc-slider/assets/index.css';` too... perhaps is something about webpack?

**Comment by yoiang** [comment]
I have the same issue, I had to use `rc-slider/dist/rc-slider.min.css` locally and none of the three options presented work on CI. Perhaps an inline CSS version could be offered as an optional alternative?
