### ISSUE TITLE
min/max inversion

### ISSUE THREAD

**Issue by dmaison** [react-component/slider#399]
there should be a property that allows the swapping of the ends of the axis.

(i.e. vertical slider minimum value on the top, maximum value on the bottom)

rotating with css affects the functionality

**Comment by yesmeck** [comment]
Duplicated of #216

**Comment by dmaison** [comment]
@yesmeck the fix for that ticket appears to be included in 8.6.1, but it doesn't look like the inverted prop affects ranges.

Is there something more to it than `inverted={ true }`, or was this feature not implemented yet for ranges?

**Comment by yesmeck** [comment]
@dmaison It's not been merged yet.
