### ISSUE TITLE
createSliderWithTooltip loses support for custom handle

### ISSUE THREAD

**Issue by allenylzhou** [react-component/slider#400]
https://github.com/react-component/slider/blob/master/src/createSliderWithTooltip.jsx does not respect the `handle` property in [Common API](https://github.com/react-component/slider#common-api)

**Comment by ShinaZin** [comment]
I have same problem

**Comment by viv3kk** [comment]
Trying to set handle as visible ...no option to do that

**Comment by yesmeck** [comment]
See this [example](https://github.com/react-component/slider/blob/master/examples/handle.js#L10:7), you can create tooltip without createSliderWithTooltip.
