### ISSUE TITLE
Range slider not updating when values (other than min/max) change

### ISSUE THREAD

**Issue by benheb** [react-component/slider#404]
Is this line needed? https://github.com/react-component/slider/blob/master/src/Range.jsx#L55

This means that when pass an array with length > 2 to the range slider, it doesn't update correctly if I'm not changing either the min or max number.

**Comment by yesmeck** [comment]
This line checks value https://github.com/react-component/slider/blob/8ebb31077eee803f1838963de8ed0db3e717722d/src/Range.jsx#L56

Could you demostrate your issue on https://codesandebox.io?

**Comment by benheb** [comment]
Nope, seems to work in this sandbox! https://codesandbox.io/s/yw2l84m0mj 

I'm using the slider wrapped with `antd`, so maybe something on their end... will keep looking and close for now.
