### ISSUE TITLE
Stop Propagation when using slider

### ISSUE THREAD

**Issue by bernatfortet** [react-component/slider#405]
First, thanks for the great component 🙏 

I have a Component that expands when clicked.
This component contains some inputs that, when clicked, use event.stopPropgation() to not trigger the expand of their parent.

With rc-slider I can't find how or when to use event.stopPropagation. Now, if I use the slider its parent expands.

Any idea on how to solve this issue?

Thanks

**Comment by yesmeck** [comment]
You can wrap rc-slider with a div, and call `event.stopPropgation()` on that div.

```javascript
<div onClick={(e) => e.stopPropgation()}>
  <Slider />
</div>
```

**Comment by bernatfortet** [comment]
Interesting... I tried that already and it was not working. 
I'll look deeper into it.

**Comment by ccowen** [comment]
@bernatfortet Were you able to get it working?

**Comment by OmarSolano1** [comment]
It works for me using this: 

    ` renderIndicator={(onClickHandler, isSelected, index) => {
                    return (
                        <span onClick={(e) => e.stopPropagation()}>
                            <li className={`dot ${isSelected && "dot selected"}`} onClick={onClickHandler} key={`carousel-${index}`} />
                        </span>
                    );`
