### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by cyclonstep** [react-component/slider#406]
Hello, I'm new in this open source thing and I really want to contribute in this project. do you have a contribution guide or some guidance for me to keep up with the updates of this project or do you have slack or anything like that? because I've been searching within this repository and didn't find any links or guide for contributing in this project. Thank you very much

**Comment by yesmeck** [comment]
You can refer to http://makeapullrequest.com/

**Comment by cyclonstep** [comment]
wow thank you very much!
