### ISSUE TITLE
IE9 not supported

### ISSUE THREAD

**Issue by agile116** [react-component/slider#41]
Hi All,

I couldn't make the slider show in IE9, anything special need to do? Thanks.

**Comment by benjycui** [comment]
Do you mean [this example](http://react-component.github.io/slider/examples/simple.html)?

**Comment by agile116** [comment]
yes, it works now. Some other css file corrupted with this one. I imported before that one and  it worked, something wrong with webpack build. Thanks for your reply. :)

**Comment by benjycui** [comment]
OK, close now.
