### ISSUE TITLE
Event.target on click 

### ISSUE THREAD

**Issue by mquandalle** [react-component/slider#422]
Hello,

I registered a global click event listener:

```
document.body.addEventListener("click", event => {
    console.log(event);
});
```

In this listener I want to identify if the click is from `rc-slider` drag. On other components I could use `event.target` or `event.relatedTarget` to identify a click from that component. But with `rc-slider` if I move my mouse out of slider while dragging, and then release the mouse, the there is no way to identify that the click comes from `rc-slider`.

**Comment by okasha93** [comment]
I Faced the same problem and i ended up with to use HTML Input range.
Here's an Example: [JsFiddle] (https://jsfiddle.net/okasha/zs61go1v/)

This's a work-around solution to have form of multiple Sliders and handle them dynamically.

You can check [stackoverflow answer](https://stackoverflow.com/a/50466842/5863487)

**Comment by mquandalle** [comment]
Yes HTML input[range] works, but I'm using advanced features of the antd slider such as the tooltip on slide, or the `marks` prop. I think this component is doing something weird with the release click event and it should be possible to fix it.

**Comment by mquandalle** [comment]
I guess the issue comes from the `removeDocumentEvents()`?

**Comment by okasha93** [comment]
@mquandalle  but it's only added [here](https://github.com/react-component/slider/blob/master/src/Slider.jsx) on `onEnd` function 
```
onEnd = () => {
    this.setState({ dragging: false });
    this.removeDocumentEvents();
    this.props.onAfterChange(this.getValue());
  }
```
let's try to remove it and i think we should add **event** to `onChange` function parameters. 

It's really strange that [react-input-range](https://github.com/davidchin/react-input-range) also send value onChange i don't know if they didn't handle event or not, but it seems that they didn't handle it the same as `rc-slider` !!

**Comment by mquandalle** [comment]
But I'm curious, is `removeDocumentEvents` really responsible for this issue (I only inferred that from the method name) and what's the reasoning behind it @benjycui?

**Comment by mquandalle** [comment]
This issue happens on Chrome but not on Firefox.
