### ISSUE TITLE
Wide handle size staying inside the track

### ISSUE THREAD

**Issue by bpsmit** [react-component/slider#431]
Hello,

If I use a large handle, say 10% of the entire track size, one side runs off the track. Since the slider is only tracking a single value, is there any work around for this?

If I was to shift the handle with a margin, the same issue would appear on the other side of the track.

Any ideas?

**Comment by bpsmit** [comment]
A workaround I found...

You

**Comment by nkint** [comment]
How have you solved? I have the same issue currently hammering it with some fixed size of the rain parent and padding but it feels hacky and dirty and unstable

**Comment by bpsmit** [comment]
Hi nkint!

Unfortunately I had to do a similar dirty hack with fixed size and padding to extend the track visually. Never found a better solution.
