### ISSUE TITLE
marks 和 step 关系问题

### ISSUE THREAD

**Issue by afc163** [react-component/slider#44]
版本：3.0.1

经过 3.0 的改造，刻度 marks 属性现在是对象形式：

```js
marks={{
  "0": "零度",
  "100": "沸点",
}}
```

这样 marks 和 step 本身没有联系，用户只是用它在已有的 slider 上标注刻度文字。

---

目前的实现，对于 step 不为 1 的情况，完全符合上述描述。

对于 step 为 1 的情况，变成用户只能选择刻度 marks 里指定的值。应该是有问题的。

---

上面的情况是想要实现类似 http://09x.ant.design/components/slider/#demo-mark 的分段式滑块的效果，即用 marks 将滑块变为离散的。而原有的 API 是 `marks={['刻度一', '刻度二'，'刻度三']}`。

---

以下有两种解决方案：

1. 兼容原有的 API，即当  `marks={['刻度一', '刻度二'，'刻度三']}` 为数组时，将 marks 和 step 进行绑定，实现离散滑动条。当 marks 为 Object 时，刻度和 step 完全分离。

2. 新增参数 `markAsStep` 属性，当此属性为 `true` 时，刻度作为 step ，用户只能选择刻度值。当为 `false` 时，刻度和 step 完全分离。默认为 `false`。

**Comment by benjycui** [comment]
用方案 2 实现，毕竟数组还是不够灵活。
