### ISSUE TITLE
Library breaks when passing in Javascript Min/Max Infinity

### ISSUE THREAD

**Issue by castrolem** [react-component/slider#448]
When sending `currentMin` or `currentMax` of`-Infinity` / `Infinity` the whole project breaks, we could avoid it by verifying that the number we're sending `isFinite` :)

**Comment by castrolem** [comment]
@sospedra found the line where it breaks while discussing it with him https://github.com/react-component/slider/blob/master/src/utils.js#L22 haha, I will make a PR this weekend to fix it :)

**Comment by sospedra** [comment]
If `closestPoint` is `+/-Infinity` pull the max or min point in `points`. Instead of doing the current calc with the `diff`. That should fix it.
