### ISSUE TITLE
High maximum value / step causes errors

### ISSUE THREAD

**Issue by iktl** [react-component/slider#46]
As the slider's max value increases performance degrades steadily, before failing outright at higher values. This looks to be a function of max value and step together (the number of actual steps on the slider). I was trying this out as a currency amount input slider so the max value was well into the tens / hundreds of thousands. 

The error is:

```
Unhandled promise rejection RangeError: Maximum call stack size exceeded(…)
```

I was getting this at: 
* `max = 200,000` and `step = 1`
* `max = 100,000` and `step = 0.5`

**Comment by benjycui** [comment]
Yes, and I knew the reason for low performance. I will try to make it faster when I have time.

But I am curious about your use case. It is hard to select a specific point out of 200,000 points.

**Comment by iktl** [comment]
It's definitely a weirder use case, where users are able to adjust the sliders and modify data points being pushed onto a chart – so the slider values are linked to the domain of the chart itself. However, that being said, I changed the approach to instead of using the raw value from the slider:

* Keep the min / max values as a prop on my container
* Set the slider from 0 - 100
* onChange function takes the slider's input from 0 to 100% and interpolates it between the min and the max.

The result ends up letting me user the slider to select from a very, very wide range, but without needing to create 100,000+ steps in the slider itself. The workaround is solid for me, so if you even wanted to just close this issue outright and if it comes up again suggest this as the workaround I'm fine with that.
