### ISSUE TITLE
Error OnClick of Slider: Unable to find node on an unmounted component

### ISSUE THREAD

**Issue by rodaan** [react-component/slider#469]
Hi,
I'm getting this odd error whenever I try to click any part of the slider component.
`Unable to find node on an unmounted component.`
https://reactjs.org/docs/error-decoder.html?invariant=188

Funny enough, this only happens in production for me. Anybody encounter this error? I'm unsure how to fix it.

Thanks,
Rodaan

**Comment by zombieJ** [comment]
Pls provide an online reproduce: https://codesandbox.io/

**Comment by BruOp** [comment]
I haven't been able to reproduce this in https://codesandbox.io/ but I'm encountering the exact same problem in a private project.

I solved it by pinning all my dependencies, which you might want to try @rodaan.

**Comment by jiangyijie27** [comment]
@rodaan I update to rc-slider@8.6.2, and it fixes the problem.

**Comment by rodaan** [comment]
Thanks for the responses. I was able to solve the issue by doing what @BruOp said. Thanks for the help!

**Comment by CameronAckermanSEL** [comment]
@zombieJ why is the yarn.lock file ignored? Having this file in the repo would help people pull in the correct version of dependencies.

**Comment by kahummer** [comment]
@jiangyijie27 the upgrade works
