### ISSUE TITLE
Discrete Slider?

### ISSUE THREAD

**Issue by vgoklani** [react-component/slider#47]
My code was previously working, but it seems the changes in 3.0 have broken a few things, as I can no longer get a discrete slider. 

Is this now the correct way of defining the marks object?

marks:{"0":"8-HR", "33":"1-Day", "66":"3-Day", "100":"7-Day"}

and should "included" be set to false? This is still giving me a continous slider:
<Slider onChange={that.handleChange.bind(that, d.field)} key={"3sliderDiscrete"} included={false} marks={d.marks} />

**Comment by benjycui** [comment]
Set `step={null}`. See: https://github.com/react-component/slider#props 

Actually, you can set `min={0} max={3}`, and then `marks={0: "8-HR", 1: "1-Day", 2: "3-Day", 3: "7-Day"}`. This will be more elegant.

**Comment by vgoklani** [comment]
thanks
