### ISSUE TITLE
blur is only accessing the first handler

### ISSUE THREAD

**Issue by ivan-navarro-75** [react-component/slider#473]
If using a **Range** component and want to lose the focus we have to lose the focus on each handler not just the first.

```
blur() {
      if (!this.props.disabled) {
        Object.values(this.handlesRefs).forEach(handle => {
          handle.blur()
        })
      }
    }
```

**Comment by zombieJ** [comment]
Since range provides each point can be focused, this behavior  is correct. But I guess it can provide a method called `blur` to blur all the focus.

PS: PR is welcomed : )
