### ISSUE TITLE
onChange only returns 'value'

### ISSUE THREAD

**Issue by alexolivan** [react-component/slider#477]
Hi.
I'm not an expert in using react, but after struggling with my rc-slider based custom components for several days, I think it would be easier if aditional info (not just value) would be included on events such as onChange, along with actual value.

I'm doing well using rc-slider to create an UI to handle ALSA based sound cards... The problem comes as I want to create Components which have more than a single rc-slider... (an stereo control has two sliders, R, L... a surround may have 5,6,7)

As I code the typical stereo sound card control, I need two sliders on my component, so far so well, my component looks good! labels, dB calculations, so far so well! ... but as I move an Slider, and I'm handling the event on a parent's method  (passed to rc-slider in props) , I'm unable know from which child rc-slider did the event came from... so far, I just receive the value.
It would be very useful if, along the updated value, the child rc-slider would send some key/id.

By now, all my multiple slider Sound Card controlers are 'linked' until I get a clue on how to solve this... but maybe this could be helpful to improve this.

Thank you very much.
Best regards.

**Comment by alexolivan** [comment]
not an issue ... I'm a react noob
It can be done by binding child method.
closing

**Comment by yevhensydorov** [comment]
> not an issue ... I'm a react noob
> It can be done by binding child method.
> closing

Could you please tell me the meaning of `binding child method`? I'd really appreciate that. Thanks
