### ISSUE TITLE
Bug with range slider and arrow keys

### ISSUE THREAD

**Issue by dajk** [react-component/slider#503]
Hello,

There is a bug with range slider and arrow keys. After dragging the slider if I press arrow key it would immediately crash.

![bug with range slider](https://user-images.githubusercontent.com/9277302/49790210-f9bbf300-fd2d-11e8-9989-e28656789e49.gif)

Seems that after dragging we lose a track on what index we are handling with. I can try to fix this when I find some time next days.

**Comment by kossel** [comment]
a PR is opened for this https://github.com/react-component/slider/pull/543
