### ISSUE TITLE
Range slider - unable to move second handle after the first handle withou unfocusing

### ISSUE THREAD

**Issue by zerbik** [react-component/slider#504]
Hello,

I have found that when using range slider, handles remain in focused state after moving them. The problem is that i can not move second handle right after moving the first handle. I have to unfocus, either by clicking away or double click on the second handle to move it. 

Any fix for this? Thanks.

![slider-handle-bug](https://user-images.githubusercontent.com/12907151/49802119-4f06fd00-fd4c-11e8-8593-a1215966efbb.gif)

**Comment by muerwre** [comment]
Yep, also faced this, even at the demo: http://react-component.github.io/slider/examples/handle.html I can't move last range slider's second handle by the first try after finished dragging first handle.

**Comment by muerwre** [comment]
Seems to be the problem of the latest release.
8.5.0 doesn't have it.

**Comment by endbay** [comment]
Facing the same issue, after downgrading to v8.5.0 the error is gone.

**Comment by ejdzipi** [comment]
Anyone to fix this please? Thanks

**Comment by muerwre** [comment]
Just roll back to 8.6.3

**Comment by 0c70pu5** [comment]
If you disable the ability to work from the keyboard (pass tabindex as null) then it will work. I added pull request
https://github.com/react-component/slider/pull/512

**Comment by pavelkeyzik** [comment]
> ```js
> <Range
>   tabIndex={[null, null, null]}
> />
> ```

It doesn't work for me. I moved to 8.6.3 version and it's work.
- _Browser:_ Chrome Version 72.0.3626.119 (Official Build) (64-bit)

**Comment by himanshuagrawal5947** [comment]
I also faced the same issue, I fixed it
afterChange(){
 document.querySelector(`.rc-slider-handle-1`).blur();
 document.querySelector(`.rc-slider-handle-2`).blur();
}
Hope it will help.

**Comment by himanshuagrawal5947** [comment]
> Anyone to fix this please? Thanks

afterChange(){
document.querySelector(.rc-slider-handle-1).blur();
document.querySelector(.rc-slider-handle-2).blur();
}
