### ISSUE TITLE
Raise onChange event only when change is done.

### ISSUE THREAD

**Issue by jake-daniels** [react-component/slider#51]
It would be great to add prop like "changeDone" which would be an event raised only when user has finished sliding (on mouseUp). I'm doing some ajax requests on change event, but it is bad for perfomance to call ajax every time the "onChange" event is raised :(

**Comment by just-boris** [comment]
There is already prop for it. Try to use `onAfterChange`.

**Comment by jake-daniels** [comment]
Yes, that's exactly what I wanted. Thank you :) This should be described in component API.
