### ISSUE TITLE
tooltip crashes

### ISSUE THREAD

**Issue by SteefTheBeef** [react-component/slider#52]
Hi! 

This might be more of an issue with your Tooltip/Trigger library...

Anyway, when draging the handle of an Rcslider, line 107 in file lib/Trigger.js in dependency rc-trigger gives me trouble:

![error](https://cloud.githubusercontent.com/assets/1152617/11368097/06818cd2-92b8-11e5-9e9c-4d04ae9d23e6.PNG)

I have removed this line to get it to work for now. But maybe you can take a look at this if you have the time !

I am running React 0.14.0, browserify, babel etc...

Thank you

**Comment by benjycui** [comment]
See: https://github.com/react-component/tooltip/issues/35

**Comment by yiminghe** [comment]
update to react 0.14.3
