### ISSUE TITLE
I have to click twice to drag

### ISSUE THREAD

**Issue by MortenHofft** [react-component/slider#522]
Using Chrome Version 71.0.3578.98 (Official Build) (64-bit) on a mac

Thank you for a nice library.

I believe there is a bug on mac chrome.

Behaviour: click and drag doesn't work. I have to click once. Then subsequent drag work on that handle. If I then want to move the other handle, then i again have to click it first. release. click and drag.

UPDATE: it is the same on Firefox for me
AND the same on Safari. ok. perhaps this isn't a bug but intended behaviour.

**Comment by lippyDesign** [comment]
plus one

**Comment by ZeroCho** [comment]
possible duplicate of #504

**Comment by MortenHofft** [comment]
Looks the same. I missed that.
