### ISSUE TITLE
Empty

### ISSUE THREAD

**Issue by bradynapier** [react-component/slider#53]
It just renders nothing... not sure but this doesnt work.. I see all the div's but they are all invisible.

**Comment by SteefTheBeef** [comment]
Hello, you have to include the styles/css as well.

**Comment by bradynapier** [comment]
Umm not sure what you mean specifically... and no documentation on this?  I tried copying the css file into the css file in my component and that did nothing.

**Comment by just-boris** [comment]
@bradynapier have you tried to copy [this file](https://github.com/react-component/slider/blob/master/assets/index.less) from the sources. It is `less` file, and should be preprocessed before using

**Comment by joemaller** [comment]
Had the same problem, the styles weren't working with Webpack for some reason. Moving the css file and linking it directly into the html finally got the slider to appear.

**Comment by elrrrrrrr** [comment]
```js
import 'antd/lib/index.css'
```

**Comment by just-boris** [comment]
I am using `rc-slider` with Webpack too. Here how I do it:

```js
import 'rc-slider/assets/index.css';
import Slider from 'rc-slider';
```

I have following setup for css loader
```js
{
  test:   /\.css$/,
  loader: 'style-loader!css-loader!postcss-loader' 
}
```

You can see full setup in my project [here](https://github.com/just-boris/revive/blob/master/webpack.config.js)

**Comment by just-boris** [comment]
Also, try to look through your compiled css. Do you see any occurrences of `.rc-slider` in your compiled css?

**Comment by benjycui** [comment]
Close without pride.

**Comment by golfreak923** [comment]
I also had this issue but ultimately ended up using a slightly-different way of importing the styles since we already have complex webpack config thanks to trying to use rc-slider in an ejected create-react-app. Here's what finally worked for us (whether or not this is best practice YMMV):
First add style-loader:
```
yarn add style-loader
```
Import the index.css like such:
```
import '!style-loader!css-loader!rc-slider/assets/index.css'; 
```
