### ISSUE TITLE
Allow to apply mark-active-text to only active mark

### ISSUE THREAD

**Issue by deepaktatineni** [react-component/slider#532]
I would like to know a way to style only active mark text. 

Related issue: https://github.com/react-component/slider/issues/219 but active text is getting applied to all the lower bound marks. 

From marks.js , I believe this line is responsible for applying mark style. Please help me understand how to change the condition if this isn't natively supported. 

`const isActive = (!included && point === upperBound) ||
            (included && point <= upperBound && point >= lowerBound);
    const markClassName = classNames({
      [`${className}-text`]: true,
      [`${className}-text-active`]: isActive,
    });`

Expected:
![image](https://user-images.githubusercontent.com/47742134/53227980-db676180-36a5-11e9-8dcd-8aac751994a8.png)

**Comment by deepaktatineni** [comment]
I have fixed this using 


```javascript
0: {
      style: {
        display: 'none',
        color: '#0071b9',
        left: '0%'
      },
      label: <span/>
    },
    10: {
      style : {
        left : '10%',
        color: 'rgba(0,0,0,0.7)'
      },
      label : <span>10</span>
    },
    35: {
      style : {
        left : '35%',
        color: 'rgba(0,0,0,0.7)'
      },
      label :  <span>35</span>
    },
    65: {
      style: {
        left : '65%',
        color: 'rgba(0,0,0,0.7)'
      },
      label:  <span>65</span>
    } ,
    100: {
      style: {
        color: 'rgba(0,0,0,0.7)',
        left: '85% !important'
      },
      label:  <span>100</span>
    }
  }
```

and by setting the active mark style in render() function.

**Comment by hb0209** [comment]
whats is render() function. Can u please help to explain where did u render this?
