### ISSUE TITLE
changing min/max modifies value

### ISSUE THREAD

**Issue by jamesjjk** [react-component/slider#54]
Great component! But when dynamically changing the min or max prop the value is changed? Surely it should limit to the max or min rather then changing value. Thanks!

**Comment by benjycui** [comment]
Could you provide your use case? I am curious. Why do you change `min` or `max` dynamically.

**Comment by jamesjjk** [comment]
Hi @benjycui. We use the component in a dynamic form, where the validation or values from other inputs affect limit the min/max value of in this case the (or ideally) the slider. For example here is a business requirement, if a user is selecting a value within a finite range which is defined by the users initial (variable input) such as maximum price or stock or units. Then the min/max will be a dependency. I hope this makes sense. Thanks for asking.

**Comment by yiminghe** [comment]
what happens if current value is less than new min or greater than new max ....

**Comment by jamesjjk** [comment]
Unfortunately it effects the value prop of the slider. It should only effect the value when the thing min or max is less then or more then the value respectively. A rule utilised by number pickers is:
Max < Value : Value = Max || Min > Value : Value = Min, rather then selecting a medium value between min and max.

**Comment by benjycui** [comment]
@jamesjjk Forgive my poor English. I am trying to follow you.

Do you mean that:
1. Set `min=0, max=100` and the value is `10`
2. The `min` is set as `50` dynamically
3. The value should be `50`, but it is `10` now.

Right?

**Comment by jamesjjk** [comment]
@benjycui Your english is ok! 
Correct and the above! AND it also sets a value when:
1. Set min=0, max=100 and the value is 20
2. The min is set as 10 dynamically
3. The value should be 20, but it is random.. now.

**Comment by benjycui** [comment]
Fixed in 3.1.4
