### ISSUE TITLE
Is there a way to force max is higher than min in range?

### ISSUE THREAD

**Issue by vovawasabi** [react-component/slider#540]
I would like to force max value is higher than min in range. So, if I move max item to left and it gets to the position of min - don't allow it to go more to left. So, if(maxVal < minVal) {maxVal = minVal}. Is there a way to achieve this? Thanks.

**Comment by kossel** [comment]
use the `pushable` flag or use it as controlled component... I don't think is the place to ask usage question. consider use stackoverlfow

**Comment by vovawasabi** [comment]
Yes, you are right allowCross="false" works. Thanks
