### ISSUE TITLE
Disabled style

### ISSUE THREAD

**Issue by kenzo23312** [react-component/slider#560]
Hi!

I have question how to remove/change style when Slider is disabled ?

There is strange border around track:

<img width="441" alt="Screen Shot 2019-04-17 at 7 21 52 AM" src="https://user-images.githubusercontent.com/19548207/56263021-9712a380-60e1-11e9-9d19-669a0c7eabed.png">

**Comment by Subalee** [comment]
Would be great if you left a solution here.
