### ISSUE TITLE
range component not fluid when setting state in onChange event and using value prop

### ISSUE THREAD

**Issue by premkiran7** [react-component/slider#590]
I find it very hard to set limits using the slider of the range component. Please check out the code sandbox link below

[![Edit quiet-mountain-dr45b](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quiet-mountain-dr45b?fontsize=14)

**Comment by BertelBB** [comment]
You are creating a new Slider on every render.

```
const createSliderWithTooltip = Slider.createSliderWithTooltip;
const Range = createSliderWithTooltip(Slider.Range);
```

Move these two lines outside of the class definition.

**Comment by premkiran7** [comment]
> You are creating a new Slider on every render.
> 
> ```
> const createSliderWithTooltip = Slider.createSliderWithTooltip;
> const Range = createSliderWithTooltip(Slider.Range);
> ```
> 
> Move these two lines outside of the class definition.

Thanks for spotting the error in my code. Really appreciate it
