### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by frontstall** [react-component/slider#613]
Hi guys, and thanks for this awesome component. React has started to warn recently about findDOMNode: Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Handle which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node

**Comment by pethel** [comment]
https://github.com/react-component/slider/pull/627/files

**Comment by mdrahiem** [comment]
Just curious to know why this pull is not merged yet? Coz I can see console error because of `findDOMNode is deprecated in StrictMode`.

**Comment by pethel** [comment]
@mdrahiem 
Hi
It is not going to be merged either because it was a breaking change if the custom handle was used.

**Comment by kruncher** [comment]
I've just added this package to a project and am seeing the same error with very simple usage:
```js
    <Slider
      min={ 0 }
      max={ 100 }
      value={ props.volume }
    />
```
Is the package currently unusable?

**Comment by pethel** [comment]
For now, it is usable but with this annoying warning. In the future, I may not be, but hopefully, the team will fix it until then?

**Comment by jecordjotse** [comment]
Any answer from the team about 'findDOMNode is deprecated in StrictMode' issue?

**Comment by chrisdemetriad** [comment]
I am also waiting for this. What's going on?

**Comment by cseas** [comment]
@zombieJ Any clue about whether this would be resolved? We're facing an issue in our project where rc-slider works fine in production mode but breaks the project's CSS in development mode. There are no errors thrown but I think it might have something to do with this.

**Comment by zombieJ** [comment]
@cseas  what's the issue link? let me check.

**Comment by carolineleger** [comment]
I still see the issue. Any news about it? Can the fix be merged?

**Comment by cseas** [comment]
@zombieJ Sorry, false alarm, it was a problem with our project's bundler. But the "findDOMNode" console warning is still present so the original issue is still relevant.

**Comment by SylannBin** [comment]
https://github.com/react-component/slider/issues/708

**Comment by jacobbroughton** [comment]
Ran into this issue too, rip

**Comment by ShoshaTheTarnegolet** [comment]
react_devtools_backend.js:4045 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Handle which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at Handle (http://localhost:3000/static/js/bundle.js:17552:90)
    at Trigger (http://localhost:3000/static/js/bundle.js:20722:92)
    at Tooltip (http://localhost:3000/static/js/bundle.js:19814:32)
    
    
    **is there any solution here?**

**Comment by AntoineFacq** [comment]
RIP

**Comment by jamesremuscat** [comment]
v10.0.0 of this library (released April 2022) has removed the call to `findDOMNode` that was triggering that warning.
