### ISSUE TITLE
feature: Provide 'Always show tooltip' option

### ISSUE THREAD

**Issue by drewproud** [react-component/slider#62]
It's a nice looking tooltip - it'd be great to have the option to always show it.

**Comment by benjycui** [comment]
IMHO, this feature will break the current design. I am not going to implement it, until it is proved to be a useful use case.

**Comment by drewproud** [comment]
Maybe I missed testing some use cases, but I created a working fork for use in my project that implements this functionality. It might not be necessary given #63, but I created a PR anyway.

**Comment by benjycui** [comment]
I am sorry to close. If there are more evidences which can prove this feature is necessary, just re-open it.

**Comment by Yuripetusko** [comment]
Useful case is for user to always know current values. Would be nice for this component to be flexible enough to allow such control.

**Comment by benjycui** [comment]
How about something like this: http://ant.design/components/slider/#demo-input-number . Just show value in an input / a label, if you want to show value all the time.

IMO, Tooltip is just used to show *more information* when users are really interested in, e.g. hover means I care about it.

**Comment by minimaldesign** [comment]
I can't show the designs for now (confidential) but I got a design where the slider's handle needs to have a persistent representation of the current selected value. I doesn't look anything like your tooltip but that's easily editable via CSS.

Everything works beautifully, besides for the fact that nothing shows when you first load the page.

I understand that if you only think about it as a tooltip, it makes little sense to show all the time, but if you think about it instead as a configurable UI element that show the currently selected value and follows the slider handle, then the option to show it all the time makes sense.

Thank you for such a great plug in! But I'm going to have to look at the fork mentioned above in order to use it as I need it to work, which is a bit of a bummer…

**Comment by minimaldesign** [comment]
@drewproud I just wanted to let you know that after starting to do that myself, I realized that you had already done it… And I wanted to thank you for your work (as well as @benjycui of course!)

I couldn't find anyway to contact you and your site is not loading for me right now so… Thanks!

I hope you keep your fork active, it's a really useful feature addition, and in case anyone stumbles upon this post, I thought I make it easy for them to find the fork with the "alway show tooltip" feature addition. It's right there: https://www.npmjs.com/package/rc-slider-fork

**Comment by drewproud** [comment]
@minimaldesign glad to hear it's helpful for you folks! I'm happy to make you a maintainer on the fork if you'd like.

**Comment by lauterry** [comment]
Hello

Thank for this great rc-slider

I also want the ability to always show the tooltip to display current values to user.

Would be great to have a props to enable it.

**Comment by benjycui** [comment]
Try http://react-component.github.io/slider/examples/custom-handles.html

**Comment by lauterry** [comment]
@benjycui 

Ho great !

**Comment by siddhant91** [comment]
custom-handles.html is not present in example anymore. I would like to show the tooltip always for createSliderWithTooltip(Slider.Range); 

Is there a way to do the custom implementation of this

**Comment by benjycui** [comment]
Demo about how to customize handle: http://react-component.github.io/slider/examples/handle.html

**Comment by hellofantastic** [comment]
That last example only shows tooltips on hover. Where is example to show tooltip always?

**Comment by ihteandr** [comment]
just add this styles
.rc-slider-tooltip-hidden{
  display: inline-block!important;
}
in you global scope

**Comment by mikdatdogru** [comment]
this is working example. actually not exactly :)
https://codesandbox.io/s/zn908z99yx

but if something expand down on the component, the tooltip stays up. When I mouse over it, Tooltip positions are update.
