### ISSUE TITLE
feature: customizable handle

### ISSUE THREAD

**Issue by benjycui** [react-component/slider#63]
Lots of issues are about making tooltip more configurable.

1. #62 wants to show tooltip anytime.
1. #32 wants to format tooltip's content, and disabled tooltip.

rc-slider has become a fattie. And it seems that all of rc-tooltip's APIs are going to be exposed.

How about @just-boris ' suggestion? https://github.com/react-component/slider/issues/32#issuecomment-156748583

If rc-slider supported customizable handle, you could wrap handle with any kind of tooltip. But the drawback is that it is not as convenient as `tipFormatter` or `tipVisibility`.

**Comment by just-boris** [comment]
Well, I will create a conception and example how it would look like at the next week

**Comment by nilssolanki** [comment]
I'm curious, has this already been implemented?

**Comment by benjycui** [comment]
Nope, I am not sure if this feature is necessary. Maybe we can try another way to solve those problems.

**Comment by nilssolanki** [comment]
Do you have any workarounds at the moment?

**Comment by benjycui** [comment]
I am busy with [ant-design](https://github.com/ant-design/ant-design) and [bisheng](https://github.com/benjycui/bisheng) recently. Maybe June?

You could describe your requirement(and why do you need this feature) in this issue. I will try to provide a solution.

**Comment by nilssolanki** [comment]
As a matter of fact, the PR (https://github.com/react-component/slider/pull/102) looks like it addresses exactly what I need. Thank you for taking the time to look at this.
