### ISSUE TITLE
Dots and Marks simultaneously cause duplicated keys warning from react  

### ISSUE THREAD

**Issue by alexdrel** [react-component/slider#64]
Slider with dots={true} and marks that match some of dots values cause duplicated keys warning:
```Warning: flattenChildren(...): Encountered two children with the same key, `.$5`. ```

The combination is valid otherwise if one wants mark on every step but just a few of them labelled.
``` <RcSlider min={5} max={50} step={5}  defaultValue={10}
            dots={true} marks={{5: '5',10: '10',25: '25', 50: '50'}} />```

**Comment by benjycui** [comment]
Try 3.3.1
