### ISSUE TITLE
feature: Simplify `marks` common case

### ISSUE THREAD

**Issue by alexdrel** [react-component/slider#65]
The requirement of object syntax for ```marks``` property is burdensome. See a real example below
```
    const marks = {
      5: '5',
      10: '10',
      25: '25',
      50: '50',
    };
```
I propose to enable additional type variants for marks:  ```boolean | numer[] | object```
So it will be ```marks={true}``` to trigger marks on every dots, ```marks={[ 5, 10, 25, 50]}``` to mark specified values, or as it is right now for the labels to differ from actual values. 

Also I suggest not to use marks for localization purposes but instead generalize ```tipFormatter``` to ```labelFormatter``` to be used for both labels and tooltips or add additional ```markFormatter``` prop.

**Comment by just-boris** [comment]
+1. I am using arrays as marks in my project. 
Now I am getting warning, but it is okay to treat that value as valid.

**Comment by benjycui** [comment]
Let me think twice.

**Comment by benjycui** [comment]
`marks: Array` is reserved for backward compatibility in [`antd.Slider`](http://ant.design/components/slider/)(It's based on rc-slider). So, try this helper to convert array into `marks`:

```js
function toMarks(arr) {
  var marks = {};
  arr.forEach(function(item) {
    marks[item] = item.toString();
  });
  return marks;
}
```

And, `marks` is not just for localization. It's for those use cases: 

1. http://ant.design/components/slider/#demo-mark
1. http://ant.design/spec/colors#色彩换算工具

It's difficult to keep rc-slider simple and useful. I am sorry to reject your feature request.
