### ISSUE TITLE
In Range and Slider step props type should allow null with --strictNullChecks 

### ISSUE THREAD

**Issue by tlehtimaki** [react-component/slider#652]
The components `src/Slider.tsx` and `src/Range.tsx` define `step` prop as `undefined or number`. It should also include `null` as it is used in Range:
https://github.com/react-component/slider/blob/b5a337e71c6678f2d24e018509379a8e6f1d0518/src/Range.tsx#L318-L333

So I would suggest changing the type for step prop to be `step?: number | null`

Related to changes that came in this pull request https://github.com/react-component/slider/pull/641

**Comment by gerdneuman** [comment]
This should be fixed by #757 and can be closed. FYI @afc163

**Comment by jnachtigall** [comment]
Since #757 has been merged, this can be closed. fyi @afc163
