### ISSUE TITLE
Using startPoint sets the first dots as active

### ISSUE THREAD

**Issue by mkantz84** [react-component/slider#682]
When using startPoint, all the marks until the value is set to active.

```
      <Slider
          marks={{ 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7 }}
          step={1}
          min={1}
          max={7}
          value={6}
          startPoint={3}
      />
```

![Capture](https://user-images.githubusercontent.com/22270407/92627519-25d62080-f2d4-11ea-955b-53651e7c4293.JPG)

version: 9.3.1
env: chrome

**Comment by mkantz84** [comment]
#683

**Comment by ktaras** [comment]
This issue is really annoying. So weird nobody merged the fix yet.

**Comment by js2me** [comment]
@afc163 Hello, this problem caused in 10.0.0 version.   

I revert rc-slider to 9.7.5 and this problem has been fixed
