### ISSUE TITLE
Property 'railStyle' does not exist on type...

### ISSUE THREAD

**Issue by dnlfrst** [react-component/slider#686]
Opposed to [the documentation](https://github.com/react-component/slider#common-api), it is no longer possible to specify `railStyle` for `Range`s and `Slider`s beginning with version [9.5.0](https://www.npmjs.com/package/rc-slider/v/9.5.0). This problem does not occur with version [9.4.1](https://www.npmjs.com/package/rc-slider/v/9.4.1). See [this MWE](https://codesandbox.io/s/rc-slider-issue-686-pzmp5) for an illustration of the issue.

**Comment by Kermit-Xuan** [comment]
@dnlfrst Fixed in `rc-slider@9.5.1`
