### ISSUE TITLE
Tooltip does not follow handle

### ISSUE THREAD

**Issue by duhaime** [react-component/slider#693]
In the current [demos](http://react-component.github.io/slider/?path=/story/rc-slider--slider) the tooltips do not follow the handle movement--dragging the handle does not drag the tooltip:
  
![handle](https://user-images.githubusercontent.com/4801116/95146605-4024e200-074c-11eb-9214-e696de24e01e.png)

In earlier versions of this repo, the tooltips did follow handle movement--have the default settings changed? Is there a way to ensure the tooltips stay with the handles?

**Comment by Kermit-Xuan** [comment]
@duhaime Which version is correct?

**Comment by duhaime** [comment]
I last used this project on `^8.5.0`, and I know the tooltip was great then, but that's likely not much help. 

I wish I had time to help figure out this hitch but I'm under a deadline so I switched to MaterialUI. Long live `rc-slider`!
