### ISSUE TITLE
Not enough tutorials or guide!

### ISSUE THREAD

**Issue by 7axiomsOfEuclid** [react-component/slider#719]
Quick question: I am going to make a slider with steps, marks below, and tooltips also.
This library seems much popular but I see the lack of document guidance. 
Your online examples are not well documented and I am also unable to find the sourcecode.

**Comment by 7axiomsOfEuclid** [comment]
What a fucking documentation! 
I am unable to scroll up or down the sourcecode.
![image](https://user-images.githubusercontent.com/19179511/101046130-22e18800-35c4-11eb-9adb-e41863016c04.png)

**Comment by 7axiomsOfEuclid** [comment]
Remove the source section from the online demo. Its useless.

**Comment by xrkffgg** [comment]
OK, It will be fixed today.
