### ISSUE TITLE
How can I restyle the sliders using javascript? 

### ISSUE THREAD

**Issue by lukephills** [react-component/slider#73]
I've seen the css file but I'd like to be able to compute my styles using javascript. What would you suggest is the best way to do this?

Thanks in advance!

**Comment by benjycui** [comment]
You can compute and set `className` dynamically. It is better than inline style.

**Comment by just-boris** [comment]
@lukephills Hello!
What issue do you want to solve?

**Comment by benjycui** [comment]
No more information, close without proud.
