### ISSUE TITLE
How to use a custom svg as the handle

### ISSUE THREAD

**Issue by cseas** [react-component/slider#736]
I'm trying to use a custom svg icon as the handle for my slider but the svg doesn't appear at all.

Here's what I tried:

```tsx
import PauseIcon from "./pause.svg";
...
      <Slider
        handleStyle={{
          borderColor: "white",
          height: 32,
          width: 32,
          marginTop: -13,
          boxShadow: "0 2px 6px 0 rgba(0, 0, 0, 0.28)",
          background: PauseIcon,
        }}
      />
```

**Comment by cseas** [comment]
Figured it out from discussion in #449

Here's how:

```tsx
import { ReactComponent as PauseIcon } from "./pause.svg";
...
      <Slider
        handleStyle={{
          borderColor: "white",
          height: 32,
          width: 32,
          marginTop: -13,
          boxShadow: "0 2px 6px 0 rgba(0, 0, 0, 0.28)",
        }}
        handle={(handleProps: any) => {
          return (
            <Handle {...handleProps}>
                <PauseIcon width="10px" />
            </Handle>
          );
        }}
      />
```

**Comment by AlfredMadere** [comment]
This does not work in 2023. Handle is not exported from "rc-slider" and the handle prop does not exist on the Slider component. Can this still be achieved?

**Comment by UmbraCi** [comment]
> This does not work in 2023. Handle is not exported from "rc-slider" and the handle prop does not exist on the Slider component. Can this still be achieved?

use V9 version，V10 has be refactored. some mistake should update

**Comment by yoyo837** [comment]
See https://github.com/react-component/slider/pull/963#discussion_r1423618617
