### ISSUE TITLE
draggableTrack moves slower/faster than the mouse when `max` is significantly greater/less than the width of the Range

### ISSUE THREAD

**Issue by bjornuppeke** [react-component/slider#740]
When `max` is significantly greater or less than the width of the Range the draggable track does not behave as expected. It does not follow the mouse. I expect it to follow the mouse, just like when dragging the handles.

https://codepen.io/bjornuppeke/pen/JjRzxdE

**Comment by yann-combarnous** [comment]
@afc163 , any chance a release can be made to publish this fix?
