### ISSUE TITLE
Connecting upper and lower bounds only changes upper bound

### ISSUE THREAD

**Issue by ingvily** [react-component/slider#75]
An attempt to connect the slider's upper and lower bounds, we rerender a `<Slider range allowCross={ false } value={[ a, b ]} />` with both lower and upper bounds changed the same amount, resulting in only the upper bound changing when the lower bound is reduced.

This seems to be because the [`allowCross`-check](https://github.com/react-component/slider/blob/0512ee6ee035ca317d363e3551620a5ee485d4c2/src/Slider.jsx#L269-L271) handling the change of the lower bound hits the `allowCross`-check for the upper bound passing the lower bound. As `handle` defaults to `upperBound` the check concludes that the new value for the lower bound should be the previous lower bound.

This results in only our upper bound moving when we change them both.

**Comment by benjycui** [comment]
Sorry for the late response.

Actually, I am not sure what kind of problem you met, could you provide an online demo and some steps to re-produce the problem?

**Comment by benjycui** [comment]
Close for no enough information.
