### ISSUE TITLE
Pushable with Typescript

### ISSUE THREAD

**Issue by cxii112** [react-component/slider#755]
I tried to use pushable range. When I tried to set `pushable ` to number I get:

> Type "number" is not assignable to parameter of type "boolean | undefined"

Same thing when I tried use `RangeProps`. So I changed `pushable?: boolean;` in `Range.d.ts` to `pushable?: boolean | number;` and it works fine.
Am I doing right (I'm new to development, sorry)?

I'm using:
Typescript 4.1.2
React 17.0.1
rc-slider 9.7.1

**Comment by TomlDev** [comment]
Bump 👍🏽

**Comment by akash10agarwal** [comment]
@cxii112 @TomlDev pls point to the ver which contains this fix?

**Comment by cxii112** [comment]
@akash10agarwal i have tested on `^9.7.5` rn. it works fine.

**Comment by akash10agarwal** [comment]
thanks worked. still seems to have lots of open issues as can be seen here in the Issues tab for this Github prj. is there a stable ver?
