### ISSUE TITLE
too many request are send to server.

### ISSUE THREAD

**Issue by FilipMessa** [react-component/slider#79]
I use slider to request on server, but when user change value it send to many request, i know i can use onAfterChange but i want use OnChange also but not so often. I'm trying to think of a solution, but maybe you do once someone has came up

**Comment by just-boris** [comment]
If you want to receive less change events, you can debounce your change handler. Something like this:

```js
const changeHandler = debounce(() => doYourAction());
//...
<Slider onAfterChange={changeHandler}>
```

You can find the debounce function in [underscore.js](http://underscorejs.org/#debounce) or find some standalone implementations or write your own.
