### ISSUE TITLE
Disable keyboard events

### ISSUE THREAD

**Issue by Tenpi** [react-component/slider#799]
Hello, the sliders have some default keyboard behaviors that I _don't_ want, can you please add an option to disable them?

For example, pressing "ArrowRight" or "ArrowUp" increments the value up, and pressing "ArrowLeft" or "ArrowDown" decrements the value. I have two sliders such that I want "ArrowRight/ArrowLeft" to only affect one and "ArrowUp/ArrowDown" to affect the other. However, when the slider is focused the default behaviors override my own.

**Comment by frankkopp** [comment]
> Hello, the sliders have some default keyboard behaviors that I _don't_ want, can you please add an option to disable them?
> 
> For example, pressing "ArrowRight" or "ArrowUp" increments the value up, and pressing "ArrowLeft" or "ArrowDown" decrements the value. I have two sliders such that I want "ArrowRight/ArrowLeft" to only affect one and "ArrowUp/ArrowDown" to affect the other. However, when the slider is focused the default behaviors override my own.

Did you find a solution?
