### ISSUE TITLE
new html structure

### ISSUE THREAD

**Issue by yiminghe** [react-component/slider#80]
track, mark and step are separated now, it is better to grouped them into step

```
<div>
<div step/track  style={{borderBottom: 1px solid}}>
<div circle></div>
<div mark></div>
</div>
<div step>
<div circle></div>
<div mark></div>
</div>
</div>
```

http://react-component.github.io/steps/examples/simple.html

**Comment by benjycui** [comment]
Close now, for rc-steps will not be deprecated.
