### ISSUE TITLE
"Module '"rc-slider"' has no exported member 'Range'."

### ISSUE THREAD

**Issue by alicerocheman** [react-component/slider#825]
`import { Range } from 'rc-slider';`
=> error: "Module '"rc-slider"' has no exported member 'Range'."

after upgrading to "rc-slider": "^10.0.0-alpha.6"

doc still says you can import Range from rc-slider.

forced to rollback.

**Comment by Ashvin-Pal** [comment]
I am using version > "rc-slider": "^10.0.0-alpha.6"

I think the documentation has not been updated. To use the range feature in version "^10.0.0-alpha.6" 

You have to do this > 

![image](https://user-images.githubusercontent.com/56989405/161039513-e49161af-1aa4-4a25-91bd-45bc89a86096.png)

**Comment by TimoWestland** [comment]
This seems to work, however now the `onChange` type is `number | number[]` instead of `number[]` which it should always be for a range slider. Is there a way to tell typescript that the value of onChange will be of type `number`? I see in the `index.d.ts` type that `SliderProps` has a generic called `ValueType`, but I'm not suer how to pass that from JSX.

**Comment by fvoordeckers** [comment]
`value`, `defaultValue`, `onChange`, `onBeforeChange`, `onAfterChange` are all using `ValueType = number | number[]` which is incorrect. The type of `ValueType` should be depending on the value of the `range` prop.

Something like:
```range extends true ? number[] : number```

**Comment by fvoordeckers** [comment]
Same for all the range-only properties, which are now optional. These properties should be `undefined` in the case range is not true and optional (or not) when it is a range selector. Otherwise the typings allow setting range specific properties on a simple slider.

**Comment by hilo2120** [comment]
onChange still has error. Any idea on how to type it?

`Type 'Dispatch<SetStateAction<number[]>>' is not assignable to type '(value: number | number[]) => void'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'number | number[]' is not assignable to type 'SetStateAction<number[]>'.
      Type 'number' is not assignable to type 'SetStateAction<number[]>'.ts(2322)`

**Comment by Ashvin-Pal** [comment]
I solved it on my side by just casting the type 

```
const handleChange = (_input: number | number[]) => {
    /* if you're using range */
    const input = _input as number[] 

    /* if you're only using the slider  */
    const input = _input as number
}
```

**Comment by fvoordeckers** [comment]
> onChange still has error. Any idea on how to type it?
> 
> `Type 'Dispatch<SetStateAction<number[]>>' is not assignable to type '(value: number | number[]) => void'. Types of parameters 'value' and 'value' are incompatible. Type 'number | number[]' is not assignable to type 'SetStateAction<number[]>'. Type 'number' is not assignable to type 'SetStateAction<number[]>'.ts(2322)`

@hilo2120  Looks like you are passing the state set action as an onchange event handler. You need to write a handleChange function that will call the state setter.

> I solved it on my side by just casting the type
> 
> ```
> const handleChange = (_input: number | number[]) => {
>     /* if you're using range */
>     const input = _input as number[] 
> 
>     /* if you're only using the slider  */
>     const input = _input as number
> }
> ```

@Ashvin-Pal would make Typescript useless because we're still guessing the type. You could also check if the input is an Array and depend your typings on that result. But both are workarounds and should be fixed by a change in the typings based on the `range` param.

**Comment by Ashvin-Pal** [comment]
@fvoordeckers yeap I had no choice but to use a workaround for now.

**Comment by guillaumeBOSSIS** [comment]
@Ashvin-Pal or someone else. Hello, I can't figure how to display the tooltip in version 10. Any idea ?

**Comment by Ashvin-Pal** [comment]
> @Ashvin-Pal or someone else. Hello, I can't figure how to display the tooltip in version 10. Any idea ?

You can check out the example over here > https://codesandbox.io/s/lzsr20?file=/App.tsx

**Comment by CBurrows87** [comment]
@Ashvin-Pal Hi, I am having trouble with getting the tooltips working in v 10 using typescript. I found you example which seems like it would have fixed the issue, but it's currently not working and complaining about tipprops? Any idea what would be needed to get it working again?

**Comment by schemata-issimo** [comment]
Attempted to upgrade but hit the same snag, agreed changing ValueType to something like fvoordeckers said would change the issue:

range extends true ? number[] : number

**Comment by Shamimrahman** [comment]
better use npm i rc-slider@9.6.5

**Comment by dotjsNet** [comment]
You must do imports like this 

const Slider = require('rc-slider');
const createSliderWithTooltip = Slider.createSliderWithTooltip;
const Range = createSliderWithTooltip(Slider.Range);

After that Range can accept the props.

**Comment by wwwouter** [comment]
I tried this with the latest version (10.1.0) and this does not seem to work:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/997207/203778641-540b1ede-b860-426e-a4d5-d5ad5a7b8e10.png">


`Property 'createSliderWithTooltip' does not exist on type 'ForwardRefExoticComponent<SliderProps<number | number[]> & RefAttributes<SliderRef>>'.ts(2339)`

`Property 'Range' does not exist on type 'ForwardRefExoticComponent<SliderProps<number | number[]> & RefAttributes<SliderRef>>'.ts(2339)`

Searching for `createSliderWithTooltip` (https://github.com/react-component/slider/search?q=createSliderWithTooltip) results in two hits in code, both are commented out.

**Comment by dotjsNet** [comment]
> I tried this with the latest version (10.1.0) and this does not seem to work:
> 
> <img alt="image" width="475" src="https://user-images.githubusercontent.com/997207/203778641-540b1ede-b860-426e-a4d5-d5ad5a7b8e10.png">
> 
> `Property 'createSliderWithTooltip' does not exist on type 'ForwardRefExoticComponent<SliderProps<number | number[]> & RefAttributes<SliderRef>>'.ts(2339)`
> 
> `Property 'Range' does not exist on type 'ForwardRefExoticComponent<SliderProps<number | number[]> & RefAttributes<SliderRef>>'.ts(2339)`
> 
> Searching for `createSliderWithTooltip` (https://github.com/react-component/slider/search?q=createSliderWithTooltip) results in two hits in code, both are commented out.

Check out this demo with source code http://react-component.github.io/slider/?path=/story/rc-slider--handle

**Comment by wwwouter** [comment]
@dotjsNet Have you tried this outside of the https://github.com/react-component/slider repository with the latest version of `rc-slider`?

If I ignore the typing by casting `Slider` to `any` and log `createSliderWithTooltip`, I get `undefined` back.

```
import Slider from 'rc-slider';
const { createSliderWithTooltip } = Slider as any;
console.log('createSliderWithTooltip', createSliderWithTooltip);
```

<img width="395" alt="image" src="https://user-images.githubusercontent.com/997207/203922359-da5d3240-d910-4cb6-9bd5-c9714789f82b.png">

I suspect the code on http://react-component.github.io/slider/?path=/story/rc-slider--handle runs <v10.

**Comment by szamanr** [comment]
so a new non-beta major release introduced breaking changes and yet the documentation has not been updated, and it looks like the vast majority of PRs merged in this repo are not even reviewed. i'm sorry but this screams "shitty library". i'm out.

**Comment by code2be** [comment]
PR made
https://github.com/react-component/slider/pull/867

**Comment by princefishthrower** [comment]
@szamanr - have you found a decent alternative range slider?

**Comment by szamanr** [comment]
> @szamanr - have you found a decent alternative range slider?

@princefishthrower no, i've pinned the dependency to `9.2.4`. i left a note to look into `react-compound-slider` in the future.

**Comment by princefishthrower** [comment]
Found yet another slider component: https://github.com/n3r4zzurr0/react-range-slider-input but this one doesn't have types. Just found this nice blog post, at this point I'll accept a completely custom one, tired of searching for a library for such simple functionality: https://benhoneywill.com/building-a-range-slider-component-in-react/

**Comment by alissaVrk** [comment]
it seems that the examples are updated to the new version see [/demo/handle](https://slider-react-component.vercel.app/demo/handle)
just the README and changelog is outdated

**Comment by alissaVrk** [comment]
@TimoWestland about `onChange` type
the `SliderProps` is generic you can pass the value type.
for range it will be `SliderProps<number[]>`

**Comment by diniththarushka** [comment]
> I tried this with the latest version (10.1.0) and this does not seem to work:
> 
> <img alt="image" width="475" src="https://user-images.githubusercontent.com/997207/203778641-540b1ede-b860-426e-a4d5-d5ad5a7b8e10.png">
> 
> `Property 'createSliderWithTooltip' does not exist on type 'ForwardRefExoticComponent<SliderProps<number | number[]> & RefAttributes<SliderRef>>'.ts(2339)`
> 
> `Property 'Range' does not exist on type 'ForwardRefExoticComponent<SliderProps<number | number[]> & RefAttributes<SliderRef>>'.ts(2339)`
> 
> Searching for `createSliderWithTooltip` (https://github.com/react-component/slider/search?q=createSliderWithTooltip) results in two hits in code, both are commented out.

Probably you have found an alternative way to achieve the requirement, posting this in case someone is stuck on this...

**Comment by wwwouter** [comment]
FYI, like others in other issues, I finally chose another library last week.

I looked at a few different options and Mantine was a good match for us.

```
import { RangeSlider } from '@mantine/core';

...

 <RangeSlider
                            min={0}
                            max={this.state.videoDuration}
                            minRange={0}
                            value={[this.state.fragmentRangeStart ?? 0, this.state.fragmentRangeEnd ?? 0]}
                            label={(value) => formatTimestamp(value)}
                            labelAlwaysOn
                            onChange={(value) => void this.onFragmentRangeChanged(value)}
                        />

```

**Comment by szamanr** [comment]
:point_up: mantine looks interesting, note to self to have a look.

https://mantine.dev/

**Comment by BBeast131** [comment]
how to use range with rc-slider. would anyone like to let me know ?

**Comment by shyamvadaliya12** [comment]
This is my code

```
import React, { useState } from 'react';
import Slider from 'rc-slider';
import 'rc-slider/assets/index.css';
import "./style.css";
import sliderImg from "@/assets/images/png/slider_texture.png";

// TimeSlider.jsx
const TimeSlider = () => {
    const [availableRange, setAvailableRange] = useState([0, 1440]);
    const [awayRange, setAwayRange] = useState([480, 1020]);

    const minutesToTime = (mins) => {
        const hours = Math.floor(mins / 60);
        const minutes = mins % 60;
        const ampm = hours >= 12 ? 'PM' : 'AM';
        const formattedHour = hours % 12 || 12;
        return `${formattedHour}${ampm}`;
    };
    const trackStyle = [{
        backgroundColor: "#d6a94a",
        backgroundImage: `url(${sliderImg})`,
        height: "22px"
    }];

    const sliderChange = (data) => {
        console.log("data", data)
        setAwayRange(data)
    }

    
    return (
        <div>
            <h3>AVAILABLE</h3>
            <Slider range 
                min={availableRange[0]}
                max={availableRange[1]}
                step={60}
                value={awayRange}
                // defaultValue={[3, 10]} 
                onChange={(data) => sliderChange(data)}
                trackStyle={trackStyle}
            />
            <br></br>
            <br></br>
            <p>{minutesToTime(availableRange[0])} - {minutesToTime(availableRange[1])}</p>
        </div>
    );
};

export default TimeSlider;


```

How to set a tooltip in above code.
