### ISSUE TITLE
SCSS version of the slider styles

### ISSUE THREAD

**Issue by benhowes** [react-component/slider#84]
Hi All,

Thanks for the module - I've just gone through and converted the styles to Sass for inclusion in a Sass based project I'm working on. I've popped the [results in a gist]( https://gist.github.com/benhowes/762dbaa2bf3e5795f4a4). Not sure if the project is interested in this, however Sass is tending to win over less these days so I thought it may be handy.

Cheers

**Comment by benjycui** [comment]
Keep it simple.

Less is not the best, but enough.

**Comment by just-boris** [comment]
Hello! I think that I should elaborate more about this. 

It would be very hard to maintain two versions of styles. That means we should make every change in both versions and test it then. it is a lot of work and we can't handle it.

@benhowes Also I understand your concern. It is good to have style sources and override variables to create a custom theme for the component.

You can look for some way to convert LESS to SASS on-the-fly. Take a look on https://github.com/ekryski/less2sass, or how Bootstrap maintains [their own converter](https://github.com/twbs/bootstrap-sass/blob/master/tasks/converter/less_conversion.rb) for SASS version.

Finally, if you don't want to change variables, you can include output css into your SASS file and it will work.

**Comment by benhowes** [comment]
Thanks @just-boris! I've got it all sorted in my case using the SASS version I made, which is `:global`'d in  my sass/webpack loader.

Not too fussed either way, I just posted it on the off-chance that it would help someone else in the future.
