### ISSUE TITLE
The slider handle immediately gets the focus

### ISSUE THREAD

**Issue by mbraak** [react-component/slider#841]
In my test setup the slider handle immediately gets the focus. This is an issue, because another component is supposed to get the autofocus.

* My test setup is quite simple: `<Slider />`
* This code seems to cause the focus: https://github.com/react-component/slider/blob/59240058ff93a1313868ed8b9c0a1410792731bb/src/Slider.tsx#L401
* Tested with version 10.0.1

**Comment by fendermany** [comment]
Same problem
