### ISSUE TITLE
Reverse min/max of slider

### ISSUE THREAD

**Issue by brotzky** [react-component/slider#86]
Hi,

I have been using this slider in a couple projects and was wondering if there is any easy configuration to change the slider direction from min --> max to max --> min. 

Example values:
|100--------------50-------------0|

Essentially the max value is to the left of the slider and the min is to the right.

**Comment by benjycui** [comment]
`tipFormatter={(val) => 100 - val}` will make Slider looks like max -> min.

**Comment by brotzky** [comment]
Thanks a lot!
