### ISSUE TITLE
highlight difference between two values

### ISSUE THREAD

**Issue by nidu** [react-component/slider#87]
Hello,

I'd like to highlight difference between initial (default) value and current value (change track colour).
Is there any way to do that, e.g. specify different style for specific track ranges, or use `range` with one handle disabled?

Thanks.

**Comment by just-boris** [comment]
What do you mean? If `value` and `defaultValue` are not equal, you want to have a different view for slider?

You can do it in a wrapper

```js
class SliderChanged extends React.Component {

  onSliderChange(value) {
    this.setState({value: value});
  }

  render() {
    return (<div className={isEqual(this.props.defaultValue, this.state.value) ? 'slider-pristine' : 'slider-changed'}>
      <Slider range defaultValue={this.props.defaultValue} onChange={this.onSliderChange} />
    </div>);
  }
}
```

You can do it without any change in the library

**Comment by nidu** [comment]
@just-boris not the whole slider, but only specific region from initial value to current value. The rest of the slider should remain blue as is. Unfortunately i can't post an image.
For example on the first example here http://react-component.github.io/slider/examples/marks.html imagine default value is 26 and current is 37. So region from -10 to 26 is normal and from 26 to 37 is orange e.g.

**Comment by just-boris** [comment]
Well, I got it. You can't do it without changes in the component, but it will be so big and complicated.

Let's see, what other team members think.

**Comment by benjycui** [comment]
So, what is your use case? And the advantage.

**Comment by nidu** [comment]
@benjycui Excuse me, I don't get the question. Use case is following: we have a series of adjusted values and series of dependent values. When you correct adjusted values and hit "Calculate" button, values are fixed and dependent values are recalculated. I'd like to highlight this difference of adjusted values between two hits of "Calculate" button. Sorry if i didn't get the question right.

**Comment by benjycui** [comment]
Forgive me, I am not a native speaker.

Could you find some implementations of Slider (e.g. based on jQuery or Angular ...) which has this feature? We need to evaluate this feature, and it will be easier if there are some example.

**Comment by nidu** [comment]
@benjycui I have a hard time searching for a slider like this. I'll try to make a naive implementation (demo) maybe instead.

**Comment by nidu** [comment]
@benjycui Hello again, here's my naive implementation - https://github.com/nidu/slider. In value-change.html example.

**Comment by benjycui** [comment]
We thought that is weirdo, and it is not common use case. Maybe you could just fork and publish your own Slider? Sorry.

![image](https://cloud.githubusercontent.com/assets/3580607/14662992/4dc3d8a2-06ee-11e6-8173-49757d6b78f4.png)

**Comment by nidu** [comment]
@benjycui Agree, i guess that would be the best option. Thanks!
