### ISSUE TITLE
Is it possible to distribute marks with offset along the line, not centered evenly?

### ISSUE THREAD

**Issue by wzup** [react-component/slider#90]
I want to implement the following time slider. Its values are minutes from 0 to 30 (actually in seconds from 0 to 1800). Please pay attention that first 15 minutes occupy about 70% of the slider length. And other 15 minutes occupy the remaining 30% of the length of the slider:

![slidercropped](https://cloud.githubusercontent.com/assets/3880497/14517494/b5435f50-0240-11e6-926b-ec0066fb027b.jpg)

Is it possible to implement it with your plugin? And so that the handle would still move smoothly.

Because it looks quite ugly with default distribution, when marks are distributed evenly:

![slider 2016-04-14 12 58 33](https://cloud.githubusercontent.com/assets/3880497/14517508/de708d58-0240-11e6-83f1-f0933c828718.png)

**Comment by wzup** [comment]
Pretty useless stuff the plugin is if it is not possible to customize steps and marks distribution other than evenly. It's not a big deal to distribute them evenly.

**Comment by benjycui** [comment]
http://react-component.github.io/slider/examples/marks.html

```js
const marks = {
  0: 1,
  ...
  14: 15,
  15: 17,
  16: 20,  
};
```

**Comment by wzup** [comment]
@benjycui 

Nope. It doesn't solve the distribution issue. It only offsets marks along the slider. But 15 should be where the red line is:

![slider google chrome 2016-04-15 17 05 36](https://cloud.githubusercontent.com/assets/3880497/14556879/fcd1290a-032c-11e6-8ee0-7f7729bf83bf.png)

**Comment by benjycui** [comment]
Just adjust my sample code.

**Comment by wzup** [comment]
It seems I eventually could set it up properly.
Now, is it possible to change `step` option dynamically?
My current props are shown below. The issue is that after 15 the `step` changes. It is no longer `.25`. Is it possible to change it dynamically?

![slider - google chrome 2016-04-16 00 14 10](https://cloud.githubusercontent.com/assets/3880497/14567873/c779aea8-0368-11e6-9b28-03772af4b37f.png)


```
                    <Rcslider
                        min={0}
                        max={21}
                        marks={marks}
                        className="slider"
                        step={.25}
                        tipFormatter={getTime}
                        onChange={this.sliderChange}
                    />
```

**Comment by benjycui** [comment]
Nope, just use map, or a function to map Slider's value to time.

```js
{
  ...
  16: 17,
  17: 20,
  ...
}
```

I know it is inconvenient, but your case is not common use case..
