### ISSUE TITLE
How to get current slider value?

### ISSUE THREAD

**Issue by wzup** [react-component/slider#93]
How to get current slider value?
```
currentValue = document.getElementById( WHAT_ID? )
```

Or is there a special method?

**Comment by benjycui** [comment]
`onChange` https://github.com/react-component/slider

http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by wzup** [comment]
@benjycui 
What was that with smart questions? I can offer you to try smart answers.

I know about `onChange` method all right.
Now imagine, please, a situation when you need to get current slider value from within other component. Not **BY MOVING** slider and calling `onChange` but from stopped slider. How can I do it? Get value without calling `onChange`?

**Comment by benjycui** [comment]
http://facebook.github.io/react/docs/thinking-in-react.html

**Comment by nejlika** [comment]
In case somebody is still wondering, onChange takes the bounds/value as an argument.

**Comment by BradZzz** [comment]
Lol. It's funny to come across these replies that completely miss what OP was asking. For anyone else who is looking for how to get the input value from the slider in the way that OP was describing, use a react [reference](https://blog.logrocket.com/how-to-use-react-createref-ea014ad09dba/), then look in the childnodes object for the input value and then reference like so: **player.seekBarRef().current.childNodes[2].value**. Good luck!

**Comment by chakmear** [comment]
I was also amused by reading the non-thinking-about-question-answers... also wanted to read out the value of the slider in the moment I changed another React-Switch.
Of course I could build up a reference but I also found the value of my reactSlider to be written simply in the element.innerText-variable... but I'm not sure if that is always the case :)
