### ISSUE TITLE
Error when dragging 

### ISSUE THREAD

**Issue by hdao3363** [react-component/slider#935]
<img width="621" alt="image" src="https://github.com/react-component/slider/assets/90520841/2f799fb1-4be3-41d1-bd47-844e3bbea144">

I got the error above just by dragging. The error only shows up if I `setValue`. This is how I init the component

                <Slider
                    range
                    allowCross={false}
                    defaultValue={[filterOptions.price[0], filterOptions.price[1]]}
                    onChange={(value) => {
                        if (value != null) {
                            // const test = value[0] 
                            // console.log(test) <--- will log the right information 
                            setValue(test) <--- cause the error above
                        }
                    }}
                    style={{ marginLeft: "6px" }}
                />

**Comment by alexandermirzoyan** [comment]
I have same problem
