### ISSUE TITLE
Why onAfterChange deprecated?

### ISSUE THREAD

**Issue by Enkratia** [react-component/slider#938]
'onAfterChange' is deprecated.ts(6385)
Slider.d.ts(37, 9): The declaration was marked as deprecated here.

Why onAfterChange is deprecated? Right now just one event (onChange) is available?

**Comment by yoyo837** [comment]
`onChange` is enough.

**Comment by antoineol** [comment]
Hi there! I have a use case where onChange does not fit my need. I need to wait for the user to finish choosing a value, then auto-send + close a popover containing the slider. onChange does not allow to do that (at least not in a clean way), and onAfterChanges does it perfectly.

I would suggest not to deprecate it. Maybe document, instead, that onChange should be preferred over onAfterChange for most use cases. Does it sound reasonable?

**Comment by alexandermirzoyan** [comment]
@antoineol can you use **onChangeComplete**?
