### ISSUE TITLE
Cannot move handles

### ISSUE THREAD

**Issue by nwehrle** [react-component/slider#97]
### Example
`<RcSlider range={true} min={0} max={40} defaultValue={[10, 10]}/>`

### Expected
Both handles overlap eachother. I can touch and move a handle to the left or right.

### Actual
I cannot move any of the handles.

### Videos
Component:
![component](https://cloud.githubusercontent.com/assets/832234/14826880/282ba9f2-0be0-11e6-9d63-e4f4697481cb.gif)

DevTools: 
![devtools](https://cloud.githubusercontent.com/assets/832234/14827042/c421a898-0be0-11e6-87d8-852b772d9f48.gif)

### Versions
rc-slider@3.5.1

**Comment by benjycui** [comment]
3.6.2
